### ISSUE TITLE
org-jira-get-issues only adds one issue to buffer

### ISSUE THREAD

**Issue by iqrow** [ahungry/org-jira#100]
After running `org-jira-get-issues`

This successfully fetches the issues and then adds only the first one from the 
`issues` array in the JIRA response JSON. It adds this one issue to the end without
logging an error. It will append the same single issue again each time it's run, so
the buffer will have for example 'Sample Task :PROJ_110:' several times, one after
the other.

Anything I can do to debug this? Thanks.

*Edit*

If it helps, when running `org-jira-get-issue`

This successfully fetches an issue and then adds it to the bottom of the `PROJ.org`
buffer but doesn't navigate to the buffer and outputs a `listp` error, but this one from helm.

```
REQUEST [debug] symbol-status = success
Tag :PROJ_1072: set in 1 headings
helm-M-x: Wrong type argument: listp, []
```

**Comment by ahungry** [comment]
Odd, nothing here in this package calls helm (`helm-M-x` in particular) - try clearing your PROJ.org buffer so there is nothing in it, and try the fetch again.  A couple months ago there was an update to nest all issues under a single top level headline.

**Comment by greened** [comment]
I am having a similar problem.  The first call to `org-jira-get-issues` returns without opening the buffer:
```
Fetching issues...
Received data for org-jira-get-issue-list-callback.
Fetching issues...
About to render 100 issues.
Use M-x make-directory RET RET to create the directory and its parents
```
The second call actually brings up the buffer:
```
Fetching issues...
Received data for org-jira-get-issue-list-callback.
Fetching issues...
About to render 100 issues.
File /Users/dag/.org-jira/PE.org is read-only on disk.  Make buffer read-only, too? (y or n) y
```
Further calls do not appear to alter the buffer.

**Comment by greened** [comment]
If I do `C-c ig` from within the jira org buffer, the same issue appears a second time, just as iqrow reported.

**Comment by greened** [comment]
I disabled most of my init.el and managed to get multiple issues returned and things basically work AFAICT.  Now I'll start re-enabling things and see what breaks it.

**Comment by greened** [comment]
Two things I learned.

1. When  emacs asks whether to open the org file read-only, one must respond with 'n', otherwise issues don't get added to it.
2. The realgud package was messing up my org config for some reason.

I still get the message about `make-directory` and I have no idea what that's about, but at least I am getting more data presented.  I'm not yet convinced it's all the data but it's a good start.

**Comment by ahungry** [comment]
If it tries to save in ~/.org-jira and the directory doesn't exist, make-directory may be prompting you for explicit permission to make it.
