### ISSUE TITLE
support changing the reporter via org-jira

### ISSUE THREAD

**Issue by nickgarber** [ahungry/org-jira#102]
Hello!

I've tried to accomplish this by making the change in the properties drawer and updating the issue. 

I also looked around for a function that would make this change directly. 

I didn't see one but maybe it would/could be added to `(org-jira-update-issue-details)`?

Is there an existing way to do this? If not, is this function to place to add it?

Cheers!

**Comment by ahungry** [comment]
You could probably borrow logic from the assignee functionality to implement something similar.

**Comment by nickgarber** [comment]
Cool, I'll take a peek next chance. Thanks!

**Comment by nickgarber** [comment]
Cheers @ahungry!

**Comment by nickgarber** [comment]
Just want to note this. I've found that my implementation of this feature doesn't work 100% of the time so I'll revisit it next chance with a corrective adjustment.

**Comment by ahungry** [comment]
Awesome, thanks for the find
