### ISSUE TITLE
Question: How to fill Jira ticket's 'Component' field?

### ISSUE THREAD

**Issue by ababushk** [ahungry/org-jira#103]
Hello!
Thank you for great addon! It is very convenient to work with Jira tickets in emacs org-mode.
Is there a possibility to specify 'Component' field during ticket creation from scratch or from org TODO field? For now I just copy-paste `:components:` filed in `:PROPERTIES:` section of org-mode item.

**Comment by ahungry** [comment]
Can you show me some samples of what this looks like in your property drawer?  (What values go in `:components:` ?

**Comment by oxygenxo** [comment]
Sure!
For example, I'm creating new ticket via `org-jira-create-issue`. This function asks me to enter Project, Issue type, Assignee, Description.
As a result I have the following:
```
*** TODO Add some tests :CVS_12345:
    :PROPERTIES:
    :assignee: andrewb
    :reporter: johne
    :type:     Task
    :priority: Undecided
    :status:   New
    :created:  2018-07-04 18:50:41
    :updated:  2018-07-06 11:02:46
    :ID:       CVS-12345
    :CUSTOM_ID: CVS-12345
    :END:
    :LOGBOOK:...
***** description: CVS-12345
        Now we have only Ubuntu, should have runs on CentOS as well
```
I have to fill Components field in my ticket (due to team's conventions) and I do this manually by inserting `:components:` string into `:PROPERTIES:` section like this:
```
*** TODO Add some tests :CVS_12345:
    :PROPERTIES:
    :assignee: andrewb
    :reporter: johne
    :type:     Task
    :priority: Undecided
    :status:   New
    :components: Continuous Integration, E2E tests
    :created:  2018-07-04 18:50:41
    :updated:  2018-07-06 11:03:46
    :ID:       CVS-12345
    :CUSTOM_ID: CVS-12345
    :END:
    :LOGBOOK:...
***** description: CVS-12345
        Now we have only Ubuntu, should have runs on CentOS as well
```
And calling `M-x org-jira-update-issue`. Is there any way to do this automatically during ticket creation?

**Comment by ahungry** [comment]
Sure, are components derived from a select list of some sort, or are they arbitrary/automatically created like labels?

**Comment by ahungry** [comment]
I started working on this, just have to tie it in soon(ish)

**Comment by nickgarber** [comment]
The 2-way component sync feature is working. 
When adding a component to the org-jira task's `components` property and updating the issue, the updated components show up on the task in Jira.

Perhaps this request is close-able?

**Comment by ahungry** [comment]
So, we already show COMPONENTS in the property drawer - this comment is a reminder to myself on this issue, that the pending ask here is that we make it interactive to select which components to add to the list based on a selection.

**Comment by ahungry** [comment]
If someone makes a PR, this would be a welcome addition.
