### ISSUE TITLE
Drawers expand when calling org-jira-update-* functions

### ISSUE THREAD

**Issue by Fuco1** [ahungry/org-jira#107]
This makes the buffer jump around, is it really necessary to expand the drawers and move the point?

This also happens on `org-jira-add-comment` and other such commands.

**Comment by Fuco1** [comment]
I think this is an issue with the async callback handlers... it also changes my window setup or changes current buffers.  We need to make sure everything is wrapped in `save-window-excursion` and `save-selected-window`.

**Comment by ahungry** [comment]
I like that idea - I'll probably look into this next

**Comment by Fuco1** [comment]
@ahungry There's also code using `(org-cycle 1)` a lot, I don't think there's any reason to do that.  Search functions such as `re-search-forward` and `search-forward` work with folded text.

This is for example in the `org-jira-update-worklogs-from-org-clocks` function

**Comment by Fuco1** [comment]
This works much better on master now already.  The buffer stays focused and does not jump around.  Good work so far!

**Comment by ahungry** [comment]
Thanks!
