### ISSUE TITLE
Map jira states to org mode TODO states

### ISSUE THREAD

**Issue by Fuco1** [ahungry/org-jira#109]
Right now everything is synced to a TODO state for me.  How does this work?  I use TODO/NEXT/DONE in Emacs and I'd like to be able to tell `org-jira` how to translate between the states of jira and org mode.

**Comment by ahungry** [comment]
Check out https://github.com/ahungry/org-jira/issues/81 - we just had this feature completed this week, so you should be able to customize it and use it as asked now
