### ISSUE TITLE
Do not reinsert top-level header if I put a todo keyword on it.

### ISSUE THREAD

**Issue by Fuco1** [ahungry/org-jira#110]
I've changed

```
* SC-Tickets
```

to 

```
* TODO SC-Tickets
```

because I have some custom features that require a todo keyword on a parent.  Now when I do a refresh it re-inserts this again without the todo keyword.  I think the code responsible is

```elisp
                    (unless (looking-at (format "^* %s-Tickets" proj-key))
                      (insert (format "* %s-Tickets\n" proj-key)))
```

Wouldn't it be better to use the built-in org mode filtering features instead of regexps directly?

```elisp
(let ((element (org-element-at-point)))
  (unless (and (eq (car element) 'headline)
               (equal (plist-get (cadr element) :title) "...Tickets"))))
```

could be a start.

**Comment by ahungry** [comment]
It might be better - not sure if this is still relevant. 

If it is, and someone makes a PR, we can incorporate it.
