### ISSUE TITLE
Put the properties under a "namespace"

### ISSUE THREAD

**Issue by Fuco1** [ahungry/org-jira#113]
this package creates a bunch of properties like `:created:` `:type:` and so on. I think those should be prefixed by e.g. `org_jira_` because they might overwrite some custom properties I put on the task.

I'm not sure if I can acutally do that now and if they are removed on sync, but I would hope they wouldn't because I would like to have extra properties for e.g. org-agenda integration.

**Comment by ahungry** [comment]
Good idea, maybe we can add a defcustom for prefix, and set it to empty to start to preserve BC with the existing files people have already generated.

**Comment by ahungry** [comment]
If anyone wants to PR this, feel free.
