### ISSUE TITLE
Some of the macros have incorrect debug declarations

### ISSUE THREAD

**Issue by Fuco1** [ahungry/org-jira#114]
For example `defmacro ensure-on-issue-id (issue-id &rest body)` has debug set to `(declare (debug (body)))` which does not include the issue-id which means it is now not possible to edebug any function which uses this macro.

I'm starting a lot of issues, just to keep track, I might be able to work on some myself so please don't feel overwhelmed :) I'm really happy I've discovered this project, it's already helping me a lot to improve my workflow.

**Comment by ahungry** [comment]
I love the feedback, so please keep it coming!  Between inheriting this project and being new(er) to Elisp when I did back then, I'm sure there are many opportunities to polish it up.

**Comment by ahungry** [comment]
Just using debug t on them now, should be good, let me know what you think (see f566fae)
