### ISSUE TITLE
Need to have sync worklog tie into the org clock in/out entries

### ISSUE THREAD

**Issue by ahungry** [ahungry/org-jira#12]
Would make adding time to the system much easier.

**Comment by khaije1** [comment]
This would have a big helpful impact in my day to day life, and though an ELisp novice I'd like to help out however possible?

Any pointers on how to start contributing code or documentation to this project?

**Comment by ahungry** [comment]
Sure, what you've been doing so far is great (filing issues / feature requests), another thing you can do while getting up to speed is spread the word (the more users the better).

To get used to working with the code, you should remember `C-M-x` key re-evaluates the defun (so crack open the file and try tinkering with the code if you have a test jira instance), and the same command with universal prefix pressed first will enable debugging/stepping (a useful elisp feature).

**Comment by khaije1** [comment]
/me works on setting up a test instance ...

Thanks @ahungry!

**Comment by ahungry** [comment]
This is about 99.9% complete in the feature/worklog branch.

This is a call for testers of the branch (see the changelog in https://github.com/ahungry/org-jira/tree/feature/worklog ) - there is a new defcustom to disable worklog sync, but otherwise org-clock entries and worklog entries on the Jira instance will now sync 2 way.

if I don't hear negative feedback / issues in the next few days, I will be merging to master for all to try.

**Comment by khaije1** [comment]
So excited will test tonight!

Do these work the same as before, where time is recorded only when logged under the '** worklog:' entries?

Could you describe a bit of the workflow please?

**Comment by ahungry** [comment]
No, the worklog entry stuff can basically be deprecated (I should probably remove entirely).

Basically, log into your clocks at the top level with a clock drawer enabled (new org default - I haven't set it up to work without a drawer yet, but it should work with a custom drawer).

Basically, clock into a task, clock out, add some plain text underneath the org clock entry and sync the issue (org-jira-update-issue) to Jira, and the clocks will sync up as well (they'll become worklog entries).

Alternatively, start by adding a few worklog entries on a Jira task, then resync the org entry with the Jira endpoint and you'll see the worklogs populate.

I'll make sure to update the README and patch notes in the .el files to reflect some of this before the branch is merged to master.

Let me know what you think!

**Comment by khaije1** [comment]
It's looking great! A couple items that I think would go a long way as an end user:

1) more controls on which worklogs are sync'd, for example: by user, by time range, by relative time, by list of projects, by list of issues, by org-tag
  - For example, if I have an org-mode clock log going back years and have been manually entering time in Jira for the past there may already be reporting performed based on Jira's worklogs that should not be altered.
  - Ideally, it'd be useful to be able to sync logs within the current month, but leave logs older than that unaltered and in place.
 - Since some jira-issues will contain worklogs from many different people. Is it only the worklogs of the individual that show up in the org-issue?

2) display the user associated with each worklog entry in the CLOCK drawer
  - Many tasks will have time include tracked by multiple people. It may be interesting to see this info but not necessarily, (as a non-manager individual), helpful to include the time data of other people in org-mode clockreports and org-agenda and the like.

So far isolated testing has gone well. With the above questions unclear I've been limited in the extent/complexity of testing I've attempted.

In order to switch to fully using this I'm considering this procedure.
1. save and backup existing org-jira files
2. remove them
3. re-sync issues from Jira instance into org-jira
4. make manual clocking adjustments to the clocking histories of the relevant issues (in my case, those worked this current month)
5. Enjoy a quality of life bump-up as a result of a seamless org-mode clocking experience, without need to manually enter time in Jira.

Sound right, did I miss any important details or even opportunities?

**Comment by ahungry** [comment]
Currently anything that updates an issue's Jira data will update the worklog on that issue on the Jira end.  Likewise, anything synced from Jira to the org buffer will include syncing the worklogs to the org clock data (unless `org-jira-worklog-sync-p` is nil).

Since I just merged the worklog sync to master, I'll go ahead and make new issues out of your suggestions (all very good!) or you can if I don't get to it (may be a couple days before I have a chance, so if you want to just file an issue for each suggestion, go for it, I would appreciate it!).

Btw, I find using org-jira with ~/.org-jira initialized as a git repo makes the process a lot smoother (easy to see what changes on syncing etc.).

**Comment by khaije1** [comment]
Sounds good @ahungry, your work on this is greatly appreciated!

**Comment by nickanderson** [comment]
@ahungry I just tried this from a fresh master.

is my LOGBOOK drawer that contains all of my CLOCK entries supposed to end up in an issue comment directly?

Is org-jira-update-comment expected to take any clock data from that comment and add it to the issue?

**Comment by ahungry** [comment]
Odd, the answer to both is no, you should see LOGBOOK drawer go directly under the PROPERTIES of the top level issue (this assumes you do the org-clock-in directly on the issue header, vs on a comment header).

Although, if you didn't actually clock under a Comment heading, and the fetch of Jira worklog produced those drawers in those locations (under comments) that is definitely an issue - can you provide a sample structure of the issue?  (Does the issue have a PROPERTIES drawer at the top level?  Is it missing it perhaps, and only has one under a Comment issue?  What happens if you use a new/empty buffer and do the get-issues calls?)

**Comment by nickanderson** [comment]
OK.

1) I was clocking into the comment itself.
2) I just created a clock entry in the top of the issue itself and ran {{org-jira-update-worklogs-from-org-clocks}} which removed the clock entry from the top of the file.

Before worklog sync
```
* TODO filesexist expression evaluates to true on empty slist :CFE_2631:
:PROPERTIES:
:assignee: a10003
:reporter: mattyasovszky
:type:     Bug
:priority: Medium
:status:   To Do
:components: Built-in functions
:created:  2017-05-09 11:55:17
:updated:  2017-05-10 16:46:41
:ID:       CFE-2631
:END:
:LOGBOOK:
CLOCK: [2017-05-10 Wed 15:59]--[2017-05-10 Wed 16:15] =>  0:16
:END:
```

After

```
* TODO filesexist expression evaluates to true on empty slist :CFE_2631:
:PROPERTIES:
:assignee: a10003
:reporter: mattyasovszky
:type:     Bug
:priority: Medium
:status:   To Do
:components: Built-in functions
:created:  2017-05-09 11:55:17
:updated:  2017-05-10 16:46:41
:ID:       CFE-2631
:END:
:LOGBOOK:
:END:
```
3) I tried deleting all my org-jira files and re-fetching them using org-jira-get-issues. Now when I clock into the top level of an issue and run worklog sync the log is added in jira, and the entry remains in LOGBOOK.

4) Adding a CLOCK entry to a Comment (I guess this is not supported? Perhaps it should get some explicit warning?)  If I {{org-jira-update-worklogs-from-org-clocks}} first the clock entries in jira are updated. When I {{org-jira-update-comment}} the LOGBOOK entry is written with comment itself and worklog in jira (indented like the comment text itself (unlike the properties drawer).

```
** Comment: a10042
:PROPERTIES:
:ID:       79797
:created:  2017-05-11 07:09:30
:END:
  :LOGBOOK:
  CLOCK: [2017-05-11 Thu 09:07]--[2017-05-11 Thu 09:08] =>  0:01
  :END:
  
  Testing.

```

**Comment by ahungry** [comment]
So, clocking under a heading is an org feature, and I think it would be a lot of work to explicitly disable it in the org-jira mode for comments only (and imho, it doesn't make a ton of sense to clock against a comment, since Jira doesn't have an equivalent, but I can see why someone may want to do that).

The reason your issue disappeared on #2 is that syncing from Jira deletes the local entries first, so it can refresh with the remote ones after.

For #3, it sounds like all is working as expected.

For #4, same thing, I didn't really set any of the clocking up to support clocks under comments, so the parser for how it chooses where to place the logbook doesn't accommodate that at all (although it may be a good idea for me to fix, but that may be confusing as users would expect that to sync to Jira, and it wouldn't).
