### ISSUE TITLE
Update README instructions for setting jiralib-token

### ISSUE THREAD

**Issue by samspills** [ahungry/org-jira#121]
While setting up org-jira (I'm using spacemacs v0.300.0 with emacs v25.3.1), I followed the instructions for supplying a cookie like so:
```
(defconst jiralib-token
  `("Cookie" . ,(format "long cookie string goes here")))
```

This was giving me errors about format expecting more arguments than I was providing. I'm not very good with lisp so maybe there's a really simple thing that I should have changed, but I couldn't figure it out. 

Eventually I ended up setting `jiralib-token` like so:

```
(setq jiralib-token
    `("Cookie" . "long cookie string goes here"))
```
and that worked for me. Should the readme instructions be updated?

**Comment by ahungry** [comment]
Yes, the format is not needed, and indeed, if your cookie string has a `%` in it, format is going to assume it needs to interpolate some value, so it should just be a plain old hard-coded string instead.

**Comment by samspills** [comment]
Oh!! That makes sense. Okay, that's definitely just me not quite understanding `format` and my cookie. Thanks for your time!
