### ISSUE TITLE
Make it possible to discard time logged by users other than me.

### ISSUE THREAD

**Issue by Fuco1** [ahungry/org-jira#122]
When I fetch an issue I get the worklog from all the team members.  This seriously breaks the agenda/dblock reporting of time spent on stuff.

It should be possible to filter worklogs and only convert to `CLOCK:` entries which are done by "me".

**Comment by nickgarber** [comment]
Hi Matus,

This was added earlier this year. Gotta run at the moment but I'd like to
assist if you have any resulting questions or suggestions.

from my 'Org JIRA' customize group:
```
Jiralib Worklog Import  Filters Alist:
[INS] [DEL] List:
            Boolean: [Toggle]  off (nil)
            String: WorklogUpdatedByCurrentUser
            Function: (lambda (wl) (let-alist wl (when (and wl
(string-equal (downcase jiralib-user-login-name) (downcase
\.updateAuthor\.name))) wl)))
[INS] [DEL] List:
            Boolean: [Toggle]  on (non-nil)
            String: WorklogAuthoredByCurrentUser
            Function: (lambda (wl) (let-alist wl (when (and wl
(string-equal (downcase jiralib-user-login-name) (downcase
\.author\.name))) wl)))

```

**Comment by ahungry** [comment]
Yup!  We have this in the jiralib section:

```
	 (defcustom jiralib-worklog-import--filters-alist
           (list
            '(nil "WorklogUpdatedByCurrentUser" (lambda (wl) (let-alist wl (when (and wl (string-equal (downcase (or jiralib-user-login-name user-login-name)) (downcase\
          .updateAuthor.name))) wl))))
	    '(nil "WorklogAuthoredByCurrentUser" (lambda (wl) (let-alist wl (when (and wl (string-equal (downcase (or jiralib-user-login-name user-login-name)) (downcas\
         e .author.name))) wl)))))
           "A list of triplets: ('Global-Enable 'Descriptive-Label 'Function-Definition)                                                                                 
         that apply worklog predicate filters during import.                                                                                                             
                                                                                                                                                                         
         Example: (list '('t \"descriptive-predicate-label\" (lambda (x) x)))"
           :type '(repeat (list boolean string function))
           :group 'org-jira)
```

Although it may not be a bad idea to put in the README if we haven't yet.

**Comment by Fuco1** [comment]
Oh.  A user option should definitely not be with `--` that signifies a private/internal variable/function, but the whole point of an option is to have it public.

I'll check it out, thanks!

**Comment by nickgarber** [comment]
I noticed that it stood out but wasn't sure if it was appropriate or not.
I'd like it to be as correct as possible. Is there a non-breaking way to
change it?

Also it was challenged by picking a descriptive name, so I'd be interested
to know if there's a better and clearer name.

**Comment by Fuco1** [comment]
@nickgarber There is a function `make-obsolete-variable` which will mark the old name as obsolete and set up an alias from the old to new so that users have a chance to migrate over time.  When you byte-compile you will get a warning if you use an obsolete variable.

```
make-obsolete-variable is a compiled Lisp function in ‘byte-run.el’.

(make-obsolete-variable OBSOLETE-NAME CURRENT-NAME WHEN &optional
ACCESS-TYPE)

Make the byte-compiler warn that OBSOLETE-NAME is obsolete.
The warning will say that CURRENT-NAME should be used instead.
If CURRENT-NAME is a string, that is the ‘use instead’ message.
WHEN should be a string indicating when the variable
was first made obsolete, for example a date or a release number.
ACCESS-TYPE if non-nil should specify the kind of access that will trigger
  obsolescence warnings; it can be either ‘get’ or ‘set’.
```

**Comment by lvsv** [comment]
https://github.com/ahungry/org-jira/issues/122#issuecomment-411618589
@ahungry `jiralib-worklog-import--filters-alist` doesn't work by default,  first parameter of each element in the list is `'nil` and this element will not be applied as a filter function.

Based on the example of `jiralib-worklog-import--filters-alist`, first parameter should be `'t`.
```
Example: (list '('t \"descriptive-predicate-label\" (lambda (x) x)))"
```
Is it a bug or feature? There are nothing about of the `jiralib-worklog-import--filters-alist` in the README.

**Comment by ahungry** [comment]
I think this feature just needs tidying up - iirc, the default was to maintain backwards compatibility and not filter things that were previously unfiltered, but we would want the defcustom to be single dash and maybe make more useful defaults etc.
