### ISSUE TITLE
Callbacks in org-jira-update-worklogs-from-org-clocks might run in different buffer.

### ISSUE THREAD

**Issue by Fuco1** [ahungry/org-jira#126]
When I call `org-jira-update-worklogs-from-org-clocks` on the issue it fires the updates to jira with `jiralib-add-worklog` which on completion calls `org-jira-update-worklogs-for-current-issue`.

But this might run in a completely different buffer because in the meantime I could've switched or the original call might have been made from `org-clock-out-hook` (which runs in context of the clocked issue) but my focus was in a different window.

I think we need to pass some parameters to `org-jira-update-worklogs-for-current-issue` and make sure it is run in proper context.

Easiest way would be to enable `lexical-binding` in the file and just use that (we can then also get rid of `lexical-let` which is really outdated).

**Comment by ahungry** [comment]
I'm doing this on the new sdk branch (a lot of these random contextual calls will be specific with the issue-id sent in at call time, and lexical-binding enabled at top of file(s).

**Comment by Fuco1** [comment]
Was there any progress on this?  It's extremly annoying I'm getting a tons of broken syncs because of errors "point is not on an issue".

I don't understand the complexity or mabye I'm using it wrong but this is pretty annoying.  I often end up copying the time tracking IDs into org manually (because the next sync submits the times multiple times otherwise).

**Comment by ahungry** [comment]
Sorry I forgot to loop back around to this, it should be fixed in 4.0.3 now, if you find otherwise please let me know and I'll reopen.

**Comment by Fuco1** [comment]
No worries!

**Comment by Fuco1** [comment]
@ahungry Yep, just updated to the latest release and it works excellent!  Great job, this makes the UX so much better.
