### ISSUE TITLE
Allow configurable mapping between Jira Fields and Org properties

### ISSUE THREAD

**Issue by khaije1** [ahungry/org-jira#13]
This would reduce duplication of similar data within existing properties used by Org-Mode's various integrations.

I have some fields already setup for http://orgmode.org/worg/exporters/taskjuggler.html integration, and if it were possible to tell org-jira to map the Assignee field to the WorkedBy property, (for example), it would allow me to use some taskjuggler reporting on org-jira tasks.

**Comment by ahungry** [comment]
Not a bad idea.

**Comment by ahungry** [comment]
This is now available via a new defcustom for org-jira-property-overrides, try it out and let me know what you think.

**Comment by khaije1** [comment]
Looking good! Sweet thanks!
