### ISSUE TITLE
Melpa recipe isn't pulling org-jira-sdk into package

### ISSUE THREAD

**Issue by codelahoma** [ahungry/org-jira#137]
Title kinda says it all.

**Comment by ahungry** [comment]
Crap, sorry, fixing....

**Comment by ahungry** [comment]
https://github.com/melpa/melpa/pull/5702

**Comment by ibizaman** [comment]
this is the one: melpa/melpa#5705

**Comment by ahungry** [comment]
I confirmed that this is for sure not an issue on a fresh Emacs under a fresh user, so closing this old ticket.
