### ISSUE TITLE
Error when creating subtask: wrong number of arguments

### ISSUE THREAD

**Issue by samspills** [ahungry/org-jira#138]
I'm getting an error when trying to create a new subtask with org-jira. The error is:

```
jiralib-call: Wrong number of arguments: #[(api &rest args) "ÆÇÈÉÊ\"ËÌÍ #ËÎÏ#PÐ?ÑÒBÓÔÕ&ÖH>8×ØÙD\"ÚH)Û\""
[api jiralib-url jiralib-complete-callback jiralib-token args cl-x append apply request string-match ...] 14 ("/Users/sam/.emacs.d/elpa/25.3/develop/org-jira-20180808.311/jiralib.elc" . 10709)], 0
```

I'm on the develop branch of spacemacs right now, and emacs 25.3. I looked at the `org-jira-create-subtask`  and followed it down to `jiralib-call` for the `createIssueWithParent` and saw that `jiralib--rest-call-it` was being called without any arguments and has been for the last three years. That's as far as I could get, I don't really understand what to make of the lack of passed arguments there.

**Comment by ragone** [comment]
Any progress on this?

**Comment by vlladdrakk** [comment]
I made a pull request (#180) that fixed an issue creating subtasks, did that fix this issue? @samspills @ragone

**Comment by samspills** [comment]
Hey @vlladdrakk, thank you for opening a pr! Unfortunately I've switched jobs and the new org doesn't use jira so I can't easily test. Hopefully it works though!

**Comment by methuselah-0** [comment]
Thanks for this fix! I can confirm it's working when using org-jira-create-subtask and choosing type sub-task, but if using org-jira-create-issue and selecting type sub-task it doesn't work.

**Comment by vlladdrakk** [comment]
@methuselah-0 What error message are you getting? If I recall correctly I was not able to create an issue before my changes were merged. I can only get the the first step, entering the project id. Once I hit enter I get `Wrong type argument: symbolp, "Sub-task"` is that the error you are getting?
