### ISSUE TITLE
Error on create issue

### ISSUE THREAD

**Issue by 11111000000** [ahungry/org-jira#139]
On org-jira-create-issue

` SOAP error: "soapenv:Server.userException", "com.atlassian.jira.rpc.exception.RemoteValidationException: {customfield_10001=Подразделение  обязательно., versions=Проявляется в версиях  обязательно., customfield_10100=Тестировщик  обязательно., components=Компоненты  обязательно.} : []", ((detail nil (com\.atlassian\.jira\.rpc\.exception\.RemoteValidationException ((xsi:type . "ns1:RemoteValidationException") (xmlns:ns1 . "http://exception.rpc.jira.atlassian.com"))) (ns2:hostname ((xmlns:ns2 . "http://xml.apache.org/axis/")) "Triton")))`

**Comment by ahungry** [comment]
Are you using the SOAP integration? That is not well tested after maintenance change, can you use the REST mode?

**Comment by 11111000000** [comment]
I will need this module again just now, will try!

**Comment by ahungry** [comment]
Closing for now, if a PR is made, we can review.
