### ISSUE TITLE
Sync task 'Due Date' with Org-Mode Deadline task cookie.

### ISSUE THREAD

**Issue by khaije1** [ahungry/org-jira#14]

**Comment by ahungry** [comment]
This is a good one, I'll probably implement this unless you're WIP on it or anything.

Do you know if there is more to the org deadline than simply adding the tag?  (no need to invoke org-deadline to handle some hidden file/cookie generation or anything)?

**Comment by khaije1** [comment]
I'm not WIP on it. 

> Do you know if there is more to the org deadline than simply adding the tag?

My understanding is that it's safe to simply write out the cookie. This belief comes from having successfully edited this cookie and lots of other content from Notepad and other OrgMode-aware editors.

**Comment by ahungry** [comment]
Added, new defcustom org-jira-deadline-duedate-sync-p also exists now, it can be set to nil if for some reason the user doesn't want these 2 dates to be synced up.

**Comment by khaije1** [comment]
This is working great! Thank you!
