### ISSUE TITLE
Question: Possible to update jira status automatically with org status?

### ISSUE THREAD

**Issue by samspills** [ahungry/org-jira#140]
I setup the `org-jira-keywords-to-jira-status-alist` to map jira statuses to my org-mode task workflow, so when I fetch issues they're inserted with the correct status. This is awesome :D However, is it possible to go the other way? If I clock-in to a task, it is automatically updated to be `STARTED` and I'd like for that to trigger jira to update the issue to `In Progress`. 

If this isn't possible, has any thought been put into how to accomplish it? I'd love to contribute but I'm not sure how to get started.

**Comment by ahungry** [comment]
It would definitely be doable, look at function org-jira-progress-issue-next (the bottom part, the rest is just parsing actions out of an alist or the thing at point) - the part you would need is at the end, the jiralib API call, which takes:

```
 (jiralib-progress-workflow-action
			issue-id
			action
			custom-fields
			(:with-callback
                         (ensure-on-issue-id issue-id (:refresh-issue))))
```

So, action is the action id - in a form similar to this:

```
                (setq jiralib-available-actions-cache
                      '(("To Do"
                         ("71" . "Business Question")
                         ("11" . "Start Progress"))
                        ("Code Review"
                         ("71" . "Business Question")
                         ("91" . "Reject")
                         ("171" . "Failed Peer Review")
                         ("221" . "Done"))
                        ("In Development"
                         ("71" . "Business Question")
                         ("241" . "No QA Needed")
                         ("21" . "Ready For Review")
                         ("81" . "Reject")
                         ("161" . "Stop Progress"))
                        ("Done"
                         ("71" . "Business Question")
                         ("141" . "Reopen")
                         ("231" . "Re-Open"))))
                (setq org-jira-progress-issue-flow
                      '(("To Do" . "Start Progress")
                        ("In Development" . "No QA Needed")
                        ("Code Review" . "Done")
                        ("Done" . "Reopen")))
```

You would basically want to have a hook on org mode's org-after-todo-state-change-hook that called this, but instead of the logic in org-jira-progress-issue-next picking which ID to transition to/from, you would want to map that to your org statuses if you used multiple status like TODO / IN-PROGRESS / DONE (I guess you could tie into clock as well, but that may not be as good if you clock multiple entries).

By the way, sweet avatar icon :smile:

**Comment by samspills** [comment]
Thanks for the helpful comment!!! I've forked the repo and made some progress. On my own branch I've created a shared `org-jira-progress-issue-action` function that takes the action id as an argument (and it is called by `org-jira-progress-issue` and `org-jira-progress-issue-next`). 

I have something in my .spacemacs that functions, but isn't yet perfect. However I'm going on vacation so I thought I would share my work so far here in case anyone else is interested. 

First, I defined a new alist that maps the action ID to the org-todo state for each project. Each of my projects have different status names and different workflows, which complicated the useage of `jiralib-available-actions-cache`. (My new variable doesn't take into account the available actions given the current issue status, but that seemed complicated, and our workflows are pretty simple). 

```elisp
(defvar sam/org-jira-org-action-ids-alist
    '(("PROJ-ONE"
       ("21" . "TODO")
       ("31" . "STARTED")
       ("41" . "DONE")
       ("51" . "WAITING")
       ("61" . "TODO"))
      ("PROJ-TWO"
       ("101" . "HOLD")
       ("111" . "DONE")
       ("81" . "TODO")
       ("41" . "WAITING")
       ("21" . "STARTED"))))
```

Then I defined a new function that is called by the `org-after-todo-state-change-hook`

```elisp
(defun sam/org-jira-todo-hook ()
    "Progress issue workflow."
    (ensure-on-issue
     (org-back-to-heading t)
     (let* (
            (element (org-element-at-point))
            (tag (car (org-element-property :tags element)))
            (status (org-element-property :todo-keyword element))
            (proj-key (replace-regexp-in-string "_.*" "" tag))
            (action (car (rassoc status (cdr (assoc proj-key sam/org-jira-org-action-ids-alist))))))
       ;; log everything
       (message tag)
       (message proj-key)
       (message status)
       (message action)
       (org-jira-progress-issue-action action))))
```

As I said, this is functional right now. It updates the jira status when I change state, and doesn't break anything when I'm not on an issue. It also seems to play nicely with my `org-clock-in-hook`, which switches a task to `STARTED` if I clock in and it has a status of `TODO` or `NEXT`. I'll keep working on this when I get back. I'd like to make a general hook function so that if anyone else wants the functionality they just have to add the hook to their config. 

Also, thanks!! 😁

**Comment by ahungry** [comment]
Seems like a cool addition, feel free to PR it!
