### ISSUE TITLE
EIEIO usage incompatible with emacs 25

### ISSUE THREAD

**Issue by Fuco1** [ahungry/org-jira#142]
Emacs 25 uses vectors to represent eieio classes, this code

```elisp
(defclass my-foo-class () ())

(eieio-class-slots (type-of (my-foo-class)))
```

breaks because `type-of` returns `vector` instead of, I guess, record syntax of E 26.

You should use

```elisp
(eieio-class-slots (eieio-object-class (my-foo-class)))
```

I'm not sure on how many places this is used.

**Comment by ahungry** [comment]
Good catch, I need to prioritize getting this set up with cask so I can have a reliable CI build to catch these things.

Fixed in commit dd3193e

**Comment by ahungry** [comment]
(it was only used in a dump/debug function to pretty print sdk class instances)

**Comment by Fuco1** [comment]
Thanks!  The SDK stuff looks good, though some things are a bit mysterious.  Why do you store the hydration callback in the object instead of dispatching on the methods?

When I first started using EIEIO I used the same pattern (storing callbacks) but then I figured it's unnecessary as you can do the same thing with the methods themselves.  But maybe there is some other point I'm missing.

**Comment by Fuco1** [comment]
You can see for example in Elsa, this diff: https://github.com/emacs-elsa/Elsa/commit/9c9bc2b38c117aaba98af7bff7a271c3a9c03d34#diff-621f58fee49edf2e9ec40d812b09327a

**Comment by ahungry** [comment]
In many of the runtime usage of the new classes, they are instantiated by the existing org-jira calls (I don't think I'm actually using the hydrate-fn anywhere atm), so it was more of a debugging device (so I could manually instantiate with the from-id call).

I guess I added as a callback fn reference, so I didn't have to redefine a custom defmethod on each record type if the majority all follow the same format (call some single jiralib with a single id passed in).  That way the base method for running the hydrate would work on all of them and that hydrate-fn could be defined inline with an initform at the defclass step.

**Comment by Fuco1** [comment]
`cl-defmethod` allows overriding on parent classes so you can also provide a default implementation that way.

Or right in `cl-defgeneric` also.  I think it's better to separate data structures (classes) and methods... I actually think that the classical OOP practice nowadays (data and functions are bound together) is quite bad.  There's a great essay http://www.smashcompany.com/technology/object-oriented-programming-is-an-expensive-disaster-which-must-end it's a good read but for the part about "Lisp OOP" you can search for this text:

> I want to offer some examples from a “functional style” language, and Clojure is the functional language I know best, so I will use that. In Clojure, inheritance is simple:
