### ISSUE TITLE
invalid priority options presented during org-jira-create-issue

### ISSUE THREAD

**Issue by khaije1** [ahungry/org-jira#15]
When selecting Priority, all Priorities are displayed, rather than priorities that are valid for the Project, resulting in an error when a priority that is invalid for that field is selected.

This could be confusing for the org-jira user. 

A preferable case would be to only present the statuses that are valid according to the information already presented to the user during the interactive M-x org-jira-create-issue dialogs.

**Comment by ahungry** [comment]
This is also an issue with Issue Type (it shows all issue types, not ones specific to a project).

I'll add a fix.

**Comment by ahungry** [comment]
Are you sure priority is a problem?  In testing, it seems like priorities are common across all projects.  Do you know how to configure Jira to provide custom priorities per project?  Is it just done with custom fields?

**Comment by ahungry** [comment]
I'm actually not sure there is an API mechanism to filter priority by project.  The endpoint currently being used to generate the list of priorities is from https://docs.atlassian.com/jira/REST/cloud/#api/2/priority-getPriorities .  I could add something like a priority exclusion or inclusion list (so only property names that matched the list would be shown?)

**Comment by khaije1** [comment]
Hi @ahungry, thanks for looking into this! I'll dig deeper into my case and follow up with some better info.

**Comment by khaije1** [comment]
You're correct: issue priorities are instance-wide, so the issue. description is incorrect. What would you recommend for getting debug info as this happens?

**Comment by khaije1** [comment]
I think this issue should be closed. Will reopen if needed but haven't been able to trigger it lately so it's looking to be in good shape. Thanks!

**Comment by ahungry** [comment]
Sweet!
