### ISSUE TITLE
Keep state logs in logbook

### ISSUE THREAD

**Issue by cslux** [ahungry/org-jira#151]
I have set `org-log-into-drawer` to non-nil...

> Non-nil means insert state change notes and time stamps into a drawer.
> When nil, state changes notes will be inserted after the headline and
> any scheduling and clock lines, but not inside a drawer.

Right now org-jira  removes the content, and replaces it with the time log data, unless `org-jira-worklog-sync-p` is set to `t`, I guess.  

Is this easy to implement, to keep the log entries (i.e. just ignore it), and keep it as it is.

Thanks!

Christian

**Comment by Fuco1** [comment]
For me the clock is logged into a `CLOCK` drawer, would that be an option?  That can be customized with setting `org-clock-into-drawer`

**Comment by cslux** [comment]
@Fuco1 That would be an option, but I personally prefer keeping it all at one place.

Thanks!

**Comment by cslux** [comment]
But yeah, since org takes care of the migration, why not set `org-clock-into-drawer` to `CLOCK`.

Thanks for pointing that option out!

regards,
Christian

PS: This option solved my problem, so closing this issue!

**Comment by Fuco1** [comment]
You can also set that locally for just the jira file if you prefer to keep it the old way elsewhere.  See [File local variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html#Specifying-File-Variables).

**Comment by cslux** [comment]
Yep

On November 19, 2018 5:04:12 PM GMT+01:00, Matus Goljer <notifications@github.com> wrote:
>You can also set that locally for just the jira file if you prefer to
>keep it the old way elsewhere.  See [File local
>variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html#Specifying-File-Variables).

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com
