### ISSUE TITLE
Question: logbook workflow

### ISSUE THREAD

**Issue by marc0s** [ahungry/org-jira#155]
Hi,

I've been using `org-jira` since a few weeks without any troubles. I mainly use it to fetch my Jira issues and track the time spent on them via `org-clock`.

I do the reporting from emacs instead of pushing the clock entries to Jira because only one of the entries get reflected in the overall logged in time (See https://community.atlassian.com/t5/Jira-Software-questions/Time-Tracking-quot-Logged-quot-shows-wrong-value/qaq-p/647203).

That seems to work fine and I could get updating my local issues' list without problems, but this morning some of my clock entries under `:LOGBOOK:` just disappeared.

What is your workflow with regard to time tracking?

Regarding my missing entries, are non-uploaded time entries discarded when syncing? What might be the cause of them disappearing?

Thanks!

**Comment by Fuco1** [comment]
Would this be helpful https://github.com/ahungry/org-jira/issues/151 ?

**Comment by marc0s** [comment]
Thanks for the hint @Fuco1 !

It didn't work for me or maybe I'm just to inexperienced to set it right.

Let's start from the beginning if you don't mind.

1. I run `org-jira-get-issues` and new buffers, one per project, appear.  I have them stored in the default, proposed path `~/.org-jira/<project>.org`.
2. I work with those files directly, is that OK?
3. I set `org-jira-worklog-sync-p` to `t` as in the linked issue, but after re-running `org-jira-get-issues` current clock entries are missing in the new buffers that appear (which are not merged with the on-disk contents). Maybe I'm expecting something here that is not going to happen?

Hope you can guide me somehow with this.

Thanks for your help!

**Comment by Fuco1** [comment]
I think you need to call `org-jira-refresh-issues-in-buffer` instead of fetching them again.
