### ISSUE TITLE
Separate files for each issue

### ISSUE THREAD

**Issue by rucarden** [ahungry/org-jira#156]
A couple of questions.
Would it require much effort to be able to have issues put into different files.   This was how I was tracking things prior to coming across org-jira.  

What are the rules for the syncing of nodes to jira,  are they ignored if they don't have a recognized heading?   I have notes for my tickets, that don't necessarily need to make it into jira.

Are there any rules about tickets that are done?  Is there a way to remove them so that they no longer show up?

**Comment by ahungry** [comment]
The default JQL will exclude tickets in a "Done" state (take a look at `org-jira-default-jql` variable).

Basically, anything you put in the Description area or nested under it is going to be synced to the server (and vice-versa, overwritten).

Maybe you could track your non-jira notes by using org links to point to the jira synced issues?

Syncing to random non-buffer locations would be a lot of work.

**Comment by Fuco1** [comment]
@rucarden I'm running into this same problem.  My current idea is to have the jira file in one file and my own notes (similar to your setup) in the other files.

I will then link the jira issues to my issues through an ID and automatically copy clock entries from my entries to the jira entries and run the update.

I might put this setup somewhere if others would be interested.
