### ISSUE TITLE
mitigate config-change/code-exec imported via sync'd buffer

### ISSUE THREAD

**Issue by nickgarber** [ahungry/org-jira#161]
(edited 2019-04-04)
----
mitigate config-change/code-exec imported via sync'd buffer

When a #+SETUPFILE: <some-url> directive is pulled in anywhere in an org-jira file, (for example in a Jira comment), it will have no immediate effect. However the next time the file is opened, the content at the pointed URL will be evaluated without prompting for the user's OK first.

This issue isn't specific to org-jira, but because it pulls in data from Jira it has a bit more exposure.

(originally)
---- 
Bi-directionally convert certain Jira Macros to Org-Mode Code Blocks

There's no need to support translation between all of them, but there are a few that might make sense:

- from `{noformat}` to `begin_example...end_example`, for example :)

I'm sure there are others that would make sense that dont immediately come to mind at the moment.

This would be a very nice usability boost and would close a significant risk factor.

The risk is that a passer-by would add (intentionally or otherwise) something that could be interpreted as an Emacs directive in a Jira comment. Once the comment is downloaded to a Jira file, the next time the file is loaded it would process that portion of the comment as a directive. Which is likely to have results somewhere in the "undesirable" range of the spectrum.

**Comment by ahungry** [comment]
Good idea - do you think it would process it with the default settings?  or only if the user was prompted and approved running arbitrary code (granted that may be approved without discretion for some).

**Comment by nickgarber** [comment]
You're asking about the risk exposure with default settings, right?

Yes, I recently found a `#+TODO:` in a Jira comment was being interpreted as an Emacs directive and was making my per-buffer `org-todo-keywords` org-mode todo status selection all wonky.

**Comment by nickgarber** [comment]
I realized I'm intertwining a problem report with a loosely related feature request... would you rather I separate them into different issues?

- Problem Report: Emacs directives may be innadvertantly Evaluated from Jira Comments (some protections needed?)
- Feature Request: Please convert Jira Macros into Emacs macros and vice-versa, where possible

**Comment by ahungry** [comment]
For the problem report - in what case would Emacs arbitrary evaluate code in the body of an org file?  I know of file locals, but that usually requires a user prompt to eval.

**Comment by nickgarber** [comment]
I'm not fully certain that unacknowledged code execution /is/ possible but I'll look into the question more deeply.

**Comment by bhipple** [comment]
Normally, org-mode will ask a user before executing any code in a block, so this ought to be safe.  It'd be really cool to convert this org-mode block

```
#+BEGIN_SRC sh
echo "Hello world"
#+END_SRC
```
to this Jira block
```
{code:language=bash}
echo "Hello world"
{code}```
and vice versa, with an alist to map the org-mode language syntax highlighting tags to the Jira ones.

**Comment by nickgarber** [comment]
Hi @bhipple I made it messy but mixing a problem/question and a feature request in one issue. Would you like to take the block-conversion idea into a different ticket? I could do it if you dont want to, but for what it's worth I think you've described as well as I would have :)

I'm going to edit the title and description of this issue in the next couple days to focus in on the security-oriented question, to make it clearer and easier to tackle.

**Comment by nickgarber** [comment]
@ahungry, the way I experienced this issue initially was with an in-buffer setting, (https://orgmode.org/manual/In_002dbuffer-settings.html). 

It changed my Emacs config in a way that felt like a fairly meaningful breakage... 

Seems like there are two questions:

 1. Can these in-buffer setting be better protected from inadvertant manipluation?
 2. Can the in-buffer settings be used to execute code?


The answer to '1' may be tied into the feature that @bhipple and I were chatting about.

It looks like the answer to '2' is 'no', but I'll try to source that from a more org-mode'ly expert than myself.

Thanks for being patient with this one!

**Comment by nickgarber** [comment]
OK, here's a big part of the answer to question 2 from above ...

```
#+SETUPFILE: file or URL

    The setup file or a URL pointing to such file is for additional in-buffer settings. Org loads this file and parses it for any settings in it only when Org opens the main file. If URL is specified, the contents are downloaded and stored in a temporary file cache. C-c C-c on the settings line will parse and load the file, and also reset the temporary file cache. Org also parses and loads the document during normal exporting process. Org parses the contents of this document as if it was included in the buffer. It can be another Org file. To visit the file (not a URL), C-c ' while the cursor is on the line with the file name. 
```

The SETUPFILE setting loading arbitrary code from the internet, it's a potential vector. 

I'm sure this issue isn't specific to org-jira, but because it pulls in data from Jira it has a bit more exposure.

When a `#+SETUPFILE: <some-url>` directive is pulled in anywhere in an org-jira file, (for example in a Jira comment), it will have no immediate effect. However the next time the file is opened, the content at the pointed URL will be evaluated without prompting for the user's OK first.


Is this making sense?

**Comment by nickgarber** [comment]
edits to separate and clarify issues #161 and #177

**Comment by nickgarber** [comment]
Org-Mode Code Blocks automatically perform some escaping on their contents to protect against this, (as discussed, https://irreal.org/blog/?p=5503).

I acknowledge that it's undesirable to maintain too many 2-way content transforms, but maybe some Org-Mode function can be use as a reference?

The comma-escaping is removed in:

```
(defun org-babel-execute:org (body params)                                                                                                                         
  "Execute a block of Org code with.                                                                                                                               
This function is called by `org-babel-execute-src-block'."                                                                                                         
  (let ((result-params (split-string (or (cdr (assq :results params)) "")))                                                                                        
        (body (org-babel-expand-body:org                                                                                                                           
               (replace-regexp-in-string "^," "" body) params)))  
...
```


Dresolve this issue: `(replace-regexp-in-string "^#\+" ",#+" body)` coming in, and `(replace-regexp-in-string "^,#\+" "#+" body)` going out. 

This change would be sufficient, but it would also escape all directives over time.

Still researching ...

S
