### ISSUE TITLE
Add possibility to map project keys to custom names

### ISSUE THREAD

**Issue by Fuco1** [ahungry/org-jira#164]
Instead of a file with an autoname based on project key (like EX.org or AHU.org) we want to have a user customizable prefix or some type of override map, so you may define:

    (("EX" . "your-file-name") ("AHU" . "your-other-name"))

See also #79

**Comment by ahungry** [comment]
Superseded by the feature i'm working on for this I think.

See feature/Custom-JQLs

**Comment by Fuco1** [comment]
What if I don't want to write custom JQLs?  This sets up a default translation option.  I think it's still useful for "not a poweruser", which I'm definitely not when it comes to Jira.

**Comment by ahungry** [comment]
Sure, thats a good point, we should definitely incorporate both
