### ISSUE TITLE
Do not require the "%s-Tickets" to be the first line in the file

### ISSUE THREAD

**Issue by Fuco1** [ahungry/org-jira#167]
the code in the rendering function 

```elisp
          (goto-char (point-min))
          (unless (looking-at (format "^* %s-Tickets" proj-key))
            (insert (format "* %s-Tickets\n" proj-key))
```

breaks features like custom org headers, for example

```org
#+FILETAGS: WORK
```

Can we relax this a bit and instead search for the first headline being that?

Ideally later we could specify target headlines but this would already be pretty sweet.  I would also like to put clock reports on the top of the file and they get broken because of this.

Also the check should be relaxed and allow for a TODO state keyword.  For example I  need the task to be marked TODO in order for my project queries to work.

We can use `org-element-at-point`

```
(headline
 (:raw-value "SC-Tickets" :begin 30 :end 24718 :pre-blank 0 :contents-begin 48 :contents-end 24718 :level 1 :priority nil :tags nil :todo-keyword
  #("TODO" 0 4
    (fontified t org-category "saleschamp" face
               (:foreground "IndianRed1" :weight bold)
               :org-clock-minutes 19))
  :todo-type todo :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 30 :TOGGL-PROJECT "Budget Energie" :title "SC-Tickets"))
```

and then look at the `:title` property.

I can do the patch if you are interested.  I will do this anyway for my fork though... so I might just as well submit it.

**Comment by ahungry** [comment]
Sure this is good - was the commit from ~9 days ago not handling properly?  I don't think it was in your fork yet
