### ISSUE TITLE
defcustom org-jira-custom-jqls + org-jira-update-worklogs-from-org-clocks

### ISSUE THREAD

**Issue by robs-nice99** [ahungry/org-jira#175]
Hy,
Thanks for this great package!

I'm using a custom jql defined with `defcustom org-jira-custom-jqls` and then trying to run `org-jira-update-worklogs-from-org-clocks` on those issues. (I still didn't understand if this command is supposed to sync all issues or just the current one)

But it fails with 
`
org-jira-update-worklogs-from-org-clocks: Issue <project>-<ticket-number> not found!
`
It creates a new empty file called <project.org>
My custom code:

```
(defcustom org-jira-custom-jqls
  '(
    (:jql "..."
          :limit 20
          :filename "all")
    (:jql "..."
          :limit 10
          :filename "general")
    )

```

Thanks in advanced

**Comment by ahungry** [comment]
This is a bug/missing feature.  I added the custom-jql and forgot this logic, I will work on it soon.

**Comment by ahungry** [comment]
Fixed in 4.3.1

**Comment by robs-nice99** [comment]
Fabulous! Thanks!

**Comment by ahungry** [comment]
:)
