### ISSUE TITLE
Feature Request: Please convert Jira Macros into Emacs macros and vice-versa, where possible

### ISSUE THREAD

**Issue by nickgarber** [ahungry/org-jira#177]
There's no need to support translation between all of them, but there are a few that might make sense:

   from {noformat} to begin_example...end_example, for example :)

    
I'm sure there are others that would make sense that dont immediately come to mind at the moment.

This would be a very nice usability boost and would mitigate the risk factor in issue #161 .

**Comment by ahungry** [comment]
This would be great - someone please make a PR :)
