### ISSUE TITLE
Clarify authorization workaround

### ISSUE THREAD

**Issue by greened** [ahungry/org-jira#178]
I'm trying to use the authorization workaround described in the README but it's not clear what part of the curl request is the token.  I see things like DWRSESSIONID, JIRASESSIONID, seraph.rememberme.cookie, atlassian.xsrf.token, __cfduid, AJS.conglomerate.cookie, crowd.token_key and other things I don't understand.

Could we update the README to try to guide users on what to set jiralib-token to?

**Comment by greened** [comment]
Also, when I try this:
`(defconst jiralib-token
  (cons "Cookie" . "<my cookie>"))`

I get:
`Wrong type argument: listp, "<my cookie>"`

**Comment by ahungry** [comment]
Thanks @kennyheaton  this should be resolved and more clear in doc now
