### ISSUE TITLE
Set Org-Mode Task's Priority from Jira Priority

### ISSUE THREAD

**Issue by khaije1** [ahungry/org-jira#18]
Hi! In my org-mode I use priority cookies ```[#A]``` through ```[#E]```. 

In Jira it's a mess of a variety of priority labels, but I'd still like them to show up ranked by priority in my Org-Agenda.

If I could define a mapping between Jira priorities and Org-Mode priorities in a variable I could keep it up to date and still get the really nice priority-sorted presentation of Org-Agenda for my Jira tasks.

Thanks!

**Comment by ahungry** [comment]
Nice idea, I'll add to the package!

**Comment by benley** [comment]
I would appreciate this feature too, if it gets implemented at some point.
