### ISSUE TITLE
Only set reporter on update if user has permission to do so

### ISSUE THREAD

**Issue by makuto** [ahungry/org-jira#182]
I'm not speaking from authority, but I think that you might need an administrator account in order to update the reporter. I don't have those permissions at my work.

As a workaround I commented the lines with `org-issue-reporter` in `org-jira-update-issue-details`, which makes updating work for me.

Does anyone know for sure whether it is a permissions issue? If it is, is there some way we could check for the permission (possibly [permissions](https://docs.atlassian.com/software/jira/docs/api/REST/8.1.0/#api/2-getPermissions)) and only send the field if the user has that permission?

_Originally posted by @makuto in https://github.com/ahungry/org-jira/issues/181#issuecomment-489836502_

**Comment by ahungry** [comment]
You should be able to exclude reporter from the updated fields in the latest defcustom `jiralib-update-issue-fields-exclude-list`
