### ISSUE TITLE
HTTP 401 Error while connecting in execution of org-jira-get-issues

### ISSUE THREAD

**Issue by notamargetic** [ahungry/org-jira#186]
Thanks in advance! Sorry if this post is similar to others but I can't figure out what's 
different/wrong with my config.

Running
* emacs 26.1
* mac osx 10.13.4
* spacemacs develop

First I `package-install` `org-jira` then I run `jiralib-login` which seems to work fine. I also have an .authinfo config file set up correctly.

However, when I run org-jira-get-issues I get an html response from the server and at the end, I see this:

REQUEST [debug] REQUEST-RESPONSE--CANCEL-TIMER
REQUEST [debug] -CLEAN-HEADER
REQUEST [debug] -CUT-HEADER
REQUEST [debug] error-thrown = (error http 401)
REQUEST [debug] -PARSE-DATA
REQUEST [debug] parser = jiralib--json-read
REQUEST [debug] data = nil
REQUEST [debug] symbol-status = error
REQUEST [debug] Executing error callback.
REQUEST [error] Error (error) while connecting to https://mysite.atlassian.net:443/rest/api/2/search.
REQUEST [debug] Executing complete callback.
Received data for org-jira-get-issue-list-callback.
Fetching issues...

**Comment by djgoku** [comment]
@notamargetic how did you get that debug output from `org-jira-get-issues` I want to try to see if I get the same output. Also I don't get any output when I run `jiralib-login`.

**Comment by notamargetic** [comment]
@djgoku, I just ran this 

`(setq request-log-level 'debug)`
`(setq request-message-level 'debug)`

**Comment by djgoku** [comment]
Weird. All I get from `org-jira-get-issues` is `Fetching issues...` nothing happens ever is returned.

**Comment by vlladdrakk** [comment]
This is weird, I just started getting this same issue yesterday. I am also on macOS, with emacs 26.1 running in the terminal. It was working fine for me before. I tried reinstalling the package, but no luck.

**Comment by vlladdrakk** [comment]
I just switched my password out for the API token and it works again!!! Thanks, @kennyheaton

**Comment by ahungry** [comment]
Thanks  @kennyheaton  !
