### ISSUE TITLE
`org-jira-refresh-issue` from Org-Agenda, (for issue under point, etc)

### ISSUE THREAD

**Issue by khaije1** [ahungry/org-jira#19]
Would it be possible to add the ability to refresh an org-jira task from the org-agenda?

By default this would be the issue under point, within region, or if there are none of the proceeding (and with a confirmation prompt), all of the displayed issues.

Use Case:

I find myself using ` M   Like m, but only TODO entries` from the Org-Agenda view in order to filter tasks by Org-Jira properties. From time to time these tasks will get out of date and it'd be lovely to be able to perform an `org-jira-refresh-issue` from within this buffer (perhaps it would also trigger a refresh) and without needing to visit each Org-Jira task in each Org-Jira project file.

**Comment by ahungry** [comment]
Sure, this would be a nice PR addition.
