### ISSUE TITLE
TODO.org/todo.org messes up checkout on MacOS (and Windows)

### ISSUE THREAD

**Issue by greened** [ahungry/org-jira#191]
Since MacOS has a case-insensitive filesystem, having both a TODO.org and todo.org file in the repository causes problems.  See for example https://stackoverflow.com/questions/2016404/git-status-shows-modifications-git-checkout-file-doesnt-remove-them/2016426#2016426.  Can we unify these files?

This probably also affects Windows since it has a case-insensitive filesystem as well.

**Comment by ahungry** [comment]
Good call, got rid of the extra one.
