### ISSUE TITLE
Add hooks when issues retrieval is completed

### ISSUE THREAD

**Issue by razcampagne** [ahungry/org-jira#197]
Hi,

I would like to run some code of mine when the whole org-jira-get-issues process is completed, to sort the issues and save the buffer, for example.
The problem is the process is heavily asynchronous and I have no way to detect when all issues and all related comments have been all rendered in the org file.
It would be great to have some bookkeeping for all requests and responses to have a way to know when the process is finished to run a hook for user defined code.

**Comment by arichiardi** [comment]
This can probably be helpful for triggering a `switch-to-buffer` call. I have briefly looked into it without too much success. Will keep digging.

**Comment by razcampagne** [comment]
great, thanks.

**Comment by ahungry** [comment]
If anyone makes something tangible, please feel free to open a PR to add the feature.
