### ISSUE TITLE
org-jira-get-issues-headonly not retrieving info

### ISSUE THREAD

**Issue by JuanPabloMF** [ahungry/org-jira#20]
Some functions are working for me, such as org-jira-get-issue (by ID) and org-jira-get-projects, but whenever I try to use a function that has to retrieve many issues at once, for example org-jira-get-issues-from-filter or org-jira-get-issues-headonly, nothing happens. 

The error I am getting sometimes in the minibuffer is:

`REQUEST [error] Error (error) while connecting to http://mycompanysname.atlassian.net/rest/api/2/search`

Also I tried accesing the same API's functionality directly in the browser and it worked. Any idea on why this is happening?

**Comment by ahungry** [comment]
The calls you mentioned that work were modernized to work with the REST API and the async based callback setup, but the other 2 calls were not tested/updated, I'll look into trying them out and seeing what I need to fix to get them going.

**Comment by ahungry** [comment]
It looks like org-jira-get-issues-headonly is ok? (I get a buffer opened with all the headers), although the filter one doesn't seem to do anything after the filter prompt.

For pulling in all issues, org-jira-get-issues seems fine though.

**Comment by ahungry** [comment]
So, it looks like jiralib-get-issues-from-filter attempts to call a jiralib endpoint labelled getIssuesFromFilter, but this endpoint has never been available.  I'm going to unbind the function and add an unimplemented notice.  You should stick to `org-jira-get-issues` and `org-jira-get-issue` instead.

**Comment by ahungry** [comment]
Removed the unimplemented functions in https://github.com/ahungry/org-jira/commit/f441421a5182e356f55bda317a7b3e2d981fdd68
