### ISSUE TITLE
Update Labels Property?

### ISSUE THREAD

**Issue by chrislockard** [ahungry/org-jira#200]
Thank you for your great work! This package may solve my biggest workflow gap, and I'm very appreciative that you've worked on it.

I may be missing something, but it does not appear possible to change labels using org-jira and have them update in JIRA.

For instance, if I edit an existing issue's :labels: property in my org-jira buffer and run 'org-jira-update-issue', I see a status message about the issue updating in JIRA (at https://jira.example.com/projects/PROJECT/summary), but the labels aren't acutally updated. When the org-jira buffer refreshes, the original issue labels are present and my updates are lost.

For example, this is what an issue with labels (created in jira web application) looks like in org-jira (retrieved with `org-jira-get-issues`):
```org
** TODO Self-evaluation                           :ISSUE_4123:
   :PROPERTIES:
   :assignee: <me>
   :filename: ISSUE
   :reporter: <me>
   :type:     Task
   :priority: (1) High
   :status:   In Progress
   :created:  2019-10-01T11:17:33.295-0400
   :updated:  2019-10-01T11:19:44.649-0400
   :ID:       ISSUE-4123
   :CUSTOM_ID: ISSUE-4123
   :labels:   2019, sprint11
   :END:
:LOGBOOK:
:END:
*** description: <description>
```

If I modify the lables property to `:labels: 2019, sprint12, newlabel` and perform `org-jira-update-issue`, the buffer refreshes and the `:labels:` property remains unchanged.

Am I doing something wrong, such as editing labels incorrectly or is what I'm trying to do not currently possible?

**Comment by vlladdrakk** [comment]
I am no expert (by any means), but I took a look at the code and the org-jira-update-issue function does not update the labels. In fact, it doesn't look like there is anything to update the labels (though I could very well be wrong).  I took a look at the JIRA API docs to see if it would be hard to implement. It looks like to update labels you need to use an update field and specify the action on a per label basis. It is a bit beyond my ability at the moment. I could see adding functions to explicitly add/remove labels being a bit easier though.

Here is a link to the documentation I was looking at: https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-rest-api-2-issue-issueIdOrKey-put

**Comment by ahungry** [comment]
Feel free to extend this to add additional features around labels - as mentioned in preceding comment, this isn't a thing at the moment.
