### ISSUE TITLE
Use TLS based authentication

### ISSUE THREAD

**Issue by floli** [ahungry/org-jira#202]
Hello,

our JIRA server uses TLS based authentication as a first step, i.e., I had to install a client certificate in order to reach the web service.

How can I make `org-jira` use a client certificate?

Thanks!

**Comment by Kinmarui** [comment]
Can you tell more how you installed client cert? I'm just trying to configure org-jira and I'm getting 
```
REQUEST [error] Error (error) while connecting to https://<domain>.atlassian.net/rest/api/2/search.
```

where above request works correctly in web browser

**Comment by floli** [comment]
I am having the same problem. The client certificate is installed only in the web browser (Firefox), `org-jira`does not use it and therefore cannot reach the JIRA installation.

**Comment by floli** [comment]
This might be an interesting feature with Emacs 27: https://github.com/emacs-mirror/emacs/blob/43caa9680b0d000014b4b9004389b7b193a51629/etc/NEWS.27#L271

**Comment by ahungry** [comment]
Please feel free to extend the package to support this, the Jiras I have available do not use this (what I assume is a client side TLS certificate?)

**Comment by Kinmarui** [comment]
Not sure if client certificate can be installed automatically in browser, I never installed one, and I am not aware that jira uses one. I even changed browser couple times (now using Brave)
I wanted to connect to Jira cloud. 

@ahungry Maybe It would be good idea to note Jira version you are using in readme ?
