### ISSUE TITLE
Optionally Preserve Mini-Buffer Comment to Kill-Ring On `C-g`

### ISSUE THREAD

**Issue by nickgarber** [ahungry/org-jira#203]
Hopefully this sounds easy?

I find myself using the `C-c c c` binding for `org-jira-add-comment` often, and will occasionally, accidentally hit `C-g` which blinks my beautifully crafted Jira comment prose out of existence.

I'd like there to be an option to copy this text to the kill-ring. Speaking only for myself I believe it'd be a big time savings to be able to quickly recover from these unfortunate mishaps :)

Thanks!

**Comment by ahungry** [comment]
Good idea, feel free to PR.
