### ISSUE TITLE
org-jira-refresh-issues-in-buffer doesn't work with per-file keywords

### ISSUE THREAD

**Issue by nightscape** [ahungry/org-jira#206]
I've just discovered the very useful `org-jira-refresh-issues-in-buffer` method and would like to use it.
My JIRA files start like this:
```org
#+TODO: OPEN(o) TODO(t) SELECTED-FOR-WORK(s) IN-PROGRESS(p) IN-REVIEW(r) | DONE(d)
* MYPROJECT-Tickets
...
```
When I call `org-jira-refresh-issues-in-buffer` it throws an error
```
Not on an issue region!
```
When I delete the first `#+TODO` line it works without problems.
I'm wondering if this is related to the comment here?
https://github.com/ahungry/org-jira/blob/master/org-jira.el#L1881-L1883

**Comment by gopar** [comment]
Seeing same behaviour :(

**Comment by ahungry** [comment]
It's probably going to top of buffer, trying to use an org call to drill down a headline level, and failing (since top line is not an org headline).

**Comment by ahungry** [comment]
Should be good now.
