### ISSUE TITLE
"peculiar error" and "parse error" for org-jira-get-boards and org-jira-get-issues-by-board

### ISSUE THREAD

**Issue by Osram-Gru** [ahungry/org-jira#209]
Hello,

I almost jumped from my chair out of joy when I saw your module. Finally jira in org mode \o/

I installed 20190930.1406 from melpa, but unfortunately there's not much working here:
When I run `org-jira-get-boards`, that's what happens:

```
[error] request--callback: peculiar error
[error] request-default-error-callback: https://server:8443/rest/agile/1.0/board?maxResults=50&startAt=0 parse-error
```
I pasted the URL into my browser to see what's happening: I got some nice looking json:

```
{
  "maxResults": 50,
  "startAt": 0,
  "total": 84,
  "isLast": false,
  "values": [
    {
      "id": 3439,
      "self": "https://server:8443/rest/agile/1.0/board/3439",
      "name": "ADB",
      "type": "scrum"
    },
    {
      "id": 3478,
      "self": "https://server:8443/rest/agile/1.0/board/3478",
      "name": "AS board",
      "type": "kanban"
    },
    {
      "id": 3298,
      "self": "https://server:8443/rest/agile/1.0/board/3298",
      "name": "Backlog",
      "type": "scrum"
    }
  ]
}
```
I'd love to use org-jira. Please tell me how I can help you - basic knowledge of elisp is there, but not much...

**Comment by jaza-syed** [comment]
Hi, a bit late but I had a similar problem - it was because my jira url in my config was wrong, I would double check yours.

**Comment by ahungry** [comment]
Thanks for the report and potential solution - please re-open or put in a new one if this is still giving trouble and you haven't given up on the mode yet :)
