### ISSUE TITLE
Error while connecting in execution of org-jira-get-issues

### ISSUE THREAD

**Issue by matejb** [ahungry/org-jira#21]
Hi,

I'm getting following error when using function `org-jira-get-issues`:
```
Contacting host: jira.custom-domain.io:443
REQUEST [error] Error (error) while connecting to https://jira.custom-domain.io/rest/api/2/search.
```

When I try loading URL that failed manually using browser I get REST response.
Could it be because of the custom domain jira is on for my organisation?

What I can I do to get more info about this error?

**Comment by mfehlhaber** [comment]
Extract more details form the underlying `request.el` by setting
```
(setq request-log-level 'debug)
(setq request-message-level 'debug)
```
before executing the command again and post the results here. Your custom domain should not be a problem. Specific settings within your local JIRA might.

**Comment by MatejB** [comment]
Here it is:
```
Created jira link.
REQUEST [debug] REQUEST
REQUEST [debug] Run: curl --silent --include --location --compressed --cookie /Users/username/.emacs.d/.cache/request/curl-cookie-jar --cookie-jar /Users/username/.emacs.d/.cache/request/curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --header nil: nil --header Content-Type: application/json https://jira.custom-domain.io/rest/api/2/project?expand=description%2Clead%2Curl%2CprojectKeys
REQUEST [debug] REQUEST--CURL-CALLBACK event = finished

REQUEST [debug] REQUEST--CURL-CALLBACK proc = #<process request curl>
REQUEST [debug] REQUEST--CURL-CALLBACK buffer = #<buffer  *request curl*>
REQUEST [debug] REQUEST--CURL-CALLBACK symbol-status = nil
REQUEST [debug] REQUEST--CALLBACK
REQUEST [debug] (buffer-string) =
HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Sun, 08 Jan 2017 12:25:59 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-AREQUESTID: 807x183146x1
X-ASEN: SEN-6689748
X-AUSERNAME: anonymous
Cache-Control: no-cache, no-store, no-transform
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: User-Agent

[]
REQUEST [debug] REQUEST-RESPONSE--CANCEL-TIMER
REQUEST [debug] -CLEAN-HEADER
REQUEST [debug] -CUT-HEADER
REQUEST [debug] error-thrown = nil
REQUEST [debug] -PARSE-DATA
REQUEST [debug] parser = json-read
REQUEST [debug] data = []
REQUEST [debug] symbol-status = success
Decrypting /Users/username/.authinfo.gpg...done
Contacting host: jira.custom-domain.io:443
uncompressing publicsuffix.txt.gz...done
REQUEST [debug] REQUEST
REQUEST [debug] Run: curl --silent --include --location --compressed --cookie /Users/username/.emacs.d/.cache/request/curl-cookie-jar --cookie-jar /Users/username/.emacs.d/.cache/request/curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --data-binary @/var/folders/8r/yh70fdj15sl6vrjrxs60tn_w0000gn/T/emacs-request26101CDU --request POST --header Authorization: Basic bWJhY286dWxhekFyZ281NQ== --header Content-Type: application/json https://jira.custom-domain.io/rest/api/2/search
REQUEST [debug] REQUEST--CURL-CALLBACK event = finished

REQUEST [debug] REQUEST--CURL-CALLBACK proc = #<process request curl>
REQUEST [debug] REQUEST--CURL-CALLBACK buffer = #<buffer  *request curl*>
REQUEST [debug] REQUEST--CURL-CALLBACK symbol-status = nil
REQUEST [debug] REQUEST--CALLBACK
REQUEST [debug] (buffer-string) =
HTTP/1.1 400 Bad Request
Server: nginx/1.8.0
Date: Sun, 08 Jan 2017 12:26:25 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-AREQUESTID: 807x183155x1
X-ASEN: SEN-6689748
X-AUSERNAME: anonymous
Cache-Control: no-cache, no-store, no-transform
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: User-Agent

{"errorMessages":["Field 'assignee' does not exist or this field cannot be viewed by anonymous users.","Field 'resolution' does not exist or this field cannot be viewed by anonymous users.","Not able to sort using field 'priority'."],"errors":{}}
REQUEST [debug] REQUEST-RESPONSE--CANCEL-TIMER
REQUEST [debug] -CLEAN-HEADER
REQUEST [debug] -CUT-HEADER
REQUEST [debug] error-thrown = (error http 400)
REQUEST [debug] -PARSE-DATA
REQUEST [debug] parser = json-read
REQUEST [debug] data = ((errorMessages . [Field 'assignee' does not exist or this field cannot be viewed by anonymous users. Field 'resolution' does not exist or this field cannot be viewed by anonymous users. Not able to sort using field 'priority'.]) (errors))
REQUEST [debug] symbol-status = error
REQUEST [debug] Executing error callback.
REQUEST [error] Error (error) while connecting to https://jira.custom-domain.io/rest/api/2/search.
```

Thx for helping :-)

**Comment by mfehlhaber** [comment]
The `X-AUSERNAME: anonymous` is a bit surprising to me. Have you not been asked for your credentials before? Assuming `https://jira.custom-domain.io` really is the URL of your JIRA server, which I consider unlikely.

**Comment by MatejB** [comment]
Yes I have, username and password, I entered same login information as for jira web interface.
Should header `X-AUSERNAME` correspond to my jira username?
Yes, I replaced real name of domain with dummy one in output, so it's not indexed, just a practice of mine.

**Comment by mfehlhaber** [comment]
To my understanding... yes, it should correspond. At least it always does for me. I did have issues with login only after having changed my JIRA user name after its initial creation. I did not take the time to dig deeper, but changed it back to the original value. This got me back in the game.

**Comment by ahungry** [comment]
Try debugging by copy/pasting the curl lines directly in a shell or REST client and trying manually.  As @mfehlhaber has mentioned, changing credential information (initial sign in name etc.) can affect the auth token setup here.

Note: Please do not post the full log output without removing the auth header (I removed for you) as it looks encrypted but is not.

**Comment by MatejB** [comment]
Tried, not working :-(
Data file for POST request gets deleted, I suppose, at the end of emacs function execution. 
How do I make file stick around?

Request:
```
curl --include --location --compressed --cookie /Users/username/.emacs.d/.cache/request/curl-cookie-jar --cookie-jar /Users/username/.emacs.d/.cache/request/curl-cookie-jar --write-out "\n(:num-redirects %{num_redirects} :url-effective \"%{url_effective}\")" --data-binary @/var/folders/8r/yh70fdj15sl6vrjrxs60tn_w0000gn/T/emacs-request3987AaM --request POST --header "Authorization: Basic HASH" --header "Content-Type: application/json" https://jira.domain.io/rest/api/2/search
```
Response:
```
Warning: Couldn't read data from file
Warning: "/var/folders/8r/yh70fdj15sl6vrjrxs60tn_w0000gn/T/emacs-request3987AaM
Warning: ", this makes an empty POST.
HTTP/1.1 400 Bad Request
Server: nginx/1.8.0
Date: Tue, 10 Jan 2017 11:58:17 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-AREQUESTID: 779x187768x1
X-ASEN: SEN-6689748
X-AUSERNAME: anonymous
Cache-Control: no-cache, no-store, no-transform
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: User-Agent

{"errorMessages":["No content to map to Object due to end of input"]}
(:num-redirects 0 :url-effective "https://jira.domain.io/rest/api/2/search")
```

**Comment by mfehlhaber** [comment]
Yes, the temporary file used in `--data-binary` gets removed right away. Try to provide someting along the lines of
```
--data '{"jql": "project = PROJECT", "startAt": 0, "maxResults": 15, "fields": ["summary", "status", "assignee"]}'
```
instead.

**Comment by MatejB** [comment]
Tried, I got error "A value with ID '10200' does not exist for the field 'project'." when I try with number ID for project. 
I think that basic auth is disabled in my organisation jira installation, request with basic auth just get ignored.
Thx for helping.

**Comment by mfehlhaber** [comment]
Not quite sure what you did here. I should have been more explicit in pointing out that you need to replace "PROJECT" with whatever project you have set up in your JIRA. The idea behind running this curl command is to check the validity of the cookie that was created during login and to make sure JIRA is installed and configured so that it supports REST API calls.

**Comment by marc0s** [comment]
Hi.

I'm having this issue as well, and having check the debug output from `request`, I see that the `Authorization: Basic` header has the wrong content.  And I don't know where the wrong username/password pair is coming from.  I have emptied my `.authinfo` file and I got the same wrong contents. Where should I look for this wrong contents coming from? Some other file `request` might be picking them up from?

I checked a handmade curl request and it works fine, so I discard any server-side issue.

Thanks

**Comment by ahungry** [comment]
Look at the jiralib.el file, function `jiralib-login` - it handles the building of this string.

There is a check currently, if you're less than emacs-major-version 24, it will prompt for username/password, otherwise it reads your .authinfo or .authinfo.gpg file, and will search it for a match on your jiralib-host (or attempt to parse it from your jiralib-url).

It then goes on to encode those parsed values as your base64'ed header.

Try adding some debug lines (message "something") in that function and recompile it, see if it is building the right Authorization header at that point (line 214 in jiralib.el) and request.el is incorrectly passing it, or if it is making the wrong one at that point.

Looking at the function, I think it could use some work to better handle cases where the credentials are not found (it looks like it would just encode a blank user/pass if so), without properly falling back to the username/password prompt that occurs on older Emacs versions (I'll have to ensure this fallback happens).

**Comment by marc0s** [comment]
Ok, I found the origin of the problem.

I had a (outdated) `~/.netrc` file with a `default` entry and `auth-sources-search` was picking it up instead of `~/.authinfo` (still don't know why, will check permissions or whatever). Definitely not an `org-jira` issue.

Once deleted the `~/.netrc` file I got asked by my username and password while doing `M-X org-jira-get-projects` and results showed up.

Thanks for the fast answer anyway!

**Comment by lonefreak** [comment]
I had the same problem. After debugging a bit I found that curl (I'm using 7.43.0 (x86_64-apple-darwin15.0)) need an extra flag to be able to carry the data to the second call when facing a redirect. The useful flags are `--post301` and `--post302`. Is it possible to set those flags in org-jira?

**Comment by ahungry** [comment]
i'll look into allowing adding/customizing the flags on the curl call in request.el.

**Comment by photex** [comment]
I'm getting the following error when trying to use this module:

```
REQUEST [debug] REQUEST
REQUEST [debug] Run: curl --silent --include --location --compressed --cookie c:\Users\chip.collier\.emacs.d\request\curl-cookie-jar --cookie-jar c:\Users\chip.collier\.emacs.d\request\curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective %{url_effective}) --header Authorization: Basic Y2hpcC5jb2xsaWVyOkkgbDB2ZSB0byBpbm5vZ2FtZXMh --header Content-Type: application/json https://jirahost/rest/api/2/project
REQUEST [debug] REQUEST--CURL-CALLBACK event = exited abnormally with code 60

REQUEST [debug] REQUEST--CURL-CALLBACK proc = #<process request curl>
REQUEST [debug] REQUEST--CURL-CALLBACK buffer = #<buffer  *request curl*>
REQUEST [debug] REQUEST--CURL-CALLBACK symbol-status = nil
REQUEST [debug] REQUEST--CALLBACK
REQUEST [debug] (buffer-string) =

(:num-redirects 0 :url-effective https://jirahost/rest/api/2/project)
REQUEST [debug] REQUEST-RESPONSE--CANCEL-TIMER
REQUEST [debug] -CLEAN-HEADER
REQUEST [debug] -CUT-HEADER
REQUEST [debug] error-thrown = (error . "exited abnormally with code 60
")
REQUEST [debug] -PARSE-DATA
REQUEST [debug] parser = json-read
REQUEST [debug] data = nil
REQUEST [debug] symbol-status = error
REQUEST [debug] Executing error callback.
REQUEST [error] Error (error) while connecting to https://jirahost/rest/api/2/project.
```

I'm able to browse for issues with Intellij and use the rest api via the browser; but I'm not able to actually modify issues outside of the web pages though so perhaps this is related.

**Comment by wires** [comment]
I ran into a similar issues and for me it turned out that I used Atlassian cloud with a google account which doesn't set a password for the user. To fix this, you need to reset your users password.

Jira's site is a nightmare, navigate as follows:

> go to dashboard (`yoursite.atlassian.net`) => click the hamburger bottom left => site administration => users => click on the user full name => click reset password in the top

    curl -u username:password -X GET -H "Content-Type: application/json" https://yoursite.atlassian.net/rest/api/2/project

**Comment by wires** [comment]
update: this actually only fixes `org-jira-get-projects`, but `-get-issues` doesn't work as expected. I see in `*Messages*` that the result from the Jira API is empty.

```json
{"startAt":0,"maxResults":100,"total":0,"issues":[]}
```

I don't know how to capture the temporary output file to see what data is sent to Jira. 

ps. Wouldn't it be better if some sort native emacs http call could be used instead of command-line `curl`?

**Comment by ahungry** [comment]
Just use the fix here: https://github.com/ahungry/org-jira#authorization-workaround-not-secure - it may be the best option atm.
