### ISSUE TITLE
How to deal with custom field?

### ISSUE THREAD

**Issue by ovc** [ahungry/org-jira#210]
Hello, I can't use `org-jira-todo-to-jira` or `org-jira-create-issue` and I think because of custom field:
```
{"errorMessages":[],"errors":{"customfield_10002":"Story Points                        ."}}
[error] request--callback: peculiar error: 400
[debug] request--callback: executing error
[error] request-default-error-callback: https://jira.mylocaldomain.local/rest/api/2/issue error
jiralib--rest-call-it: Wrong type argument: stringp, nil
```
I think that I need somehow create custom `JQL`?
Is any examples with custom field or any advice? Thank you!

**Comment by ahungry** [comment]
The readme should have some samples of custom-jql usage.  There is another open issue related to better support of custom fields, so maybe that'll go somewhere some day.
