### ISSUE TITLE
Keybinding for org-jira comments shadows common org-mode keybindings

### ISSUE THREAD

**Issue by bhipple** [ahungry/org-jira#211]
The `C-c c` prefix is generally setup by most users for `org-capture`:
https://orgmode.org/manual/Using-capture.html#Using-capture

While technically not done by `org-mode` itself, most "getting started with emacs" guides I've seen recommend putting it on `C-c c`, since `org-mode` itself does bind `C-c C-c` to org capture completion once the template is started.

For users who have done that, these two bindings conflict:
```
    (define-key org-jira-map (kbd "C-c cc") 'org-jira-add-comment)
    (define-key org-jira-map (kbd "C-c cu") 'org-jira-update-comment)
```
https://github.com/ahungry/org-jira/blob/master/org-jira.el#L535-L536

It's possible we may want to change them?

**Comment by ahungry** [comment]
While you're definitely right, I don't think it'd be a good idea to change or remove bindings that have been in this mode for around 10 years at this point.
