### ISSUE TITLE
Getting started steps are buggy

### ISSUE THREAD

**Issue by zenspider** [ahungry/org-jira#215]
I've had a lot of trouble getting started.

1. it would be nice if everything in the readme was in a file that ships with the library.
2. I created my auth info following the readme.
3. `M-x org-jira-get-issues RET` wound up erroring in a number of ways. First, it started with telling me to issue `M-x make-directory RET RET` to fix a rootless file. But the rootless file never showed up, so I had nowhere to do that.
4. If I make the directory and open one of the org files (possibly a mistake?), none of the keybindings are available. I assume it's because org-jira-mode is never fired off.
5. I just filed #214 for a related but separate issue.

**Comment by ahungry** [comment]
Thanks for the update @zainab-ali  - going to close this
