### ISSUE TITLE
Problem - Current cloud jira complains Basic auth is deprecated resulting in 401 calls that fail to auth

### ISSUE THREAD

**Issue by ahungry** [ahungry/org-jira#217]
Problem - Current cloud jira complains Basic auth is deprecated resulting in 401 calls that fail to auth

**Comment by dineshbhardwaj** [comment]
when is this going to be fixed?

**Comment by ahungry** [comment]
The auth workaround is pretty easy to setup (copy the session cookie from a jira web session) and has the benefit that the remote jira instance doesn't actually need to be setup to "allow" REST access, so doing anything with basic auth is pretty low priority.

Maybe we should clean it up/remove from repo.

**Comment by Trisk3lion** [comment]
What worked for me on a corporate cloud jira instance, was to set:
` (setq jiralib-token '("Authorization" . "Bearer <PERSONAL-TOKEN>")`

**Comment by mujo-hash** [comment]
For Basic Authentication on cloud Jira, an api token must be used now in place of a password:
https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/
https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/

The self-hosted version of Jira appears to still support Basic Authentication with a user password:
https://developer.atlassian.com/server/jira/platform/basic-authentication/

I think if the README just included this information, that would be enough to resolve this issue.

**Comment by ahungry** [comment]
Updated
