### ISSUE TITLE
Fails with helm-comp-read

### ISSUE THREAD

**Issue by jagguli** [ahungry/org-jira#218]
When using helm, org-jira fails on create issue

helm-M-x-execute-command: In ‘org-jira-create-issue History’ source: ‘#[0 \304\302\300\305\303$\211\205^Q^@\306\307\310\301^D""\207 [nil nil initial-input t helm-comp-read-get-candidates nil delete  helm-cr-default] 6]’
 (wrong-type-argument listp initial-input)

**Comment by ahungry** [comment]
Hmm, I also use helm, I don't recall having seen this, but it looks like the initial candidates list is not a list type and is perhaps something else

**Comment by jagguli** [comment]
Which version of helm are you using I'm using 3.6.2, which version are you using ?

**Comment by jagguli** [comment]
Anyways I got it working by removing initial-input as arg to completing-read
My lisp foo is not good enought to fix this issue

**Comment by ahungry** [comment]
I think this bug was caused by quoting the initial-input variable done in this PR:

https://github.com/ahungry/org-jira/pull/199/files

I seem to be having a similar issue with creating an issue, and undoing this commit fixes it.

**Comment by ahungry** [comment]
issue is fixed
