### ISSUE TITLE
org-jira-update-issue does not work

### ISSUE THREAD

**Issue by jagguli** [ahungry/org-jira#219]
Tried updating description and assignee

these fields do not seem to be working

Emacs 26.3

**Comment by jagguli** [comment]
A small token of appreciation if someone can fix this, 
https://www.bountysource.com/issues/91878932-org-jira-update-issue-does-not-work

**Comment by eliraz-refael** [comment]
This issue bugged me as well, I can try to go about solving it, however, it seems like there are PRs from last year that left unseen (I guess), I hope the maintained is here to review any upcoming PRs

**Comment by ahungry** [comment]
I'm around, but need more info to look into this - what Jira server version, what setup work was done so far, has the update ever worked for you etc.

**Comment by jagguli** [comment]
I'm using it against jira cloud.
And I've never used this package before, so it's never worked for me.

**Comment by ngm** [comment]
Might be unrelated, but I found that when an issue has no priority, `org-jira-update-issue` fails with 

> {"errorMessages":[],"errors":{"priority":"Priority name '' is not valid"}}
[error] request--callback: peculiar error: 400

and my changes to the description were lost.  After giving it a priority, my changes to the description are saved.

**Comment by ahungry** [comment]
assignee issue fixed in 0e9bb6d0bc9241bdee72a1c6c78472f4cf30965b - I'm not sure when an empty priority would exist - I have added more verbose error logging on failed http calls.

If we see a priority failure that's reproducible, maybe can look into a fix.
