### ISSUE TITLE
add jira issue's sprint or component properties to tag lists

### ISSUE THREAD

**Issue by micanzhang** [ahungry/org-jira#22]

**Comment by travispavek** [comment]
This would really be awesome!  I would love to have component, fixversion, and sprint tags.

**Comment by ahungry** [comment]
I'll look into adding, should be easy enough if they are top level tags and not heavily customized Jira things - if someone wants to make a PR it's welcome as well.

**Comment by ahungry** [comment]
Sprint is stored in a custom field, so this is a pain to query out of the existing endpoints.

**Comment by nevetS** [comment]
@ahungry This is something that I want (I need sprint + Epic).  I'd like to throw some effort into a PR, but before I get started I wanted to ask:

1) are you open to this?
2) Do you have any direction based on the research that you've done as to how it might work?

**Comment by ahungry** [comment]
1. Yes, that'd be a great update!
2. I think you will have to look into jiralib.el and follow the link to the appropriate rest document, and read up on querying for custom fields (last I remember, we don't do a lot with custom fields atm).

**Comment by ahungry** [comment]
Btw, @nickgarber just commented about some custom fields were here: https://github.com/ahungry/org-jira/issues/87 - maybe you guys would want to coordinate on extending custom fields functionality?
