### ISSUE TITLE
Cannot org-jira-get-summary and org-jira-get-issues fail request-default-error-callback

### ISSUE THREAD

**Issue by ReggieMarr** [ahungry/org-jira#223]
I'm unable to retrieve summary or issues however I am able to retrieve boards and projects. It appears this is due to some kind of failed search. Is it possible that I need to make a custom jql request ?
I have debug flags turned on now and find the following.
After calling: org-jira-get-issues
I was called, was it with a callback? yes
[debug] request--curl: curl --silent --location --cookie /home/[USER]/.emacs.d/.local/cache/request/curl-cookie-jar --cookie-jar /home/[USER]/.emacs.d/.local/cache/request/curl-cookie-jar --include --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --compressed --data-binary @/tmp/emacs-requestKANFbX --request POST --header Authorization: Basic <omitted>== --header Content-Type: application/json http://[HOSTNAME]/jira/rest/api/2/search
Fetching issues...
[debug] request--curl-callback: event finished

[debug] request--callback: UNPARSED
HTTP/1.1 400 
Date: Fri, 31 Jul 2020 15:47:26 GMT
Server: [SERVERINFO]
X-AREQUESTID: [REQUESTID]
X-ASESSIONID: 1ugckb0
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
X-ASEN: SEN-4275085
X-Seraph-LoginReason: OK
X-AUSERNAME: [USERNAME]
Cache-Control: no-cache, no-store, no-transform
Content-Encoding: gzip
Vary: User-Agent
Content-Type: application/json;charset=UTF-8
Connection: close
Transfer-Encoding: chunked

{"errorMessages":["No content to map to Object due to end of input"]}
[error] request--callback: peculiar error: 400
[debug] request--callback: executing error
[error] request-default-error-callback: http://[HOSTNAME]/jira/rest/api/2/search error
[debug] request--callback: executing complete
Received data for org-jira-get-issue-list-callback.
Fetching issues...

After calling org-get-summary I get the following:

[debug] request--curl: curl --silent --location --cookie /home/[USER]/.emacs.d/.local/cache/request/curl-cookie-jar --cookie-jar /home/[USER]/.emacs.d/.local/cache/request/curl-cookie-jar --include --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --compressed --data-binary @/tmp/emacs-requestRA6lxQ --request POST --header Authorization: Basic <omitted>== --header Content-Type: application/json http://[HOSTNAME]/jira/rest/api/2/search
[debug] request--curl-callback: event finished

[debug] request--callback: UNPARSED
HTTP/1.1 400 
Date: Fri, 31 Jul 2020 15:51:55 GMT
Server: [SERVERINFO]
X-AREQUESTID: [REQUESTID]
X-ASESSIONID: 1ugckb0
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
X-ASEN: SEN-4275085
X-Seraph-LoginReason: OK
X-AUSERNAME: [USERNAME]
Cache-Control: no-cache, no-store, no-transform
Content-Encoding: gzip
Vary: User-Agent
Content-Type: application/json;charset=UTF-8
Connection: close
Transfer-Encoding: chunked

{"errorMessages":["No content to map to Object due to end of input"]}
[error] request--callback: peculiar error: 400
[debug] request--callback: executing error
[error] request-default-error-callback: http://[HOSTNAME]/jira/rest/api/2/search error

**Comment by ahungry** [comment]
I had to edit your comment, you had 2 references to a basic auth (which is just base64 encoded user:password) in your paste.

If this is still giving you trouble, could you please refile with the exact steps taken to get to the failure?
