### ISSUE TITLE
How to programmatically get issues on startup

### ISSUE THREAD

**Issue by bznein** [ahungry/org-jira#225]
Hello, and thanks for this wonderful mode!

I am trying to set it up so that, when starting Emacs, `org-jira-get-issues` is called, but with no luck.

Simply adding to my config 

`(org-jira-get-issues)` leads to this error:

` Wrong number of arguments: (1 . 1), 0` but I can't figure out which arguments should be passed.
What I want to obtain is the same result of calling `M-x org-jira-get-issues` right after starting up

**Comment by parhamdoustdar** [comment]
Try this: `(call-interactively #'org-jira-get-issues)`

**Comment by bznein** [comment]
Yes that works! :)
