### ISSUE TITLE
Pull Custom JIRA Fields Into Issue Properties

### ISSUE THREAD

**Issue by parhamdoustdar** [ahungry/org-jira#226]
Hi,

First of all, thanks a lot for making this package. I'm completely blind and use a screen reader, and JIRA is almost completely unusable.

I moved to a part of our company that relies heavily on JIRA, and you saved my life. thank you.

I have an issue, though. Right now, the list of fields to pull out of an issue are hard-coded. This means that if I need to look at a field that is custom, I need to browse around in JIRA's horrible UI 😭

What I'm hoping to do is to pull those fields into the properties of the issue, so that I can query them in org, or read them.

Thanks a lot!

**Comment by jmpatricio** [comment]
Hi. 

I have the same issue here.

Just wondering if we can make this configurable somehow. 
Think the code that does that is placed here: https://github.com/ahungry/org-jira/blob/master/org-jira-sdk.el#L93

I will try to make a PR on this

**Comment by ahungry** [comment]
This is a good idea, a bit of a bigger effort, as a lot of hardcoded field references may exist in various portions of the files.

**Comment by ahungry** [comment]
If anyone makes a PR, this would be quite welcome.
