### ISSUE TITLE
Allow Viewing Stories in an Epic

### ISSUE THREAD

**Issue by parhamdoustdar** [ahungry/org-jira#227]
Right now, the only way I've found of viewing all the stories in an epic is evaluating this sexp:

```
(org-jira-get-issues-headonly (jiralib-do-jql-search (format "\"Epic Link\" = %s" (org-jira-parse-issue-id))))
```

However, this doesn't give me any of the nice stuff that I get when I run `org-jira-get-issues`, like being able to view comments, the state of the issue, and so on.

**Comment by ahungry** [comment]
Did you look into the org-jira-custom-jqls usage?

**Comment by parhamdoustdar** [comment]
Hi,
Yes. I already use it and manually define per-file queries about things I'm
interested in.
However, what I'm looking for is to have the ability to look at the stories
under an epic when I'm viewing it.
For example, assume that the project `roadmap` is made up of epics. When I
open `roadmap.org`, I'd love to see the stories under each epic, instead of
manually defining a query for each and putting each one in a separate file.
Hope this makes sense.

**Comment by ahungry** [comment]
I would probably accept a PR with this, if anyone wants to make one, feel free.
