### ISSUE TITLE
Give org-mode priority cookie higher precedence than properties drawer priority

### ISSUE THREAD

**Issue by bhipple** [ahungry/org-jira#229]
As of https://github.com/ahungry/org-jira/pull/123, we put the priority cookie in the title, e.g. 

```
** TODO [#A]  Foobar               :ISSUE-123:
:PROPERTIES:
:priority: Highest
...
:END:
*** description: ...
```

If we use the standard org-mode tools to change the `[#A]` priority, this will be overwritten on the next Jira update, since the one in the properties drawer has higher precedence.

Since many org-mode users will tend to use the standard tools more often than the Jira tools, it'd be nice to have an option to make the `[#A]` higher priority than `:priority: Highest`.  E.g., if I change `[#A]` to `[#B]` the next update should change the ticket on Jira to `:priority: Medium` (or w/e the alist says).

**Comment by ahungry** [comment]
Good idea, I may add this soon

**Comment by ahungry** [comment]
I'm not going to have time to look at specific enhancement requests, but if someone else wants to PR it, feel free to make one.
