### ISSUE TITLE
Compare functionality to ejira

### ISSUE THREAD

**Issue by deepfire** [ahungry/org-jira#232]
How do features of `org-jira` compare to https://github.com/nyyManni/ejira ?

What is missing in `org-jira`?

What can be plausibly ported over?

I realise, that's a lot of questions for a single ticket! : -)

**Comment by ivaigult** [comment]
As was discovered in #3 , org-jira lacks markup re-formatting (from jira to org format and vice versa) when importing/exporting tickets descriptions and comments.

**Comment by ahungry** [comment]
I think it's a fun thought experiment, however coke and pepsi are both good choices, without needing to match each other identically.  In this way, I think org-jira and ejira may be similar.

Going to close this since it's not an actual bug or related to a feature PR.
