### ISSUE TITLE
Cannot get issues with custom jql

### ISSUE THREAD

**Issue by seokbeomKim** [ahungry/org-jira#233]
Hi,
I am trying to get 'sub-assigned' issues with using custom jql, but it does not work well.
It seems that fetching issues has been successful, but the file has not been created according to the buffer messages.
```
Received data for org-jira-get-issues-from-custom-jql-callback.
Fetching issues...
About to render 73 issues.

(nothing in the buffer list)
```

Following custom jql is correct and I've tested with it.
```
(setq org-jira-custom-jqls
	   '(
	     (:jql "Sub_Assignee = B190253 AND status not in (Resolved, closed) ORDER BY created DESC")
	     ))
```

**Comment by ahungry** [comment]
Try adding a `:filename "some-file.org"` and see if it works, it seems your definition may be missing the filename value and I don't think it drops to a default.
