### ISSUE TITLE
Not on an issue region

### ISSUE THREAD

**Issue by roganjoshua** [ahungry/org-jira#237]
I am trying to refresh all the issues in my buffer C-c iR and get Not on an issue region!

What denotes and issue region

**Comment by ahungry** [comment]
This seems to happen if the file has a blank line at the top.  I think some time ago a change was made to insert a blank line at the top of new files, I'll look into adjusting to accommodate for this.

**Comment by ahungry** [comment]
Should be fixed in e144ce9
