### ISSUE TITLE
Fetching issues fails with "peculiar error"

### ISSUE THREAD

**Issue by thermopyle** [ahungry/org-jira#238]
Fetching issues fails every time I try with the following output in `*Messages*`:
```
I was called, was it with a callback? yes
[error] request--callback: peculiar error: 401
[error] request-default-error-callback: https://****.atlassian.net/rest/api/2/search parse-error
Fetching issues...
```
Nothing happens after the "Fetching issues...".

I have configure email address and password in the `.authinfo` file:

`machine ****.atlassian.net login ****@****.com password **** port 443
`

I have obviously obfuscated some of the info above. The port 443 is there since the url starts with "https://".

Is there a way to get some more logging and error info to pin point the problem?

**Comment by AblatedSprocket** [comment]
I was seeing this issue if there were no issues specifically assigned to me. Otherwise it seems to work ok.

**Comment by ahungry** [comment]
I see the peculiar error indicates a 401, which would seem to be an unauthorized request, so maybe that has to do with the failure.

Some Jira intances do not allow basic auth, so the token suggestion is a good one (or the README talks about manually setting jiralib-token).

**Comment by ahungry** [comment]
For diagnosis, the underlying HTTP call is handled by request.el which offers these settings for the request-log-level variable:

          request-log-level is a variable defined in request.el.

          Value
          -1

          Set Customize

          Documentation
          Logging level for request.

          One of error/warn/info/verbose/debug/trace/blather.
          -1 means no logging.

**Comment by ahungry** [comment]
Going to close this one.
