### ISSUE TITLE
org-jira-get-issues has not result

### ISSUE THREAD

**Issue by doug2mac** [ahungry/org-jira#239]
Hello,

I am currently using doom emacs as my configuration, in WSL2 in Windows 10 (OS: Ubuntu 20.04.1 LTS on Windows 10 x86_64).

Emacs information:
```
GNU Emacs 27.1
Copyright (C) 2020 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

 I have created the directory for org-jira (make-directory "~/.org-jira"), as well as set the jiralib-url in my configuration.

When running org-jira-get-issues, I am prompted for my username, and password. After completing, the message "Fetching issues..." displays and after waiting 20 mins, nothing happens.

I check the directory "~/.org-jira" and there are no entries (my understanding is that there should be 1 org file per project)

I am missing something in the setup?

Thank you!

**Comment by RolT** [comment]
Hi, I had the exact same issue with `org-jira-get-issues`, with no real error message, but I found the actual error when using `org-jira-get-projects` (which turned out to be #238, solved by using an API token in my case). Hopes this help.

**Comment by ahungry** [comment]
Thanks for the assist, sounds like it may be auth based.

For now, I am going to close - the latest update adds some extra error output for http requests by default, which should make this type of bug reporting easier in the future.
