### ISSUE TITLE
Add Epic Link and Issue Link to org-jira task properties

### ISSUE THREAD

**Issue by khaije1** [ahungry/org-jira#24]
The Epic Link would help when filtering for and selecting tasks to work on.

The Issue Link is similar, but perhaps more special. 

I'm interested in the ability to get and set this info from org-jira, but also with the potential for integration with the org-depend system.
http://orgmode.org/worg/org-contrib/org-depend.html

The todo-dependencies ( http://orgmode.org/manual/TODO-dependencies.html) may also be relevant.

In the first and simple case, it'd still be useful to have these available in org-mode as conventional strings. 
The org-depend tie-in was only mentioned in case it spurred a brainstorm :)

**Comment by ahungry** [comment]
Good ideas
