### ISSUE TITLE
org-jira-update-worklogs-from-org-clocks calls resync on each update/insert event

### ISSUE THREAD

**Issue by sjg-ep** [ahungry/org-jira#241]
As per the comment in `org-jira-update-worklogs-from-org-clocks`

```
              ;; @TODO :optim: This is inefficient, calling the resync on each update/insert event,
              ;; ideally we would track and only insert/update changed entries, as well
              ;; only call a resync once (when the entire list is processed, which will
              ;; basically require a dry run to see how many items we should be updating.
```

I am motivated to fix this, as I have some tickets with thousands of worklogs, making this is painfully slow.

Could it be as simple as:

1. Track how many requests are made to update/add a worklog
2. When we have had this many callbacks, trigger a single resync

Sorry if I have overlooked something here.

**Comment by sjg-ep** [comment]
Hmm, it seems a fix here is really needed, as org-jira is hammering the Jira API so hard I'm getting HTTP 429 Too many requests.

**Comment by sjg-ep** [comment]
As a work-around for the HTTP 429 problem, I deleted all worklogs with an id attribute from the org issue, before running the update.

**Comment by ahungry** [comment]
You can add a PR for consideration, but I think thousands of work-logs on a single ticket is an outlier, as most tickets I've ever seen tend to be a day or less worth of effort (else they are broken into smaller tickets/sub-tasks etc.).
