### ISSUE TITLE
Updating an issue that is unassigned gives it an assignee

### ISSUE THREAD

**Issue by ngm** [ahungry/org-jira#242]
If I have an issue with no assignee, when I update the issue with `org-jira-update-issue` (to update e.g. the description), then the issue is given an assignee.  It appears to be the first person alphabetically in the list of possible assignees.

I would like it to stay unassigned.

**Comment by ahungry** [comment]
Should be fixed as a result of this update:
0e9bb6d0bc9241bdee72a1c6c78472f4cf30965b
