### ISSUE TITLE
Question/Advice: Jira vs other

### ISSUE THREAD

**Issue by LeeRuns** [ahungry/org-jira#245]
My experience in engineering always says- _**before you start the project, if there is someone who is an expert, ask them how long it will take._**  Which leads to my question.

I am faced with a somewhat of a decision and I would like your advice. I am married to org mode and azure devops right now. I could switch to jira one day, but I a single proprietor start-up who wants to be able to scale. Meaning I would like to avoid jira for now.

Devops has pretty clear method to do api with jira, so i could get a 3 way sync going i guess. 

My question is if i wanted to fork/modify this to point to something else, how long you think it will take me?

**Comment by opsroller** [comment]
Not Jira, I hate jira, and we're forced to use this sluggish crap.

**Comment by ahungry** [comment]
@LeeRuns if it'd just be pointing to a different domain, I wouldn't think long at all.

If it required a different domain + authentication mechanism, maybe a bit longer.

if all the endpoints/data formats were completely different, I think it'd take quite a long time.

Hope that helps.
