### ISSUE TITLE
Workaround for Jira time tracking race condition

### ISSUE THREAD

**Issue by jack-michaud** [ahungry/org-jira#247]
## Background
There's an open Jira time tracking bug that causes a discrepancy between the sum of all work logs and the time tracking time.

https://community.atlassian.com/t5/Jira-Software-questions/Time-Tracking-quot-Logged-quot-shows-wrong-value/qaq-p/647203
> I imported 66 worklogs via the REST-API which sum up to a total of 12h 15m but the time tracking only shows 55m of logged time.

I get this problem too when running `org-jira-update-worklogs-from-org-clocks`, and it's a pain in the butt because my org relies on Time Tracking and Time Remaining and I have to manually adjust the time remaining in the UI. 

## Root Cause
The issue happens because of a race condition in the Jira API. While all of the work logs are uploaded and recorded, only one of the entries is updated in time tracking.
![image](https://user-images.githubusercontent.com/13189762/112179642-19eae580-8bb8-11eb-8bfd-78c26dbde04b.png)

## Possible Solution
Making `org-jira-update-worklogs-from-org-clocks` **synchronously** update worklog entries will mitigate the issue. From my local testing, this seems to work.
![image](https://user-images.githubusercontent.com/13189762/112180050-6f26f700-8bb8-11eb-9167-705f3d095232.png)

There is a small speed drawback but in my opinion this is worth the pain of manually updating Time Tracking. 

I made a rough PR https://github.com/ahungry/org-jira/pull/246 with my synchronous changes and wanted to gather thoughts before finalizing the PR.

**Comment by ahungry** [comment]
Merged in https://github.com/ahungry/org-jira/pull/246, so I'll close this issue
