### ISSUE TITLE
org-jira-get-summary is not working

### ISSUE THREAD

**Issue by BaoshanPang** [ahungry/org-jira#249]
org-jira-get-summary is always getting nil, and I find the field 'summary' is under field 'fields' for the jira site used in my company, so changing the code like this would make it working:

(defun org-jira-get-summary ()
  "Get issue summary from point and place next to issue id from jira"
  (interactive)
  (let ((jira-id (thing-at-point 'symbol)))
    (forward-symbol 1)
    (insert (format " - %s"
                    (cdr (assoc 'summary (assoc 'fields (car (org-jira-get-issue-by-id jira-id)))))))))

**Comment by ahungry** [comment]
New error logging shows this as a result of command - I'll apply your update and re-try, next time feel free to make a PR:

          "JIRA_ERROR - see your *Messages* buffer for more details."

          "JIRA_ERROR REQUEST: "

          "/rest/api/2/search"

          (:type "POST" :data "{\"jql\":\"id = nil\",\"maxResults\":100}")

          "JIRA_ERROR RESPONSE: "

          ((errorMessages . ["The issue key 'nil' for field 'id' is invalid."]) (warningMessages . []))

          error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]

**Comment by ahungry** [comment]
Thanks, fixed in ef68b0b
