### ISSUE TITLE
Issues rendering in *Messages* buffer and not in org buffer

### ISSUE THREAD

**Issue by ezmiller** [ahungry/org-jira#250]
When I run `org-jira-get-issues` the issues are being fetched, but their content ends up in the `*Messsages*` buffer instead of the org-mode file buffer where I run the command. 

Anyone know why this might happen?

**Comment by ahungry** [comment]
I've never seen this - certain request.el log levels may show issue output in *Messages*, but it certainly shouldn't try to render the org formatted issues in that buffer (the buffer by default is read-only - is yours read-only disabled?)

**Comment by ahungry** [comment]
@ezmiller sometimes issues from fetch commands end up in specialized org files just for their particular project, not necessarily where you invoked the command from.

Going to close for now, please reopen if you have more details to reproduce.

**Comment by ezmiller** [comment]
@ahungry I will try again soon. I haven't had a chance to go back and try it again.
