### ISSUE TITLE
completion for @mention in comments

### ISSUE THREAD

**Issue by stfl** [ahungry/org-jira#254]
We're using jira comments to communicate within the team which requires mentioning the user with `@username`
In org-jira this is turns into `[~accountid:<id>]`
I'd love to have a completion function to select the username and insert the accountid

this should work with `(org-jira-get-assignable-users)` but my elisp experience is quite limited.
Maybe someone already has a function for that and is willing to share.

**Comment by ahungry** [comment]
If anyone does, feel free to make a PR, this would be a nice addition.
