### ISSUE TITLE
Cannot create issues from existing org-mode TODOs

### ISSUE THREAD

**Issue by worldofgeese** [ahungry/org-jira#257]
When trying to create an issue from an org-mode TODO such as, `* TODO Up and running with org-jira`, I receive the following error:
```
"JIRA_ERROR REQUEST: "

"/rest/api/2/issue"

(:type "POST" :data "{\"fields\":{\"project\":{\"key\":\"IN\"},\"parent\":{\"key\":null},\"issuetype\":{\"id\":\"10292\"},\"summary\":\"Up and running with org-jira\",\"description\":\"\\n\",\"priority\":{\"id\":\"4\"},\"assignee\":{\"accountId\":\"60a41e425d67f200694a7ed1\"}}}")

"JIRA_ERROR RESPONSE: "

((errorMessages . []) (errors (priority . "Field 'priority' cannot be set. It is not on the appropriate screen, or unknown.")))

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
```

The error message indicates that field `priority` cannot be set but I know that priorities are supported on Jira tasks. Here's the same task created through the console and synced down using `org-jira-get-issues`:
```
* IN-Tickets
** TODO Launch MVP cluster in Best Practices tryfamly_co VPC :IN_195:
:PROPERTIES:
:assignee: $FULLNAME
:filename: IN
:reporter: $FULLNAME
:type:     Task
:type-id:  10292
:priority: Medium
:status:   To Do
:created:  2021-07-16T08:54:36.112-0500
:updated:  2021-07-16T08:54:57.887-0500
:ID:       IN-195
:CUSTOM_ID: IN-195
:END:
:LOGBOOK:
:END:
*** description: [[https://famlyapp.atlassian.net/browse/IN-195][IN-195]]
```

I can pull existing issues in that I've created through the Atlassian console.

**Comment by worldofgeese** [comment]
This applies to creating any type of issue inside Jira. Subtasks, epics, tasks are all blocked from creation by the same basic set of errors:

**Comment by worldofgeese** [comment]
The only two commands which are successful are `org-jira-get-issues` and `org-jira-add-comment`

**Comment by ahungry** [comment]
jiralib-update-issue has a function signature that reads as `key fields &optional callback` - I'm thinking since "fields" is likely the issue, I may just add a defcustom filter here, where anything in the custom `jiralib-update-issue-fields-exclude` would be omitted.

**Comment by ahungry** [comment]
This can be customized via `jiralib-update-issue-fields-exclude-list` now - add the problematic fields in here, and they won't attempt to sync on update.

**Comment by PrismaPhonic** [comment]
This might have been prematurely closed. @ahungry from what I can tell this only effects issue update and not creation of new issues, which ignores this exclusion list
