### ISSUE TITLE
how can i get all issues?

### ISSUE THREAD

**Issue by donovankim** [ahungry/org-jira#26]
'with filter' command was removed. and get-issues only get 100 results.
how can i get all?

**Comment by ahungry** [comment]
Was with filter ever working for you?  There was a call for it, but no API endpoint ever associated to the call.

I can add an update to allow the max limit to be customized though.

**Comment by ahungry** [comment]
Look in the README at the custom-jql documentation, you can more easily define refined queries, as well as a custom LIMIT per JQL query.

I don't think I will be implementing pagination of any sort though.

**Comment by greened** [comment]
I am also struggling to figure out how to get all the issues assigned to me.  How is `org-jira-get-issues-from-custom-jql` supposed to work?  Does it run all of the queries in `org-jira-custom-jqls`?  Can it be run via M-x from any buffer or only via C-c ij in van org-jira buffer?  I have not been able to get it to consistently return results.  I don't see any messages or other output from org-jira.  Onm occasion I do get issues back but it is not consistent.

**Comment by greened** [comment]
Still not seeing data from custom queries.

**Comment by weipe** [comment]
I had problems getting all issues too, from a board with loads of issues. I'm not sure, but I think the Jira server has a max size limit of the response list too in its configuration. The only way I can get org-jira-get-issues to retrieve all my issues is to use custom queries to get them in a number of sub queries, using contstraints on the properties. I read somewhere that you can also paginate queries with max and offset parameters, to work around the restriction in the Jira server.
