### ISSUE TITLE
Feature Request: Add Customizable Keymap Prefix

### ISSUE THREAD

**Issue by nickgarber** [ahungry/org-jira#260]
The `org-jira-entry-mode-map` keymap includes the `C-c` as prefix to each key-chord.

May we restructure this to make it easier for folks who want to use a difference prefix, through `use-package`'s `:bind-keymap`, for example?

```emacs-lisp
(use-package org-jira
  :after (org)
  :bind
  (:map org-jira-entry-mode-map
	("i G" . org-jira-get-issues)
	("i s r" . org-jira-set-issue-reporter))
  :custom
  (org-jira-keymap-prefix "C-c M-j"))
```

This would help with issues such as #211 

I'm comfortable drafting a PR for this myself and (as always) appreciate any guidance on standards and practices.

Here's what I'm thinking:
- Add a `defcustom` variable, `org-jira-keymap-prefix` with a default value of `C-c` 
- `org-jira-keymap-prefix` is inserted as prefix when the `org-jira-entry-mode-map` variable is created

**refs**:
- `:bind-keymap` at https://jwiegley.github.io/use-package/keywords/
- https://www.gnu.org/software/emacs/manual/html_node/emacs/Local-Keymaps.html

**Comment by ahungry** [comment]
Nice idea - as long as the defaults (C-c) continue to work without any user involvement/changes I think this would be a very welcome addition - no special hoops to jump through on the code end, just use your best judgment :)

**Comment by nickgarber** [comment]
That's what I had in mind: add an option but retain the current behavior by default.

I'll put together some parens on this. Much obliged!

**Comment by nickgarber** [comment]
Thanks @ahungry!

**Comment by nickgarber** [comment]
I just noticed that the keymap prefix doesn't show up in places like `ivy-rich`. So, for example, instead of `C-c i g` showing up only `i g` is showing up. 

This is obviously not ideal. Not sure the best way to resolve this but am amenable to feedback.

**Comment by nickgarber** [comment]
Just a heads up I'm re-reading up on this and hoping to make a more wise and correct PR in the next week or so :)
