### ISSUE TITLE
Run org-jira-get-issues & org-jira-refresh-issues-in-buffer in the background

### ISSUE THREAD

**Issue by YujiShen** [ahungry/org-jira#262]
I am trying to write a method to fetch new issues and refresh current issues. I have following code:
```elisp
(defun yuji/org-jira-sync ()
  (interactive)
  (call-interactively #'org-jira-get-issues)
  (dolist (i org-jira-project-filename-alist)
  (with-current-buffer
    (find-file-noselect (cdr i))
    (org-jira-refresh-issues-in-buffer)
    (run-with-timer 10 nil #'save-buffer)
    )))
```

The method works but there are 3 problems:
1. It has to switch to the buffer of the Jira file. I think it is due to `(call-interactively #'org-jira-get-issues)`. Is it possible to run all these process in the background?
2. If I comment this line, the rest of code (refresh the issues) does not work. It should switch to the Jira file and refresh the issues there. What is wrong with this code? I adopt it from https://github.com/kidd/org-gcal.el/issues/65
3. I have to use a timer to delay save the buffer, otherwise sometimes it will not save the file if the `save-buffer` run immediately after refreshing. Any way to make this more robust instead of a timer?

**Comment by ahungry** [comment]
1. The legacy code expects to be able to hop around files to write contents - my large revamp a few years ago to async speeds up the process, but it still needs to jump to buffers, so I would say most likely the answer is "no" - a better way to achieve this might be to just run emacs batch commands from the CLI on a cron job or something.
2. I don't know, the code is not part of org-jira.
3. Probably an issue with the callback nature of async issue fetching - without a hook to run when all async things are done (such a hook does not exist at the moment) I don't think so.
