### ISSUE TITLE
Pull an issue (or issues) into any org file

### ISSUE THREAD

**Issue by ezmiller** [ahungry/org-jira#265]
Is it possible to import an issue (or issues) into an arbitrary org file rather than having the issues imported into a file in `.org-jira`? 

For example, I use org-journal. Can I import jira entries directly into an org-journal file?

**Comment by ahungry** [comment]
Not at the moment, but I wouldn't be opposed to a PR which added the functionality :)

**Comment by NimSed** [comment]
I was looking for an answer for a similar question, when found the below feature:
https://github.com/ahungry/org-jira/pull/169
It is not exactly what OP asks, but is very helpful -- and I guess undocumented.

If we could only customize the heading under which the items are added...

**Comment by ezmiller** [comment]
@NimSed can you elaborate a little. I followed that link you provided, but it wasn't clear to me how this relates. 

I still struggle to use this package because my use-case is simpler. I just want to pull in a single issue, or a set of issues (perhaps by JQL) into a buffer of my choosing. 

Conversely, when I try org-jira-get-issues or some such, I just get a bunch of junk (i.e. old issues etc), and that may be a result of the way our Jira is managed, but it leaves me stuck.
