### ISSUE TITLE
Customizing required fields for creating an issue

### ISSUE THREAD

**Issue by kamyabzad** [ahungry/org-jira#266]
It would be really nice if we could customize the required fields for `org-jira-todo-to-jira` and `org-jira-create-issue`: different Jira servers could have their own requirements for a ticket. In my case, I don't need, for example, `priority` to be set, but I need to have a due date and an estimation for each ticket; because of this, I'm not able to use the mentioned functions as org-jira doesn't care about these fields when creating a new issue (correct me if I'm wrong). If currently there's no way of achieving this, I'm willing to contribute.

**Comment by nickgarber** [comment]
Same issue - the priority field is causing the create issue POST to be rejected ...

```
Result: ((fields (project (key . "EMACS")) (parent (key)) (issuetype (id . "10018")) (summary . "convert org-setupfile to customize values") (description . "convert org-setupfile to customize values") (priority (id . "4")) (assignee (accountId . "<xx-redacted-xx>"))))
edebug-instrument-callee: You must be before a list form

[error] request--callback: peculiar error: 400

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/issue"

(:type "POST" :data "{\"fields\":{\"project\":{\"key\":\"EMACS\"},\"parent\":{\"key\":null},\"issuetype\":{\"id\":\"10018\"},\"summary\":\"convert org-setupfile to customize values\",\"description\":\"convert org-setupfile to customize values\",\"priority\":{\"id\":\"4\"},\"assignee\":{\"accountId\":\"<xx-redacted-xx>\"}}}")

"JIRA_ERROR RESPONSE: "

((errorMessages . []) (errors (priority . "Field 'priority' cannot be set. It is not on the appropriate screen, or unknown.")))
```

**Comment by ahungry** [comment]
I recently added this defcustom for updating:

jiralib-update-issue-fields-exclude-list

It allows exclusion of certain fields/keys (any in this list will not be sent to the server for updates).

Maybe it could be adapted for the create issue problem?

If so, feel free to make a PR.
