### ISSUE TITLE
Question: Ability to add custom fields

### ISSUE THREAD

**Issue by djgoku** [ahungry/org-jira#267]
I am trying to create an issue. The create issue fails to create because there are missing required fields.

Is this same data also apart of updating and progressing issues too? Because I am getting errors there too when trying to close an issue too.

I would like to try and contribute but really don't know where I should focus on to add this functionality.

**Comment by ahungry** [comment]
What fields in particular?

Can you try using the custom, "jiralib-update-issue-fields-exclude-list" and see if it solves your issue?

**Comment by djgoku** [comment]
I need a few custom fields we use for putting in time estimate, labels (tags) and another field I can remember right now.

When I use org-Jira-create-issue it errors with the above three fields are required.

**Comment by ahungry** [comment]
Ah, you need more fields sent in, not less.  At the moment, there isn't an option to include additional fields - if you wanted to extend the package to add that feature, that would be a welcome PR.

**Comment by whompyjaw** [comment]
Is there still no support for this?
