### ISSUE TITLE
Sync Jira ticket status history into Orgmode

### ISSUE THREAD

**Issue by YujiShen** [ahungry/org-jira#269]
Is it possible to sync the status history from Jira into Orgmode? 

I separate my clocks from status change in Orgmode, and I usually update status of tickets in Jira and log time in Org. I don't want to sync worklog but want to sync status history.

**Comment by YujiShen** [comment]
I found even I progress issue in Orgmode, the status change is not logged. Is this caused by my settings?

```
(setq org-log-into-drawer t)
(setq org-clock-into-drawer "TIMESHEET")
(setq org-log-done 'time)
(setq org-log-repeat nil)
(setq org-log-reschedule t)
(setq org-log-redeadline t)
(setq org-todo-keywords
    '((sequence "TODO(t!)" "NEXT(n!)" "DOING(i!)" "WAITING(w!)" "HOLD(h@/!)" "SOMEDAY(s!)"
        "|" "DONE(d!)" "CANCELLED(c@/!)")))

(setq org-jira-worklog-sync-p nil
    org-jira-jira-status-to-org-keyword-alist '(("Backlog" . "TODO")
                                                ("In Progress" . "DOING")
                                                ("In Review" . "WAITING")
                                                ("Blocked" . "HOLD")
                                                ("Done" . "DONE")
                                                ("Closed" . "CANCELLED"))
)
```

**Comment by ahungry** [comment]
I don't think there is any type of history that gets synced in either direction (if you're suggesting something like the History tab in the jira GUI/website itself).

As you've discovered via the setting shown in the snippet above, you can disable worklog syncing.

**Comment by YujiShen** [comment]
Thanks! Is it possible to trigger the state change and save it? For example, when the status of an issue is changed during refresh the buffer, log that into LOGBOOK or specified drawer.

**Comment by ahungry** [comment]
At the moment, no - it seems like that'd be a nice optional feature though - if you want to make a PR, I would suggest putting the behavior under a defcustom to make it a user opt-in feature.
