### ISSUE TITLE
Authenticating using `password-store` auth-source backend

### ISSUE THREAD

**Issue by cmacrae** [ahungry/org-jira#270]
Hey @ahungry, et al 👋 

Thanks so much for all the hard work on what looks like a brilliant package.  
I'd really like to integrate org-jira into my daily workflow, as I think it'll benefit me greatly. Unfortunately I can't seem to get the ball rolling.  

I use [password-store](https://www.passwordstore.org/) as my secret store, so as such I set `auth-sources` to `(password-store)`. This works in all places in my Emacs configuration, apart from org-jira, it seems.  

When calling `org-jira-get-issues`, this is what's returned:
```
I was called, was it with a callback? yes
auth-source-backend-parse: invalid backend spec: password-store
funcall-interactively: Wrong number of arguments: #<subr jiralib-login>, 0
```

Any ideas what's happening here? Other packages using auth-source are able to parse the backend and retrieve credentials just fine.

In case it's of any help, here are the relevant parts of my configuration (à la use-package):
```elisp
(use-package password-store
  :ensure nil
  :demand t
  :load-path "~/.nix-profile/share/emacs/site-lisp/password-store.el"
  :bind
  ("C-c M-p" . password-store-copy)
  :custom
  (auth-sources '(password-store)))

(use-package org-jira
  :if (string= system-name "workbook")
  :demand t
  :init
  (setq jiralib-url "https://<my company>.jira.com") ;; Redacted
  :config
  (let ((dir "~/.org-jira"))
    (unless (file-exists-p dir)
        (make-directory dir t))))
```

Any help on debugging this would be greatly appreciated 🙇

**Comment by cmacrae** [comment]
Ah... well clearly this issue served as a rubber duck. I think I must have some initialisation issues with my configuration. If I manually evaluate some of my configuration after a fresh start, it works! So, obviously this issue isn't with org-jira :)

Apologies for any e-mails/notifications! I'll close this off.

Thanks again for this package! Really looking forward to using it

**Comment by ahungry** [comment]
Glad to hear you figured it out :)
