### ISSUE TITLE
map a jira status to multiple agenda statuses?

### ISSUE THREAD

**Issue by dustinfarris** [ahungry/org-jira#272]
is there a way to map a jira status, like "In Progress" to multiple agenda statuses, like "TODO" and "BLOCKED"?

I see org-jira-keywords-to-jira-status-alist but that seems to be the reverse of what I'm looking for if I understand it right.

**Comment by ahungry** [comment]
Currently not - although if you wanted to develop this feature in a non-backwards compatability breaking manner, I would be open to the PR to add it.
