### ISSUE TITLE
org-jira-update-issue-details Field 'reporter' cannot be set.

### ISSUE THREAD

**Issue by jeremygooch** [ahungry/org-jira#276]
First off, thank you for this wonderful tool. It has made working with Jira so much better in my day-to-day!

When running `org-jira-update-issue` on a given issue after updating a field like description, I always get back the following error:
```
"JIRA_ERROR RESPONSE: "
((errorMessages . []) (errors (reporter . "Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown.")))
```

I'm not sure if I'm doing something wrong, or if something needs to be set up on my end, but to get around this issue I commented out the following lines in the `org-jira-update-issue-details` function:
```
  (org-issue-reporter (cl-getf rest :reporter (org-jira-get-issue-val-from-org 'reporter)))
  // ...
  (cons 'reporter (list (cons 'id (jiralib-get-user-account-id project org-issue-reporter))))
```
and the update works without issue. (I suspect the second line only is the issue.)

I didn't see this workflow documented so I'm not sure if this is a bug or just my naiveness, so feel free to close as a non issue if I am indeed doing something wrong.

If this is an issue and removing these lines would be helpful please let me know and I can open a PR for it.

**Comment by ahungry** [comment]
Try using the custom: "jiralib-update-issue-fields-exclude-list", and add reporter to it - let me know if that works, as that's the intended way to avoid setting it when you're unable to.

**Comment by jeremygooch** [comment]
Yep, that fixed the issue, and I see the documentation for that variable to help in the future. Thank you! Closing the issue.
