### ISSUE TITLE
how to preserve org mode priority

### ISSUE THREAD

**Issue by dustinfarris** [ahungry/org-jira#278]
is there a way to set a priority in org mode and keep it through subsequent `org-jira-get-issues`?  Right now if I set, e.g. **`[#B]`** the priority is removed when i get issues again.

I tried this, but it doesn't seem to help:

```
  (setq jiralib-update-issue-fields-exclude-list '(priority))
```

**Comment by ahungry** [comment]
At the moment, no - you could add a new defcustom to control this - look into matches in org-jira.el for "org-priority" (there aren't many) if you wanted to make the attempt.
