### ISSUE TITLE
Unable to create issues: wrong-type-argument symbolp

### ISSUE THREAD

**Issue by rand-fu** [ahungry/org-jira#279]
I've got another one but I'm not quite clear yet if this is entirely org-jira related so my apologies if not. I couldn't find a related issue.

After getting passed the emacs lock-up issue org-jira resumed working well, creating issues from todo items and creating/fetching issues in general.

Then it seems like after using `org-jira-create-subtask` several times successfully I could no longer create new issues with `org-jira-create-issue` or `org-jira-todo-to-jira`.

I'm getting the following error in the messages buffer. It doesn't seem to even make it to the curl calls to jira itself. I'm prompted for the issue board, issue type and then it errors out with the following.
```
ivy-read: Wrong type argument: symbolp, #("sub-task" 0 4 (ivy-index 2))
```
Maybe worth noting, whatever issue type I select from `org-jira-create-issue` seems to not matter and default to the last type I selected when running `org-jira-create-subtask`. Initially I thought that might be an ivy problem but if I switch to helm I end up with a similar error.
```
Debugger entered--Lisp error: (cl-assertion-failed ((if shistory (or (null history) (and history (symbolp history))) t) "Error: History should be specified as a symbol"))
```
I decided to toggle debug on error and got a little more info but I'm not sure how to debug this from here. Or why it suddenly stopped working in the middle of the day. I don't know if its at all related to the create subtask function, this is the first time Ive used it personally. I even tried purging org-jira, .elc  files, reset ivy's history. The only thing I haven't attempted in that regard is recreating on a separate system. I should have a chance to test that out later this week and see if I can reproduce. Any help is appreciated though.

```
Debugger entered--Lisp error: (wrong-type-argument symbolp #("Story" 0 5 (ivy-index 31)))
  ivy--update-history(#("Story" 0 5 (ivy-index 31)))
  ivy-read("Type: " (OMITTED)) #("Task" 0 4 (ivy-index 3)) #("Sub-task" 0 8 (ivy-index 6))) #("Story" 0 5 (ivy-index 31)))
  org-jira-read-issue-type()
  org-jira-todo-to-jira()
  funcall-interactively(org-jira-todo-to-jira)
  call-interactively(org-jira-todo-to-jira record nil)
  command-execute(org-jira-todo-to-jira record)
  counsel-M-x-action("org-jira-todo-to-jira")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "org-jira-create-issue" "org-jira-get-issues-by-board" "org-jira-todo-to-jira" "org-jira-create-subtask") :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

**Comment by rand-fu** [comment]
Some more investigation on this I can kind of reproduce it but I think its related to my own private config and our jira instance. I've played around with some excludes, and was able to get back to working behavior. I'm going to close this and chalk it up to my own mis-config for now. If I get the time I'll try to recreate this in case anyone else runs into a similar prob.

**Comment by LeeRuns** [comment]
@rand-fu 

Any tips on how you resolved this. I keep having the same issue.
