### ISSUE TITLE
Lisp error: (wrong-number-of-arguments #<subr jiralib-login> 0)

### ISSUE THREAD

**Issue by greened** [ahungry/org-jira#280]
I get the following with `M-x org-jira-get-issues`.  Indeed `jiralib-login` takes two arguments so I don't see how this is supposed to work.  This used to work for me and I'm not sure what changed.  As you can see I'm using ivy/counsel but I don't know if that has anything to do with it.  I don't see why it would.

```
Debugger entered--Lisp error: (wrong-number-of-arguments #<subr jiralib-login> 0)
  jiralib-login()
  funcall-interactively(jiralib-login)
  call-interactively(jiralib-login)
  jiralib-call("getIssuesFromJqlSearch" #f(compiled-function (&rest rest) "Callback for async, DATA is the response from the request call.\n\nWill send a list of org-jira-sdk-issue objects to the list printer." #<bytecode -0x1ec53924c2808a2f>) "assignee = currentUser() and resolution = unresolv..." 100)
  jiralib-do-jql-search("assignee = currentUser() and resolution = unresolv..." nil #f(compiled-function (&rest rest) "Callback for async, DATA is the response from the request call.\n\nWill send a list of org-jira-sdk-issue objects to the list printer." #<bytecode -0x1ec53924c2808a2f>))
  org-jira-get-issue-list(#f(compiled-function (&rest rest) "Callback for async, DATA is the response from the request call.\n\nWill send a list of org-jira-sdk-issue objects to the list printer." #<bytecode -0x1ec53924c2808a2f>))
  command-execute(org-jira-get-issues record)
  counsel-M-x-action("org-jira-get-issues")

```

**Comment by mujo-hash** [comment]
I've just run into this issue as well, and I too am confused as to what changed as this used to work for me as well.

**Comment by mujo-hash** [comment]
If I understand correctly, as jiralib-login is an interactive function, we can replicate this issue by calling jiralib-login directly. Here is my output when I do:
```
funcall-interactively: Wrong number of arguments: (lambda (username password) "Login into JIRA as user USERNAME with PASSWORD.

After a successful login, store the authentication token in
`jiralib-token'." (interactive (if (> 24 emacs-major-version) (let ((user (read-string "Username for Jira server login? ")) (password (read-passwd "Password for Jira server login? "))) (list user password)) (let ((found (nth 0 (auth-source-search :max 1 :host (if (string= jiralib-host "") (let ... ...) jiralib-host) :port (list (number-to-string ...) (url-port ...) (let ... ...)) :require '(:user :secret) :create ...))) user secret) (if found (progn (setq user (plist-get found :user) secret (let ((sec ...)) (if (functionp sec) (funcall sec) sec))) (list user secret)))))) (if jiralib-use-restapi (setq jiralib-token (cons "Authorization" (format "Basic %s" (base64-encode-string (concat username ":" password) t)))) (if jiralib-wsdl nil (jiralib-load-wsdl)) (setq jiralib-token (car (soap-invoke jiralib-wsdl "jirasoapservice-v2" "login" username password)))) (setq jiralib-user-login-name username)), 0
```

**Comment by mujo-hash** [comment]
@greened I was able to temporarily work-around this issue by eval-ing (jiralib-login "myusername" "mypassword") which created a token that org-jira then uses from then on. Hope that helps

**Comment by greened** [comment]
@mujo-hash that gets me further, thanks!

**Comment by ahungry** [comment]
What version of Emacs are you using? There is conditional logic looking for > 24 in the jiralib-login function.

**Comment by ahungry** [comment]
Also, jiralib-login, when called interactively - it will not need arguments in the code - those are provided by the user, based on the evaluation (list) result of the (interactive) form:

          ELISP> (defun hello (name) (interactive (list (read-string "What's your name?"))) (message name))
          hello
          ELISP> (call-interactively 'hello)
          "bob"
          ELISP> (hello "bob")
          "bob"

The list elements correspond to the defined parameter/argument list up in the function signature, so (call-interactively 'jiralib-login) itself is not a problem, but a red-herring.  Something else must be a problem, but I need the Emacs version to know which branch of this function I should be scrutinizing.

**Comment by mujo-hash** [comment]
@ahungry Gotcha, thanks! elisp is a weak spot of mine.

I am running GNU Emacs 27.2 on gentoo, do you need anything more specific?

**Comment by david-greene-cb** [comment]
This is still happening for me on Emacs 28.1.

**Comment by ahungry** [comment]
Is this still an issue for anyone?

**Comment by mujo-hash** [comment]
> Is this still an issue for anyone?

I'm not using this package right now, so I guess it's not an issue for me :p maybe someone else can chime in
