### ISSUE TITLE
org-jira-get-issues: JIRA-ERROR

### ISSUE THREAD

**Issue by greened** [ahungry/org-jira#281]
I'm not sure what to make of this:

```
I was called, was it with a callback? yes
Fetching issues...
[error] request--callback: peculiar error

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/search"

(:type "POST" :data "{\"jql\":\"assignee = currentUser() and resolution = unresolved ORDER BY\\n  priority DESC, created ASC\",\"maxResults\":100}")

"JIRA_ERROR RESPONSE: "

nil

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
```

This *is* this Messages buffer...

**Comment by ahungry** [comment]
That error should pop up in the modeline as it occurs (even if the *Messages* buffer isn't being displayed) - as a by product of doing so, it'll also show up *Messages* buffer, as you observe (where you may simply ignore it, and look up in the scrollback for more details).

Unfortunately, there don't seem to be any more details, just that the remote jira apparently gave you a nil (null) response.
