### ISSUE TITLE
Adding a comment fails with `Symbol's function definition is void: filename`

### ISSUE THREAD

**Issue by mvarela** [ahungry/org-jira#286]
Hi! When trying to add a comment via `org-jira-add-comment`, I get the above error. 
  ```
(defun org-jira-add-comment (issue-id filename comment)
  "For ISSUE-ID in FILENAME, add a new COMMENT string to the issue region."
  (interactive
   (let* ((issue-id (org-jira-get-from-org 'issue 'id))
          (filename (org-jira-filename))        ;; <<<<<------- This seems to be the offending line
          (comment (read-string (format  "Comment (%s): " issue-id))))
     (list issue-id filename comment)))
  (lexical-let ((issue-id issue-id)
                (filename filename))
    (ensure-on-issue-id-with-filename issue-id filename
      (goto-char (point-max))
      (jiralib-add-comment
       issue-id comment
       (cl-function
        (lambda (&key _data &allow-other-keys)
          (ensure-on-issue-id-with-filename issue-id filename
            (org-jira-update-comments-for-current-issue))))))))
```
When just evaluating `(org-jira-filename)` in the issue buffer, it seems to return the correct file name, so I'm a bit lost as to what the error may be.
Any help would be appreciated!

**Comment by ahungry** [comment]
Are you calling org-jira-add-comment with a hotkey, or via evaluation?

Where is the cursor when you call it?  (In an org entry body, or in the property drawer area?)

**Comment by mvarela** [comment]
I'm calling it via smex, haven't decided on using the bindings yet.
The error happens whether I'm on the ticket header, on the properties drawer, or in the body itself.

**Comment by ahungry** [comment]
Just eyeballing it, I'm wondering if the issue is actually in the lexical-let, where it has `(filename filename)` - maybe it's incorrectly treating that as a function call (due to filename itself being undefined in some way?)

I'll have to try this out and loop back around - I wonder if anyone else has experienced the issue?

**Comment by ahungry** [comment]
Looking into - I was able to reproduce...

**Comment by ahungry** [comment]
27e69c7 changed how the filename is handled - if I call it manually while on top of an issue `(org-jira-filename)` I get the ticket key as the name ("AHU-23"), while if I revert the commit, I get the proper file name when it may be a customized file (like "last-years-work.org").

**Comment by ahungry** [comment]
https://github.com/ahungry/org-jira/pull/268 - related discussion - that covers some of the history and may or may not be related - I'll have to look to see what a suitable fix is.

**Comment by ahungry** [comment]
Interesting - making a commit message with "Fix: <url to github issue>" auto-closed the issue - in any case, I think this should be working now via commit b4cbefc

**Comment by mvarela** [comment]
I'm running a git build (maybe a couple of months old, native compiled branch, with GTK support). I'll try the latest commit you pointed to, and see if that works out!
Thanks for being so responsive!

**Comment by mvarela** [comment]
Yep, that did the trick. Thanks!
