### ISSUE TITLE
Does this provide mapping org "TODO,INPROCESS,DONE" to JIRA (To Do, In Process, Done) ? Am I not configuring correctly?

### ISSUE THREAD

**Issue by LeeRuns** [ahungry/org-jira#288]
I have org mode setup to run a bunch of different TODO types, including types that match by jira board sequence. After reading through org-jira.el I setup the following 
```elisp
  (defcustom org-jira-jira-status-to-org-keyword-alist'(
                                                        ("To Do" . "TODO")
                                                        ("In Progress" . "INPROCESS")
                                                        ("Done" . "DONE")
                                                        ("Blocked" . "BLOCKED")
                                                        )
    )
 
  (defconst org-jira-progress-issue-flow'(
                       ("To Do" . "In Progress")
                       ("In Progress" . "Done")
                       )
    )


```
When I try to execute communication to either sync by pulling issues, or push my updates it wipes the categories and turns everything into either a todo or done.

Case 1:
org-jira-get-issues: -> results in list of only todo and done

Case 2:
1. I update an issue to INPROCESS (inside emacs/org-jira). Which should translate to "In Progress" according to the list above
2. I execute org-jira-update-issue: -> flips the "INPROCESS" to TODO

I thought that org-jira was able handle both of the cases above or at least one of them. Please let me know. If this is a bug, or is just not a feature right now. 

Thanks for the great application. I really appreciate it.

**Comment by ahungry** [comment]
If I set this:

```lisp
(setq org-jira-jira-status-to-org-keyword-alist
      '(("Closed" . "FOO")
        ("Resolved" . "BAR")
        ("Done" . "BAZ")
        ("In Progress" . "INPROGRESS")
        ("To Do" . "BUZ")))
```
and run `org-jira-get-issues-from-custom-jql` (my preferred way to fetch) which ultimately calls "org-jira-render-issue" for each issue in the result set (as most the jira->org sync calls do) it puts the cdr side values in place of the standard TODO/DONE keywords in the summary line of the org entries.

There is another variable that could have impact on this being rendered or not:

```lisp
(defun org-jira-get-org-keyword-from-status (status)
  "Gets an 'org-mode' keyword corresponding to a given jira STATUS."
  (if org-jira-use-status-as-todo
      (upcase (replace-regexp-in-string " " "-" status))
    (let ((known-keyword (assoc status org-jira-jira-status-to-org-keyword-alist)))
      (cond (known-keyword (cdr known-keyword))
            ((member (org-jira-decode status) org-jira-done-states) "DONE")
            ("TODO")))))
```

What is your `org-jira-use-status-as-todo` set to currently?  You can see that it could cause the alist in question to be disregarded if it were a truthy value.

**Comment by LeeRuns** [comment]
What is a truthy value?

**Comment by LeeRuns** [comment]
Hot dog, that works!!! Really appreciate it.

**Comment by LeeRuns** [comment]
Need to re-open because I now get the following error when the code above is implemented:

```lisp
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 3) 2)
```

**Comment by ahungry** [comment]
Hi @LeeRuns - you may have figured it out, but a truthy value is just anything that would satisfy the condition in an `if` statement or equivalent (pretty much everything but `nil` in emacs lisp).

I'm not sure what your current error is, maybe you could try debugging locally (if you don't have it set yet, try `(setq debug-on-error t)`
