### ISSUE TITLE
Error messages not useful

### ISSUE THREAD

**Issue by everops-miked** [ahungry/org-jira#289]
The error log contains no useful info. The 
```
I was called, was it with a callback? yes
Fetching issues...
[error] request--callback: peculiar error: 404

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/search"

(:type "POST" :data "{\"jql\":\"assignee = currentUser() and resolution = unresolved ORDER BY\\n  priority DESC, created ASC\",\"maxResults\":100}")

"JIRA_ERROR RESPONSE: "

nil

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
Mark set
[error] request--callback: peculiar error: 404

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/search"

(:type "POST" :data "{\"jql\":\"id = KEY-5990\",\"maxResults\":100}")

"JIRA_ERROR RESPONSE: "

nil

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
Quit
next-line: End of buffer [3 times]
Mark set
```

**Comment by everops-miked** [comment]
I used `(setq jiralib-url "https://SUBDOMAIN.atlassian.net/jira")` that was wrong. `(setq jiralib-url "https://zendesk.atlassian.net/")` worked. This still does not change my bug report, the error messages are not useful.

**Comment by ahungry** [comment]
I think the "bug report" is a bit subjective - the remote end gave a 404 (mentioned a couple times in the output) - that may not be useful to you, but it is useful to me.  Similarly, the other messages are useful to me, as they identify the request url/data being sent (to identify if anything odd is happening).

If you would like to contribute to the project by adjusting/enhancing the error messages to be more useful to you, most PRs are welcome, as long as they don't cause regressions, so please don't hesitate to make some updates and share them via a github PR.
