### ISSUE TITLE
Example output in README

### ISSUE THREAD

**Issue by jeigrei** [ahungry/org-jira#290]
Can `README.md` be updated to show what some example buffers look like? It would be nice to know if it will fit into existing workflows before configuring.

**Comment by ahungry** [comment]
Like, a screenshot or text paste of what org mode looks like? (basically, showcasing how the jira fields are mapped to the org properties?)

**Comment by jeigrei** [comment]
A text paste is what I was thinking, but yes, specifically for folks wanting to quickly see how the mapping is done, i.e., what does an org buffer look like after successfully running `org-jira-get-projects` or `org-jira-get-issues`
