### ISSUE TITLE
auth-source-search throws wrong-type-argument exception due to integer port argument

### ISSUE THREAD

**Issue by cellux** [ahungry/org-jira#291]
While trying to set up JIRA authentication with credentials provided by freedesktop.org secret service (KeepassXC), I stumbled upon the following issue:

```
Debugger entered--Lisp error: (wrong-type-argument stringp wrong-type-argument)
  format-message(wrong-type-argument 443)
  apply(format-message (wrong-type-argument 443))
  error(wrong-type-argument 443)
  secrets-search-item-paths("Secrets" :host "<redacted>" :port 443)
  apply(secrets-search-item-paths "Secrets" (:host "<redacted>" :port 443))
  secrets-search-items("Secrets" :host "<redacted>" :port 443)
  apply(secrets-search-items "Secrets" (:host "<redacted>" :port 443))
  auth-source-secrets-search(:backend #<auth-source-backend auth-source-backend-158baaf16c1c> :type secrets :max 1 :require (:user :secret) :create nil :delete nil :max 1 :host "<redacted>" :port ("443" 443 "https") :require (:user :secret) :create t)
  apply(auth-source-secrets-search :backend #<auth-source-backend auth-source-backend-158baaf16c1c> :type secrets :max 1 :require (:user :secret) :create nil :delete nil (:max 1 :host "<redacted>" :port ("443" 443 "https") :require (:user :secret) :create t))
  auth-source-search-backends((#<auth-source-backend auth-source-backend-158baaf16c1c>) (:max 1 :host "<redacted>" :port ("443" 443 "https") :require (:user :secret) :create t) 1 nil nil (:user :secret))
  auth-source-search(:max 1 :host "<redacted>" :port ("443" 443 "https") :require (:user :secret) :create t)
  ...
  call-interactively(jiralib-login)
  (if jiralib-token nil (call-interactively 'jiralib-login))
  ...
  jiralib-call("getIssue" #f(compiled-function (&rest request-response) #<bytecode 0x158baaf1696d>) "DTC-2344")
  jiralib-get-issue("DTC-2344" #f(compiled-function (&rest request-response) #<bytecode 0x158baaf1696d>))
  org-jira--refresh-issue("DTC-2344" "DTC")
  org-jira-refresh-issue()
  org-jira-refresh-issues-in-buffer()
  funcall-interactively(org-jira-refresh-issues-in-buffer)
  call-interactively(org-jira-refresh-issues-in-buffer nil nil)
  command-execute(org-jira-refresh-issues-in-buffer)
```

The culprit is apparently in this part of `jiralib-login`:

```
     (let ((found (nth 0 (auth-source-search :max 1
                                             :host (if (string= jiralib-host "")
                                                       (url-host (url-generic-parse-url jiralib-url))
                                                     jiralib-host)
                                             ;; secrets.el wouldn’t accept a number.
                                             :port (list (number-to-string (url-port (url-generic-parse-url jiralib-url)))
                                                         (url-port (url-generic-parse-url jiralib-url))
                                                         (url-type (url-generic-parse-url jiralib-url)))
                                             :require '(:user :secret)
                                             :create t)))
           user secret)
```

The `:port` parameter gets the list `("443" 443 "https")` and `secrets-search-item-paths` throws an error for the second value (443) as it does not accept numbers.

Removing the second integer value `(url-port (url-generic-parse-url jiralib-url))` from the list resolved the issue for me.

**Comment by ahungry** [comment]
```
(auth-source-search
 :max 1
 :host "example.com"
 ;; secrets.el wouldn’t accept a number.
 :port (list "80" 80 "http")
 :require '(:user :secret)
 :create t)
```

Evaluating this doesn't seem to fail for me, even if I remove the "80" so the list is `(list 80 "http")` , or just change to the literal `80` or `"80"` - I wonder if it's difference in Emacs version, or code path being taken if it's seeing something - regardless, it doesn't make sense to me to include port twice as is being done - it looks like a year or so ago @nickgarber updated 7524f98f to make this more robust.

If there are no objections, I think applying your fix is a good idea (if certain versions of Emacs want string port, and others want integer, we should just wrap that port logic in a conditional, not include both string and int port).

**Comment by cellux** [comment]
Maybe it depends on the execution path inside `auth-source-secrets-search` depending on the configuration of `auth-sources`, i.e. it may work differently for file-based sources (`~/.authinfo`, `~/.authinfo.gpg`) and others like secret service (which I am using).

In my case the setup is `(setq auth-sources '((:source (:secrets default))))`.

**Comment by cellux** [comment]
Based on [this](https://github.com/emacs-mirror/emacs/blob/master/lisp/auth-source.el#L97) definition, I would think that the `port` parameter should be a string.

There is a function [auth-source-ensure-strings](https://github.com/emacs-mirror/emacs/blob/master/lisp/auth-source.el#L881) which apparently used to force this constraint but it is only used in the [netrc](https://github.com/emacs-mirror/emacs/blob/master/lisp/auth-source.el#L918) and [plstore](https://github.com/emacs-mirror/emacs/blob/master/lisp/auth-source.el#L2072) auth backends.

From this I would think that the reason the change made by @nickgarber worked for him is that he uses the netrc backend which automatically coerced the `443` integer port value into a string.

**Comment by ahungry** [comment]
Sounds good enough to me to drop the int one - updated in ^
