### ISSUE TITLE
org-jira-get-issues JIRA_ERROR, *Messages* not helpful

### ISSUE THREAD

**Issue by david-greene-cb** [ahungry/org-jira#298]
I am getting this with `org-jira-get-issues`:

```
I was called, was it with a callback? yes
Fetching issues...
[error] request--callback: peculiar error

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/search"

(:type "POST" :data "{\"jql\":\"assignee = currentUser() and resolution = unresolved ORDER BY\\n  priority DESC, created ASC\",\"maxResults\":100}")

"JIRA_ERROR RESPONSE: "

nil

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
```

Note that I authenticated with a manual invocation of `jiralib-login` to work around #280.

**Comment by fk0** [comment]
In addition to above I captured the JIRA log piece:
```
30-Jul-2022 14:20:07.594 INFO [http-nio-8080-exec-3] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03r0xa60xa50x130x9a0xa20x800xad0xa9{c0xfe0xbb0xe60x1cd0xd80xd50xd00xbe0x0a0xd0k0x87;0xbb10xbe0x160x060x150xa1 ]. HTTP method names must be tokens
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ahungry** [comment]
Try `(setq request-log-level 'blather)` and see if the underlying request has any more info.

Is this for cloud jira?  I'm considering just flat out not supporting on-prem, as the cloud diverges more and more and no one that actually uses on-prem has stepped up to adopt the mantle of on-prem testing/QA (I've been on cloud only for the last 7 years).

**Comment by fk0** [comment]
same error with `'blather`
this is on-prem (docker version) running locally on my machine

**Comment by ahungry** [comment]
Can you make an API request by hand/from scratch with curl? (see `rest-calls/jira.rest` for a sample using Emacs rest-mode)?

I'm not surprised you still received the error with blather, but I am surprised if you don't have additional debug info in one of your output buffers as a result (I think `*Messages*` but maybe in a different buffer)

**Comment by fk0** [comment]
ok, so I managed to get the issues using emacs' restclient, below is the "normal" working output from curl
```
GET /rest/api/2/search?jql=assignee=REDACTED&startAt=2&maxResults=2 HTTP/1.1
MIME-Version: 1.0
Connection: keep-alive
Host: localhost:8080
Accept-encoding: gzip
Accept: */*
Cookie: JSESSIONID=326ED54386844DE6A5F989249A7D6262; atlassian.xsrf.token=BZJL-PC4O-2T8T-BL5I_88aeec0622249fb9226c855f6a916ca60a7cfbb8_lin
Authorization: Basic <REDACTED>
Content-length: 0

HTTP/1.1 200 
X-AREQUESTID: 1133x131x1
X-ASESSIONID: ekaf6y
Referrer-Policy: strict-origin-when-cross-origin
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: sandbox
Strict-Transport-Security: max-age=31536000
X-Seraph-LoginReason: OK
X-AUSERNAME: <REDACTED>
Cache-Control: no-cache, no-store, no-transform
Content-Encoding: gzip
Vary: User-Agent
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 05 Aug 2022 18:53:01 GMT
Keep-Alive: timeout=20
Connection: keep-alive

{"startAt":0,"maxResults":2,"total":0,"issues":[]}
```
now here's what I captured with wireshark from org-jira request
```
HTTP/1.1 400 
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 2201
Date: Fri, 05 Aug 2022 18:54:33 GMT
Connection: close

<!doctype html><html lang="en"><head><title>HTTP Status 400 ... Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 ... Bad Request</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030xd80x920x9b0xecS&#39;#0xcb0x0e0x8d10x8a0x9c0xc40x1d90x000xf50xbbWm0x120xea50x12@0x96R0x92%r0xa4 ]. HTTP method names must be tokens</p><p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p><p><b>Exception</b></p><pre>java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030xd80x920x9b0xecS&#39;#0xcb0x0e0x8d10x8a0x9c0xc40x1d90x000xf50xbbWm0x120xea50x12@0x96R0x92%r0xa4 ]. HTTP method names must be tokens
	org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base&#47;java.lang.Thread.run(Thread.java:829)
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.63</h3></body></html>
```
I don't see the request in the output so start to think that it might be something with my setup. However, I've already tried this on two machines (Mac/Linux) with the same result...

**Comment by fk0** [comment]
One very small difference in the error message
```
I was called, was it with a callback? yes
Fetching issues...
[error] request--callback: peculiar error: 403

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/search"

(:type "POST" :data "{\"jql\":\"assignee = currentUser() and resolution = unresolved ORDER BY\\n  priority DESC, created ASC\",\"maxResults\":100}")

"JIRA_ERROR RESPONSE: "

nil

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
```
note the 403 after `peculiar error:`, not sure if that makes any sense, but still

**Comment by ahungry** [comment]
400 is bad request (the input was not good), 403 is Forbidden (the auth is not good, similar to 401) - without pasting the details, can you look at the value of your `jiralib-token`?  Maybe it isn't being populated properly through org-mode, and it was in your curl header?

Which auth are you attempting?
- A REST api token
- A (mostly deprecated I guess) basic auth of base64 username:password
- A JWT token pulled off the jira web browser (by inspecting ajax requests the website makes - aka, the org-jira fallback for when all other auth fails)

**Comment by fk0** [comment]
ok, so finally it worked (get-issue only, as I have other problems, for instance with updating issue), I fixed the authentication (I guess it was simply a mix-up of different ways to supply credentials)
I believe, the 400 was caused by missing issues as it was a bare setup from scratch. I'll try to reproduce it with another docker container instance.

**Comment by ahungry** [comment]
Awesome, thank you @fk0 !  

If you can script the containerized setup (or provide copy/pastable commands, like `docker run --rm -it whatever:imagename`), or if the manual steps could be listed (and aren't too many) I would be willing to give a little more attention and try some interop between the package and a local docker jira instance.

**Comment by fk0** [comment]
Sure, I followed this [Quick Start](https://hub.docker.com/r/atlassian/jira-software) steps in the official docker hub for Jira. You can even run multiple versions to execute regression tests, etc.
Just let me know if you need more details, I'd be happy to help.

**Comment by et2010** [comment]
I got a similar error:

```
[error] request--callback: peculiar error: 400

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/search"

(:type "POST" :data "{\"jql\":\"assignee = currentUser() and resolution = unresolved ORDER BY\\n  priority DESC, created ASC\",\"maxResults\":100}")

"JIRA_ERROR RESPONSE: "

((errorMessages . ["Field 'assignee' does not exist or this field cannot be viewed by anonymous users." "Field 'resolution' does not exist or this field cannot be viewed by anonymous users." "Not able to sort using field 'priority'."]) (warningMessages . []))

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
```

**Comment by ahungry** [comment]
"Cannot be viewed by anonymous users" - maybe your jiralib-token is expired?

**Comment by et2010** [comment]
I refreshed the token but still saw the same error.

**Comment by et2010** [comment]
> I refreshed the token but still saw the same error.

After updating the elisp `request` package to the latest, it works again!

**Comment by etpng** [comment]
((errorMessages. [ "Field 'assignee' does not exist or this field cannot be viewed by anonymous us ers." "Field ' resolution' does not exist or this field cannot be viewed by anonymous users." "Not able to sort us ing field'priority'."J) (warningMessages [])）

That's my error. and I guess .authinfo file is invalid.

**Comment by ahungry** [comment]
That sounds like the output related to an improperly authenticated access attempt - I would suggest constructing a standalone `curl` call on your command line (or using Emacs `rest-mode` or postman etc.) - that might help you narrow the issue.

This is an older ticket with some resolution that I forgot to close out - going to close it now, if you discover a package issue please feel free to file a fresh ticket @etpng
