### ISSUE TITLE
Use org markup for node bodies

### ISSUE THREAD

**Issue by nickanderson** [ahungry/org-jira#3]
I wonder if [ox-jira](https://github.com/stig/ox-jira.el) could be used to automatically reformat org markup to jira. Something similar but in reverse could be used to convert jira syntax into org markup.

**Comment by ahungry** [comment]
Are you thinking to translate between jira markdown syntax and org markdown syntax?  So things like `{code}` in Jira would swap to the appropriate `#+BEGIN_SRC` block in the org buffer?

If so, I like that idea!

**Comment by nickanderson** [comment]
Indeed, that was the thought. Hummm initially maybe a body written in org markup could be translated to Jira on update.

**Comment by stig** [comment]
I fear a JIRA to Org translator is going to be very lossy. Perhaps one could wrap existing JIRA formatting in a special block something like:

```org
#+BEGIN_EXPORT jira
...
#+END_EXPORT
```

**Comment by nickanderson** [comment]
Indeed Jira to org would likely be very lossy. A special block seems like a reasonable idea.

**Comment by WarFox** [comment]
I'm using this with my spacemacs setup, and it works great!! Thank you so much for making this

It would be great if `org-jira` could convert

```org-mode
#+begin_src sh
   aws s3 cp ./sample_etl_job.py s3://my-bucket/sample_etl_job.py
#+end_src
```

to 

```
{code|language=bash}
    aws s3 cp ./sample_etl_job.py s3://my-bucketsample_etl_job.py
{code}
```
and vice versa.

I understand this is an old thread. Is there any work happening on this?

**Comment by ivaigult** [comment]
This project [here](https://github.com/nyyManni/ejira) has this exact feature.
> Two-way synchronization between JIRA and org-mode.

It [relies](https://github.com/nyyManni/ejira/blob/8675aaef6f8774f2c8aa6cf0957aba012743760b/ejira-parser.el#L29) on the ox-jira library though.

**Comment by ahungry** [comment]
If anyone wants to make this PR to do something similar, go for it.
