### ISSUE TITLE
Support Custom Fields

### ISSUE THREAD

**Issue by yuchen-lea** [ahungry/org-jira#301]
Thanks for your wonderful work!

It would be really nice if we could sync custom fields of jira. 

I looked into `org-jira--render-issue` , and tried `(slot-value Issue 'customfield_13103)`. Failed. It seems it only supports fields in   `org-jira-sdk-issue`. However, this [api](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-get) does return the value of customfield_13103. Thus I think there's a way to get its field from `jiralib-get-issue`.

I'm checking the following function:
- org-jira-find-value
- jiralib-custom-field-value

Couldn't find the way 😂 Any suggestions for how I can dig deeper?

**Comment by ahungry** [comment]
Hi @yuchen-lea - I missed this comment - hopefully you found some way to work around your issue.

If you'd like an enhancement to the package, feel free to PR it, they are always welcome :smile:
