### ISSUE TITLE
Updating an issue (org to jira), in a custom file, gets the issue to the default file

### ISSUE THREAD

**Issue by robs-nice99** [ahungry/org-jira#302]
Hi,

So I'm working on project A. I'm currently refining a couple of issues, so I used a custom jql to fetch them all to the file "current-work". I then changed descriptions and other details and then wanted to update them all to Jira.
I couldn't find a command to update the whole file, so I updated one by one. The problem is, every time I run `org-jira-update-issue` I get a copy of the issue in buffer A and focus changes to that buffer.

Is this expected?

**Comment by ahungry** [comment]
Hmm probably not - what version of Emacs and org-jira?
