### ISSUE TITLE
Issue labels not updated by org-jira-update-issue-details

### ISSUE THREAD

**Issue by jeromeag** [ahungry/org-jira#305]
The "labels" org-mode attribute is on org-jira-get-issues call.
This "labels" field is not updated in Jira server on org-jira-update-issue call.

**Comment by ahungry** [comment]
Just to check pre-merge - are you testing against Jira cloud, or an on-prem server at a particular version?

**Comment by jeromeag** [comment]
I tested onan on-prem server. Version is "Jira v8.20.10"
