### ISSUE TITLE
Add agile endpoints

### ISSUE THREAD

**Issue by marc0s** [ahungry/org-jira#31]
At our company, we're using the agile boards and sprints stuff from Jira.  It would be nice to have the ability to operate with those entities.

Mainly I want to be able to fetch my issues from the current sprint, so I can easily narrow the list of assigned issues.

I've started to work on this, but I'm a total elisp newbie so I'll need some help for sure.  I started here https://github.com/marc0s/org-jira/commits/issue-agile-requests

Any feedback will be appreciated 😃.

**Comment by ahungry** [comment]
Cool, good idea - what if you were to just pull in the assigned sprint as an org tag and then just filter the org view based on the tag match?  I assume your current idea is to only pull in the sprint issues vs all issues?

**Comment by sangm** [comment]
So my company is using the version that is supported, but this can also be done through JQL

C-u org-jira-get-issues

`assignee = currentUser() and sprint in openSprints()`
