### ISSUE TITLE
Selective Worklog sync

### ISSUE THREAD

**Issue by trentfisher** [ahungry/org-jira#311]
I have been using org-mode for many years, and am in a habit of logging my time and writing pretty unfiltered notes.  Now that I am trying to make these worklogs sync to Jira, I don't want all that going into Jira.  Is there a way to trim the worklog so that only part of the text goes to Jira?  Or perhaps only include the first line of text?

**Comment by ahungry** [comment]
Currently no, but it sounds like a good idea.  The closest is using `jiralib-worklog-import--filter-apply` (well, the external facilities that'd trigger it) to avoid syncing entire worklogs that you don't want to sync (other users worklogs).

If you PR it, and it doesn't break bc, it sounds like a great idea!

**Comment by trentfisher** [comment]
Since I don't know Emacs Lisp at all, could you give some hints as to how to do this?  I'm guessing I'll need to add a new "defcustom" to let people select the behavior they want, and then I'd have to do the modifications to comment-text somewhere between lines 1344 and 1346.

I was kind of hoping you'd at least leave this open as a feature request in case anybody else may be interested in this... maybe someone who actually knows how to do this?

**Comment by ahungry** [comment]
@trentfisher sure, I can re-open it for a couple days/weeks (I'll probably forget about it and it'll remain around longer :laughing: )

It's exceedingly rare someone implements a feature by request that doesn't give them a direct benefit, which is why I updated the language here: https://github.com/ahungry/org-jira/blob/master/CONTRIBUTING.md to note that in general requests for others to do work on behalf of a requester will be closed out unless accompanied by a PR that implements the change (other than bug fixes).

I had to change that up because the majority of issues were "wouldn't it be nice" type requests cluttering the Issues board.

**Comment by ahungry** [comment]
@trentfisher you're spot on for the lines to look at:
```
              let* ((worklog (org-jira-org-clock-to-jira-worklog org-time clock-content))
                     (comment-text (cdr (assoc 'comment worklog)))
                     (comment-text (if (string= (org-trim comment-text) "") nil comment-text)))
```

So in that area, you've found the comment, however org-jira-org-clock-to-jira-worklog is the function responsible for parsing an org entry and turning it into a record for jira (side note - this function suffers from what a lot of the old code does, even though I'm the guilty author - in an ideal world it'd be split - one to parse the org entry, then passing that structure into something else to convert to jira format - that way we would be able to unit test simple input/output, which is...challenging at the moment).

Anyways, that breakdown is this:
```
(defun org-jira-org-clock-to-jira-worklog (org-time clock-content)
  "Given ORG-TIME and CLOCK-CONTENT, format a jira worklog entry."
  (let ((lines (split-string clock-content "\n"))
        worklog-id)
    ;; See if we look like we have an id
    (when (string-match ":id:" (first lines))
      (setq worklog-id
            (replace-regexp-in-string "^.*:id: \\([0-9]*\\)$" "\\1" (first lines)))
      (when (> (string-to-number worklog-id) 0) ;; pop off the first id line if we found it valid
        (setq lines (cdr lines))))
    (setq lines (reverse (cdr (reverse lines)))) ;; drop last line
    (let ((comment (org-trim (mapconcat 'identity lines "\n")))
          (worklog-time (org-jira-worklog-time-from-org-time org-time)))
      `((worklog-id . ,worklog-id)
        (comment . ,comment)
        (started . ,(cdr (assoc 'started worklog-time)))
        (time-spent-seconds . ,(cdr (assoc 'time-spent-seconds worklog-time)))
        ))))
```
Where you can see some basic work on "lines" (dropping a first line, dropping a final line) and eventually combining the array of lines into the `comment` let assignment - if I were working on this feature, this is probably where I would insert a function call (maybe defaulting to `#'identity`) that would be capable of receiving a string as input, and returning a string as output (in your scenario, you would be able to (de)reference it via a defcustom, and define your string truncation/translation logic in there.

**Comment by ahungry** [comment]
I think the big "gotcha" you'll encounter (if you went with this approach) is that this would work great for pushing your worklogs up to jira (and not sending more note info than you intend to) - however as soon as it goes to re-sync the org entry, your extra/truncated messages will disappear forever, as the program will pull the jira worklog note as the authoritative data source and obliterate your old (self only) notes, as the sync operations are (generally) destructive and make sure they match up to jira.

**Comment by trentfisher** [comment]
Oh, that is a big gotcha.  I'll have to think about how to get around that.  It seems that I would either have to make the pull aware of the public/private parts, and only sync the public chunk; or maybe make the sync one-way, that is, make the org file the source of truth and don't pull back from Jira.  Either of those are tricky or problematic.  I shall think about it.  I created a fork yesterday and will experiment.  Many thanks for your guidance!

**Comment by ahungry** [comment]
I'm going to close this out - having this open or closed won't impact PR creation, so if you came up with something tangible, feel free to PR it :smile:
