### ISSUE TITLE
Updating Issues Confusion

### ISSUE THREAD

**Issue by bagnaram** [ahungry/org-jira#314]
I have a query set up to dump a list of issues (or tickets) that are assigned to my team. They fall under 
```org
* PROJECT-NAME
** TODO lorem ipsum :PROJECT-NAME_12345:
** TODO lorem ipsum dolar :PROJECT-NAME_123456:
```

But when I open one of the tickets up to add a comment via `org-jira-add-comment` I get a message `Issue PROJECT-NAME-12345 not found!` and it opens a new buffer called `PROJECT-NAME-12345.org` with the only contents `#+title: PROCJET-NAME 12345`. 

Am I doing something wrong in my flow? I would like to either update tickets inline or select one and open it in its own buffer (appears to be failing here)

**Comment by bagnaram** [comment]
After a bit of digging it appears to bail out after https://github.com/ahungry/org-jira/blob/master/org-jira.el#L1327

I think it may be failing because these JIRA tasks don't have any worklog data being set. Is there a way I can bypass this or ignore the worklog part? I am not very proficient in elisp sadly.

**Comment by bagnaram** [comment]
No it doesn't seem to be that. I am stumped  on this one. It tries to create the file, so only thing I can guess is that I am doing the workflow incorrectly

**Comment by ahungry** [comment]
Are you using `org-jira-custom-jqls`  / `org-jira-get-issues-from-custom-jql` for setting this up?

The primitive issue sync would be via the `"assignee = currentUser() and resolution = unresolved"` query from org-jira-get-issues (in which case they end up in buffers/files named after the project).

I thought I had it set up so the output from custom JQL worked for pushing updates - I don't use org-jira-add-comment (interactive) often, I usually type the comment in the org syntax and use org-jira-update-issue to push it up (with any other updates).

**Comment by bagnaram** [comment]
Hi, I am using `org-jira-get-issues-from-custom-jql` and here's an example:

```elisp
    (:jql " project = TESTGUY AND assignee in (6052b08a06cbba006a019a41, 62154f4bba649b006aac6c0b) order by created DESC "
          :limit 10
          :filename "team-test")
    ))
```

This fetches the issues like I want  it to. Then I add an inline comment like you mentioned by adding in ORG syntax
```org
*** Comment: firstname lastname
this is a test
```

ANd then firing off `org-jira-update-issue`. I get dropped into the same situation where a new file gets created for that issue with only the basic title content, and the same index out of bounds error message.

**Comment by jboyens** [comment]
I was able to work around this by having the issue under the point, then doing `C-c i r` (org-jira-refresh-issue) which created a org-mode buffer for that issue and then the commenting worked fine.

**Comment by ahungry** [comment]
I think the callback rendering of issue is likely not respecting the `:filename:` set in the area invoking the update - it seems to be falling into the default path of deriving the filename/buffer to open based on the project key.

I can reproduce, so I'll try to look into sometime soon.
