### ISSUE TITLE
org-jira-refresh-issues-in-buffer on a project buffer creates new buffers instead of updating the issues in the buffer

### ISSUE THREAD

**Issue by ArneBab** [ahungry/org-jira#316]
Hi,

When I run `C-c i R` in a project buffer (i.e. `DEVEL.org`), then org-jira creates a new buffer for every issue (named something like `DEVEL-1234.org`) instead of staying in the `DEVEL.org` buffer while the issues in `DEVEL.org` are then not updated.

This may be connected to https://github.com/ahungry/org-jira/issues/314 because the issues in the `DEVEL.org` file have a `:filename: DEVEL` property while in the `DEVEL-1234.org` file the filename is `DEVEL-1234`.

Thank you for org-jira!

Best wishes

**Comment by ahungry** [comment]
I think this should be good in the next update (4.4.1 or greater)

**Comment by ArneBab** [comment]
Wow — thank you very much!

**Comment by ArneBab** [comment]
To report back: I now run version 4.3.1 20230329.1527 (not yet 4.4.1, but the branch from 29th of march), and this works flawlessly again. Thank you!
