### ISSUE TITLE
how can I make it use basic authentication with token

### ISSUE THREAD

**Issue by alikthename** [ahungry/org-jira#317]
Hi! can't get issues with get-jira-issues
in jira account I don't use password (just login with google)
the output is 
`
"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/search"

(:type "POST" :data "{\"jql\":\"assignee = currentUser() and resolution = unresolved ORDER BY\\n  priority DESC, created ASC\",\"maxResults\":100}")

"JIRA_ERROR RESPONSE: "

((errorMessages . ["Field 'assignee' does not exist or this field cannot be viewed by anonymous users." "Field 'resolution' does not exist or this field cannot be viewed by anonymous users." "Not able to sort using field 'priority'."]) (warningMessages . []))

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
Auto-saving...
Mark set
`
 variables set are:
```
jiralib-url <jira access domain name>
jiralib-user-login-name <user>@<domain>
jiralib-user <user>
jira-password <token>
jira-token <token>
jiralib-token `("Authorization" . ,(concat "Bearer " jira-token))
```

**Comment by johnhamelink** [comment]
I was having login problems initially myself (fixed!). Increasing the log level helped me immensely when comparing working curl requests to what org-jira was doing:

```
(setq request-log-level 'blather)
(setq request-message-level 'blather)
```
