### ISSUE TITLE
Documentation for styling text

### ISSUE THREAD

**Issue by nickanderson** [ahungry/org-jira#318]
Am I not finding any notes about supported styling because it just hasn't been added? After a bit of experimentation I find that you can style the text.

```
{noformat}code block{noformat}

[A link to the org-jira project on github|https://github.com/ahungry/org-jira]

{noformat}a code block{noformat}

* un
* ordered
* list

# an
# ordered
# list

+underline+

-strike through-

{{verbatim}}

^superscript^

{color:#0747a6}Dark Blue{color}

😀

||*table*||*of*||*stuff*||
|with|things|in|
|it| | |



{panel:bgColor=#deebff}
Info block
{panel}

{panel:bgColor=#eae6ff}
Note block
{panel}

{panel:bgColor=#e3fcef}
success block
{panel}

{panel:bgColor=#fffae6}
Warning block
{panel}

{panel:bgColor=#ffebe6}
Error block
{panel}

----

{quote}Quote block{quote}

h1. h1

h2. h2

h3

h3.

*Expand block*

With content inside

```

**Comment by ahungry** [comment]
org-jira doesn't do any special markdown (although I recall some old discussion about improving bi-directional support on this - converting jira markdown to org syntax and vice-versa, when present in a Description or Comment block).

What you're seeing is likely just the syntax Jira itself supports (if you were to view the raw description/comment fields, and not their WYSIWYG editor).

If you like, you could make a small note in the readme pointing to the official Jira docs for this formatting support, but I don't think it merits it's own section, unless we were doing something custom with it.
