### ISSUE TITLE
Creating/Updating Issue/Comment with Umlaute fails

### ISSUE THREAD

**Issue by mic-ha** [ahungry/org-jira#32]
Hi, first of all: Thanks for this excellent work

We're using JIRA with german umlaute (öüöß) and unfortunately creating/updating an issue or comment fails. I get the following information (i.e. creating an Issue - this is what emacs returns to me)

```
<ns1:createIssue>
<ns4:in0 xsi:type="xsd:string">3a9e01ca71b0351ac41b2df0c5fa0800d40fd648</ns4:in0>
<ns4:in1><ns5:description xsi:type="xsd:string">Philipp hat einen anderen Benutzernamen als sonst und sollte den gleichen bekommen.</ns5:description>
<ns5:priority xsi:type="xsd:string">4</ns5:priority>
<ns5:project xsi:type="xsd:string">EJ</ns5:project>
<ns5:summary xsi:type="xsd:string">Benutzername von Philipp \303\244ndern</ns5:summary>
<ns5:type xsi:type="xsd:string">4</ns5:type>
</ns4:in1>
</ns1:createIssue>
</soap:Body>
</soap:Envelope>
```
Is it some configuration I missed or does it not work in generally?

**Comment by ahungry** [comment]
SOAP mode hasn't been actively worked on for a bit, as newer Jira versions have removed it.  Can you try with the REST mode?

**Comment by mic-ha** [comment]
Changed the mode to REST which works which unfortunately fails with Umlaute again (JIRA 6.4.2)

`|REQUEST [error] Error (error) while connecting to http://jira.glutrot.de/rest/api/2/issue/EJ-14/`

**Comment by ahungry** [comment]
I just pushed a change - can you see if update works now?

**Comment by ahungry** [comment]
Actually, your issue sounds similar to one that has been happening to users who have edited their Jira account name to be different from what their credential user originally was (your error translated appears to be `Philipp has a different user than usual and should get the same.`).

**Comment by mic-ha** [comment]
The title of the issue has nothing to do with JIRA, sorry if this lead to a misunderstanding.

As soon as I try to add, update a comment or issue I do run into this problem.

`Wrong type argument: stringp, nil`

I found out that even whitespaces within Type (we use a custom type "Graphical Task") breaks the process.

Any kind of encoding problem?

**Comment by ahungry** [comment]
Can you post a minimal working reproduction?

What does the org block look like?  (What title, attribute tags, and Description content etc.)?

**Comment by jgoerzen** [comment]
I seem to have the same issue when I try to update a comment.  Here's a backtrace:
`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-make-unibyte(nil)
  org-jira-decode(nil)
  org-jira-entry-put(11104 "ID" nil)
  org-jira-get-comment-body(nil)
  org-jira-update-comment()
  funcall-interactively(org-jira-update-comment)
  call-interactively(org-jira-update-comment record nil)
  command-execute(org-jira-update-comment record)
  execute-extended-command(nil "org-jira-update-comment" "org-jira-update-comm")
  funcall-interactively(execute-extended-command nil "org-jira-update-comment" "org-jira-update-comm")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
`

**Comment by jgoerzen** [comment]
Note there is no umlaut here, but it is true that `:type:` under `:PROPERTIES:` contains spaces.  Not sure if that's relevant.

**Comment by jvalkeejarvi** [comment]
I faced the same issue with org-jira using REST mode and Jira version 7.6.1. Updating/creating comment works when umlaut character is replaced with its html code (eq ä is `&auml;`).
