### ISSUE TITLE
org-jira-add-comment: Issue not found!

### ISSUE THREAD

**Issue by nickanderson** [ahungry/org-jira#322]
Not sure what happend, I know that I was able to add comments to tickets as recently as Monday and I don't recall making any configuration changes. But today when I try to `org-jira-add-comment` I get `Issue XYZ-123 not found!`.

`org-jira-get-issue` pulls issues into `XYZ.org` as second level sub headings and that still works, but updating comments or adding new comments does not seem to work.

```
Debugger entered--Lisp error: (error "Issue XYZ-123 not found!")
  signal(error ("Issue XYZ-123 not found!"))
  error("Issue %s not found!" "XYZ-123")
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55>(--filename-- --issue-id-- :data ((self 
...
  #f(compiled-function (&rest args2) #<bytecode 0x4a08de084e8e287>)(#<process request curl> "finished\n")
  read-event(nil t 2)
  sit-for(2)
  #f(compiled-function () #<bytecode 0xb922be447fc6485>)()
  apply(#f(compiled-function () #<bytecode 0xb922be447fc6485>) nil)
  timer-event-handler([t 25636 39761 203555 nil #f(compiled-function () #<bytecode 0xb922be447fc6485>) nil nil 725000 nil])
```

Oh, compiled-function. Right, I did swap out `emacs28` for `emacs28-nativecomp` this morning, so perhaps that is it.

`GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2022-05-31`

**Comment by nickanderson** [comment]
Well, I am not sure what was going on, but today after updating my system and rebooting it's working again. So closing.

**Comment by ahungry** [comment]
Nice!  Glad to hear that!
