### ISSUE TITLE
Multiple Jira Systems

### ISSUE THREAD

**Issue by trentfisher** [ahungry/org-jira#329]
So I have the misfortune of working in a company with a number of Jira systems.  Most of my work is against only one of those systems, but now I need to log work against a second one.  So I created a new org file and tried setting the new Jira system as local variables, like so:

```
#+STARTUP: logdone content indent
# Local Variables:
# mode: org
# eval: (org-jira-mode)
# jiralib-url: "https://another.jira.system"
# jiralib-token: (cons "Authorization" (concat "Bearer " (auth-source-pick-first-password :host "another.jira.system")))
# END:
```
I had to get rid of the eval line as it caused the error "File local-variables error: (error Variable binding depth exceeds max-specpdl-size)"

When I try org-jira-get-issue to get a single issue, it just says "Fetching issues..." a couple of times and does nothing.

I suspect the answer is either "you're doing it wrong" or "that isn't possible"... or, more likely, both.

As with the other issue I have open, I will try to add some debugging output to figure out what is going on, but I am doing that in my "spare time" (whatever that is :) but I figured I would check if I am doing something stupid first.

**Comment by ahungry** [comment]
I haven't tested or used for this purpose - I doubt many others have, so you may be blazing a new trail :smile:
