### ISSUE TITLE
Updating worklog

### ISSUE THREAD

**Issue by gtrev** [ahungry/org-jira#33]
Hi, my company forced me to use jira to track a new project and so I would like to thank you for the fantastic job you have done so that I don't have to leave org-mode :)

Now the question. When I create a new issue from org-jira (org-jira-create-issue)  it doesn't have any custom id or headline related to work log. If I create a worklog headline (with a link to the jira task) and then update worklog (org-jira-update-worklog), org-jira asks me a couple of questions (how much time spent and start date) then nothing happens: the worklog headline is deleted and if i go on the web interface the worklog is not updated.

I'm using org-jira latest from melpa (20170207.2145), Emacs 26.0.50 and JIRA v1000.747.1

Am I doing something wrong?
TIA

**Comment by ahungry** [comment]
I'll have to look into this, since taking over maintenance, I haven't tested out the worklog functions.  I'll get a fix going soon.

**Comment by ahungry** [comment]
So, this attempts to call an API endpoint labelled as "addWorklogAndAutoAdjustRemainingEstimate" in the jiralib, which unfortunately has never existed, so until I actually implement this as a new feature, there is no actual work log integration (but I have wanted this feature for awhile, and the menu prompts do seem to be there, so I'll look into the API backend to get it finished soon).

**Comment by ahungry** [comment]
I pushed a bugfix in 2.6.1 (well, it will produce an error now instead of just doing nothing).

Since the feature request is the same as this one, I'll close this ticket for now.

https://github.com/ahungry/org-jira/issues/12
