### ISSUE TITLE
org-jira won't get issues from team-managed board

### ISSUE THREAD

**Issue by tomoakley** [ahungry/org-jira#334]
Hi, I'm new to emacs, org-mode and org-jira. First of all sorry for opening an issue as this isn't a bug, just a question.

I'm trying to get issues assigned to me from Jira; when I run `org-jira-get-issues`, it gets issues from an old, company-managed board that hasn't been used in about 2 or 3 years - but I'm technically still a member of. However, my new team's board (which is listed as "team-managed" in Jira) doesn't get any issues from the `org-jira-get-issues` command. When I run `org-jira-get-issues-by-board` and pass in the identifier (listed in `org-jira-get-projects` and prepends the issue number in Jira), it gets the first 50 tickets on this board - I looked in the org-jira code and saw there is a limit of 50 to this query. 

Additionally I'm sometimes assigned ad-hoc or one-off tickets in other boards that I'm not normally a contributor to/member of. I would like to be able to get these in org-jira too.

What command do I need to run to get the tickets in the new board (I don't care about the old board) and the adhoc tickets I'm occasionally assigned? I also don't need it to return tickets from the past. Thanks.

**Comment by ahungry** [comment]
I would look at: https://github.com/ahungry/org-jira#get-issues-from-custom-jql

The command you can use to fetch, after configuring, is: `M-x org-jira-get-issues-from-custom-jql`

**Comment by ahungry** [comment]
To clarify a little bit if it wasn't apparent from the readme and the command - JQL is the Jira Query Language - the same type of query you can build or write yourself with the web jira UI - tune it to get the ticket list you'd prefer using the web UI, and then just transpose it into the Emacs config as documented.

**Comment by tomoakley** [comment]
Hi @ahungry, thanks I will try and work out the JQL I need to use. Never used JQL before! Will post back here when I get it worked out.

**Comment by tomoakley** [comment]
Was able to get all my assigned tickets with this JQL:
```
(setq org-jira-custom-jqls
  '(
    (:jql "
assignee = currentUser() AND status not in (Resolved, Closed, Done, 'Ready for live')
order by priority, created DESC "
          :filename "jira")
    ))
```

I added the status query as it was returning a lot of tickets that were old done. Different boards in my company have different ways of saying 'done' so there are a few labels. Will probably refine this query later on but for now it works well. Thanks for your help @ahungry and sorry for such a basic question.

**Comment by ahungry** [comment]
Glad to have helped!
