### ISSUE TITLE
I got only one issue from my Jira and it is very slow

### ISSUE THREAD

**Issue by yelatia** [ahungry/org-jira#34]
Hi,
I'm new to this tool , I tried the command org-jira-get-issues to load all my issues, I keep getting only one.

and it is very slow.

Am i missing something ?

Kind Regards,

**Comment by ahungry** [comment]
Are you using the REST mode?  The SOAP mode is mostly deprecated at this time.

What version of Emacs are you using?  What version of org-jira?
