### ISSUE TITLE
org-jira-create-issue

### ISSUE THREAD

**Issue by embeddedpenguin** [ahungry/org-jira#344]
I saw that https://github.com/ahungry/org-jira/issues/343 exists, but I made another issue because I have a different error.

```
condition-case: In ‘org-jira-create-issue History’ source: ‘(closure ((alistp . t) (history . initial-input) (default) (test)) nil (let ((cands (helm-comp-read-get-candidates history test nil alistp))) (if cands (progn (delete  (helm-cr-default default cands))))))’ 
 (wrong-type-argument listp initial-input)
```

When running `org-jira-create-issue` via M-x, I am prompted for the project and once I select the project, I get the above error.

**Comment by ahungry** [comment]
I see "helm" referenced in there - does it occur if you do it with helm mode disabled?

**Comment by embeddedpenguin** [comment]
Thanks! Switching to vertico from helm did solve the issue
