### ISSUE TITLE
What you think about open source Jira alternative solution Plane ?

### ISSUE THREAD

**Issue by dev590t** [ahungry/org-jira#346]
Plane is an open-source alternative to Jira. In less than a year, it becomes the most starred project management tool on GitHub: https://plane.so/blog/how-we-got-to-20k-github-stars

Plane probably will become a Jira replacement in open source community.

Will org-jira community intent to support Plane, maybe in future?

**Comment by ahungry** [comment]
No, but someone could fork this repo and use it as a starting point for an `org-plane` package or something.
