### ISSUE TITLE
Is there any existing package for evil users?

### ISSUE THREAD

**Issue by oscarvarto** [ahungry/org-jira#348]
Hi!

I use evil bindings with Emacs, and wondered if there is any existing package to use this package with evil mode.

**Comment by ahungry** [comment]
I use "evil-org-mode" for better org-mode bindings (I'm also an evil user) - although for bindings introduced here, I guess I just got used to them (like `C-c C-x C-i` for org-clock-in).  

Many of those were the original bindings in this package when I took it over.

evil-leader is a nice general purpose package for adding easier user custom bindings - I set my leader key to `;` (though I think Spacemacs uses space bar) - it allows binding things like `; i` to org-clock-in, without a dedicated <something>-evil package existing.
