### ISSUE TITLE
Insert a user accountid based on user name search

### ISSUE THREAD

**Issue by ahbc-sdg** [ahungry/org-jira#349]
Have a command like org-jira-get-users to provide a syntax that would insert the accountid
`[~accountid:822024:50def85f-9de6-4865-b317-4ed222ababccb]` into the comment

It would be a nice to have to be able to render the accountid string as a link to show the display name; something like 
`[[~accountid:822024:50def85f-9de6-4865-b317-4ed222ababccb][John H Doe]]`

**Comment by ahbc-sdg** [comment]
If something like an org link is created, it would need to be sanitized, since inserting the accountid `[~accountid:...]` will render correctly in the jira ui

**Comment by ahungry** [comment]
Sure, feel free to PR it - as long as it doesn't break backwards compatability, could be nice.
