### ISSUE TITLE
Can't install from Melpa

### ISSUE THREAD

**Issue by lowl4tency** [ahungry/org-jira#35]
```
Warning (initialization): An error occurred while loading ‘/Users/user/.emacs.d/init.el’:

File error: http://melpa.milkbox.net/packages/org-jira-20170207.2145.tar, Not found
```

**Comment by ahungry** [comment]
This sounds like a problem with the MELPA server, try refreshing the contents via a fresh `list-packages` command, as I see the latest org-jira it wants to install is: `curl -I http://melpa.milkbox.net/packages/org-jira-20170224.1951.tar` (which is a 200 OK), so I think your MELPA index is pointed to an out of date org-jira package (I'm guessing they don't continue to host the outdated one after updating).

**Comment by lowl4tency** [comment]
Ah, my bad, sorry :) Thanks a lot for the help

**Comment by ahungry** [comment]
NP!
