### ISSUE TITLE
Create new buffer to edit and send comment

### ISSUE THREAD

**Issue by ahbc-sdg** [ahungry/org-jira#350]
I'm think something where instead of using the minibuffer to add a comment, have a new buffer that provides the top area for the comment and, like magit, provide a commented out section underneath to help the user add different elements to the comment (something like: https://github.com/ahungry/org-jira/issues/349)

**Comment by ahungry** [comment]
If you PR it, I wouldn't be opposed, as long as it's similar to how you describe.
