### ISSUE TITLE
Custom JQL action does not remove tickets that no longer satisfy the filter?

### ISSUE THREAD

**Issue by dmitrym0** [ahungry/org-jira#356]
Howdy,

I have a custom JQL that only returns "live" tickets. Once I close the ticket ("In progress" -> "Done") the ticket no longer satisfies the JQL condition but it sticks around.

I can empty the buffer and rerun org-jira-get-issues-from-custom-jql and now I get the correct list.

Is this intended behaviour, or am I missing something?

Thanks!

**Comment by ahungry** [comment]
Expected behavior
