### ISSUE TITLE
Gitter channel for org-jira?

### ISSUE THREAD

**Issue by nightscape** [ahungry/org-jira#36]
Hi @ahungry,

what do you think about creating a Gitter channel for org-jira where one can have short discussions / Q&As?
For some discussions, the real-time chat in Gitter is a quite effective way of communication.

**Comment by ahungry** [comment]
It's not a terrible idea, although I've never used gitter for anything yet - I like github for handling of issues, but if users had general questions about how to use org-jira, that may be a nice area to have them.

As it is, there are not a whole lot of PRs or changes being made other than the ones I do, so not much to discuss unless I want to talk to myself more than usual :smile:

**Comment by ahungry** [comment]
I'm sure its a couple seconds of search away, but can you paste the instructions required to set this up here? (or link)

**Comment by nightscape** [comment]
Ok, let's see if this works:

1. Create a login for Gitter
2. Go to https://gitter.im/#createcommunity
3. On the bottom click on the link for `github projects`
4. Choose `org-jira` under `my repos`
5. Tick `Add badge to README on GitHub (via pull request)`
6. Next -> Next -> Next

After some time, a `gitter-badger` bot will create a PR that adds a badge to the README.

**Comment by ahungry** [comment]
Thanks, sorry for the slow reply, I'll probably look into doing this soon.

**Comment by ahungry** [comment]
All set https://gitter.im/org-jira/Lobby#
