### ISSUE TITLE
REQUEST [error] Error (error) while connecting to.

### ISSUE THREAD

**Issue by jamesrichardsonjr** [ahungry/org-jira#39]
Hi, I'm getting the following errors when trying to connect to our Jira instance:

REQUEST [error] Error (error) while connecting to https://<removed>/rest/api/2/project.
REQUEST [error] Error (error) while connecting to https://<removed>/rest/api/2/search.

I've removed the hostname, to keep $JOB happy.

I could use some help with sorting out how to debug this. I don't *think* it is environmental as I can hit the urls with other clients.

Thanks,
jr

**Comment by kaffeed** [comment]
I have the same issue, my company just moved from email authentication to normal usernames and, as org-jira seems to concat the host and the username to an email address.

**Comment by kaffeed** [comment]
Actually i just tried it on my linux machine at home and it works fine here.. What OS are you on?

**Comment by jamesrichardsonjr** [comment]
I'm on Debian GNU/Linux. Emacs 25.1. We authenticate against an AD domain.

**Comment by ahungry** [comment]
Please do not copy and paste the Authorization header, but turn up the request.el debug level:

```
(setq request-message-level 'debug)
(setq request-log-level 'debug)
```

This will provide a lot more info on the actual CURL call being performed by request.el.

Make sure your ~/.authinfo or ~/.authinfo.gpg also contains a Jira entry for the http url (even if you hit a real https endpoint).

**Comment by jamesrichardsonjr** [comment]
CURL was returning a 60, cert problem. Turns out the certs on the site have some sort self signed intermediate certificate. I imported those right ones into the cert store that curl sees and (org-jira-get-issues) is working.

Thanks for the help!
