### ISSUE TITLE
How to install on emacs 25?

### ISSUE THREAD

**Issue by bhmevik** [ahungry/org-jira#40]
Sorry if this is a stupid question.
I'm trying to install org-jira on emacs 25.1.1 on Fedora 25 (M-x package-install org-jira), but I get the error message "Package ‘emacs-24.5’ is unavailable". What am I doing wrong?

**Comment by bhmevik** [comment]
Yep. It was a stupid question.  I discovered that several packages gave the same error, and found out that I had an old version of package.el in the search path. I'll close the issue.

**Comment by ahungry** [comment]
Glad to hear it!
