### ISSUE TITLE
option to only sync worklogs for currentUser()

### ISSUE THREAD

**Issue by khaije1** [ahungry/org-jira#42]
This option should be enabled by default, since it's probably what most people would expect.

Enabling this option preserves the org-clock data as an individual's work log, while preserving a means to interface with Jira.

Also to provide greater clarity, each worklogs should indicate the `:user:` similarly to the `:id:` data.

**Comment by khaije1** [comment]
I'm hoping to dig into this a bit over the weekend. Any pointers on how to understand the modularity or control flow, or how to approach an implementation for this feature in general?

**Comment by ahungry** [comment]
Sorry @khaije1 missed this - for the most part, the org-jira.el file has all the org related code, while jiralib.el has the jira endpoints (you would want to find the current worklog code and customize the JQL it runs most likely).

**Comment by khaije1** [comment]
No worries! I think I have the beginnings of something useful.

My approach is to add a map filter function just after the worklogs are
extracted from the response body. The function will accept one or more
lambdas and return a vector containing only those worklogs that match.

This way maybe it could be extended for other purposes.
I'm working through how to manage the lambda selection and config from
within the customize system.

Seems like this may not be the ideal way to do it but that it'll do the
job. The sync from org->jira would remain untouched.

My time to work on it was cut short but once I'm able to finish would you
be willing to help me make it acceptable to merge?

**Comment by ahungry** [comment]
Absolutely!  Let me know when you've got what you want in place.

**Comment by khaije1** [comment]
Hi @ahungry, you'll find my work on adding an org-jira worklog filter here: 
https://github.com/khaije1/org-jira/tree/worklog-import-filter

Summary:
I've added a function, control variable, and inserted the filter function into the org-jira-update-worklogs-for-current-issue function.

control-variable: jiralib-worklog-import--filters-alist
filter-function: jiralib-worklog-import--filter-apply
inserted-into: org-jira-update-worklogs-for-current-issue

This works in my isolated scratch buffer testing, but I haven't tested it extensively yet.

I'm hoping to have the benefit of another's review, in particular for issues around clarity and completeness.

If possible could you please review and critique my approach?

**Comment by nickgarber** [comment]
I'll continue with additional cleanup and testing. Very interested in advice on improvements. 

Hoping to send a PR in the next couple weeks.

**Comment by ahungry** [comment]
For sure, looking through it tonight (sorry for the slowness again!)

**Comment by ahungry** [comment]
In the jiralib, your variable for predicate-fn-lst is mismatched between the function param, comment and the actual code (predicate-fn, predicate-fns-lst, and predicate-fn-lst).

I would also consider not executing the code in the body of the jiralib function jiralib-worklog-import--filter-apply at all, if the filter list is empty (whether you avoid calling it in org-jira or do a fully conditional body in the function).

Other than that, looking pretty good!

**Comment by khaije1** [comment]
I'll make those changes and submit a PR over the next few days. 

Side note: I'm not well acquainted with how to produce idiomatic/readable elisp, so would be happy to take on any suggestions you'd have on that front as well.

Really appreciate it @ahungry !

**Comment by ahungry** [comment]
np!  I would try out flycheck, it has a pretty good elisp linter and will give you lots of suggestions on the quality of your elisp syntax/code.

**Comment by khaije1** [comment]
I did some refactoring and am happier with this work now. 
Highlights:

- Simplified the configuration variable's layout and documentation
- Improved the function documentation
- Add practical and usable filter functions as examples, (disabled by default)
- Separated most of the (light) variable setup from most of the (heavy) variable processing
- Moved variable processing behind a condition gate to limit spurious processing
- Applied elisp flycheck recommendations to beautify the code

One thing I'd like to improve is the condition check. I'm not sure I'm getting the best use out of it. Any suggestions on that or elsewhere?

**Comment by ahungry** [comment]
Looking good!

I see a `message` call if the filter list isn't bound - please ensure user's do not receive a message that appears to be a warning if it is simply them leaving the default (unfiltered) setup in place.

For the filters, I see you defining values in the defcustom - those are changing the defaults from current (unfiltered as is now) to be filtered to only current user correct?  (if so, that sounds like a good change, but want to confirm default behavior is being altered).

You can add a summary to the change log comments at the top of the file that detail those types of events (sorry if you did already and I missed), such as:

```lisp
;;;; Changes since x.x.x
;;     Added filter for worklog sync
;;     Changed worklog sync default behavior to filter to just own-user worklogs by using the new filter
```

**Comment by khaije1** [comment]
The first element of each lists in this defcustom is the On-switch aka the "Global-Enable" element, so with the leading 'nil in each of these lists they are defaulting to Off. I'm hoping that including them as off-by-default will provide a helpful example.

My intent is that all current behavior will be unchanged by default with this work. 

FWIW, the "WorklogAuthoredByCurrentUser" filter is the one I use day-to-day by toggling the "Global-Enable" via `customize-group org-jira`.

As an aside about the "Global-Enable" element, this should make it possible to replace the 't/'nil with an "if" such that each filter could be dynamically/conditionally activated. 
I think there's a neat potential there, but it's a bit of an advanced use case so I'm not doing much to explore it at this point.

For quick reference, here's an excerpt of the section we're discussing:
```
(defcustom jiralib-worklog-import--filters-alist
  (list
   (nil "WorklogUpdatedByCurrentUser" (lambda (wl) (let-alist wl (when (and wl (string-equal (downcase jiralib-user-login-name) (downcase .updateAuthor.name))) wl))))
   (nil "WorklogAuthoredByCurrentUser" (lambda (wl) (let-alist wl (when (and wl (string-equal (downcase jiralib-user-login-name) (downcase .author.name))) wl)))))
  "A list of triplets: ('Global-Enable 'Descriptive-Label 'Function-Definition)
that apply worklog predicate filters during import.
```

I'll amend the commit to remove the `message`. Agreed, that shouldn't be there.

Just a note to say thanks for your help in reviewing this and getting it into better shape! I'm excited about these features :)

**Comment by khaije1** [comment]
Thanks for the guidance while working on this :)

**Comment by ahungry** [comment]
np!

**Comment by robs-nice99** [comment]
I'm using a version from elpa 20190301, and I don't see any :user: field in the LOGBOOK. Besides that, when I update my worklog all other issues times get edited, which is not very "polite". Do I need to add some configuration to get this behavior?

**Comment by ahungry** [comment]
Sure, if you want to make a PR to add the new feature, I would be happy to consider merging it.  I think (at my org) it's very rare to have multiple time charts among different people on the same ticket, so this isn't a feature I have a lot of self-need for atm.

**Comment by robs-nice99** [comment]
I never program in elisp, so that will be challenging. Anyhow, didn't Worklog import filter #58 did that already?

**Comment by nickgarber** [comment]
> From what I can see, after this merge, I should see the names of the user the worklog item reports to, and I should not edit other peoples worklogs. Do I need to add some configuration to get the behavior that?

Hi @robs-nice99, this feature doesn't add a `:user:` tag to worklogs. I considered it but eventually realized I wanted a way to hide irrelevant information, rather than adding additional context that could be tough to act on. So to re-iterate, there's no `:user:` annotation in this work.

The second part of your comment is spot-on. The default behavior is to grab all logs for an issue - becuase by default the ability to filter worklogs on import is disabled. This was done to preserve the preceeding behavior, and to basically make worklog filtering opt-in.

It sounds like you'd like to opt-in, so here's how you can do that ...

- Enter the customize system for `org-jira` by typing `M-x customize-group RET org-jira RET`
- Look for a variable entry called `Jiralib Worklog Import  Filters Alist` and click the `Show Value` button to expand.
- Within the expanded text you'll see a list of two options (by default). Locate the list entry called `WorklogAuthoredByCurrentUser`, and look to the Boolean `[Toggle]`
- Click on that `[Toggle]` to activate and deactivate worklog filtering. When it's "on", that particular worklog filtering is Enabled, and vice-versa.
- When Enabled, the `WorklogAuthoredByCurrentUser` filter will only return entries that were created by you. 

Sounds like activating the `WorklogAuthoredByCurrentUser` filter is what you're looking for. 


Hope that helps!

**Comment by robs-nice99** [comment]
Hy @nickgarber. Thanks for the detailed explanation. I usually set my configuration in `init.el`, with `setq`. So now, I learned what 'defcustom' is for, and I got to use the "UI". Thanks!

However, setting the `WorklogAuthoredByCurrentUser` had several issues, scrambling a bit of my Jira issues, and meaning I won't be using the org-jira for some time.

1. If I update the clock-log multiple times (I usually update it every time I add new time logs), it duplicates the clock logs.
2. I'm not sure if this result from that change, but apparently id did: whenever I logged some time, the remaining time would remain the same, effectively raising the expected time (worked time + remaining time = estimated).

**Comment by robs-nice99** [comment]
Hello again,
My company moved from the onprems option to the cloud Atlassin. And from what I can figure out, this filter now filters out all worklogs. If I turn it off I get all worklogs when I update an issue. When I turn it on I get no worklogs.
My JIRA has a Tempo plugin, might that be the problem?
