### ISSUE TITLE
Log in with Google

### ISSUE THREAD

**Issue by zovt** [ahungry/org-jira#44]
Can't seem to get this working. Our JIRA accounts redirect to google login, and then authorize from there. Any way to get that supported?

**Comment by ahungry** [comment]
I don't really have a way to test this, at the moment I am 99% sure it is not going to be possible with the current code base, as the auth is done with the `Authorization: Basic <base64user:pass>` type.  

Is yours being done with something like Oauth or Okta?  Or some proprietary google integration?

In any case, I'll tag this as a feature request, but I'm not sure its going to be doable - how  do you (if you can) handle manual calls to your Jira's REST api?  (is your REST api usable?  Do you hit an endpoint to store some type of token and pass it back on further requests)?

If you can provide a minimal working curl call example, I can probably work from there (one of the curl call you would use to get your auth, the other of an endpoint to, say, query a single issue).

Please make sure *not* to paste any sensitive data like a base64 password when copy/pasting your curl commands.

**Comment by ahungry** [comment]
Well, its your lucky day, my work just disabled basic auth and is using google/okta integration, so the priority on this just increased 100 fold :smile:

**Comment by zovt** [comment]
Nice :) let me know if you need anything else from me.

**Comment by ahungry** [comment]
I'll have a temporary workaround soon, that will just involve signing into the jira instance via your browser, and manually moving the auth headers/cookies into jiralib variables (like, copy the request as a curl from your browser debugger's network tab, most browsers have as a right click thing and just set it in a jiralib-auth-cookie variable or something).

If the expiration on the token was not too short, this wouldn't be terrible (org-jira requiring a cumbersome sign in once a week is better than no org-jira).

Then, direct integration into <random sso provider> is going to be a lot more work..

**Comment by ahungry** [comment]
So, to get around temporarily, when you right click in debug bar and Copy Request as Curl (in your browser), the value you see it have under the header for `Cookie: `, you can manually set your jiralib token as such:

```lisp
(setq jiralib-token
      `("Cookie" . ,(format "__atl_path=x.x.x.x...<bunch of cookie data omitted here>")))
```

That should at least get it usable again

**Comment by zovt** [comment]
Cool, thanks for looking in to this!

**Comment by jellelicht** [comment]
@ahungry: Could you elaborate a bit on this jiralib-token workaround? Do I need to copy all cookie data, or just the __atl_path one?

**Comment by ahungry** [comment]
Everything in the curl header that starts with that, so, I believer it would be all the cookie data.

I definitely recommend figuring this out by using copy to curl and looking in the curl command it gives you, so you know you grabbed curls full header cookie request.

**Comment by ahungry** [comment]
I think using oauth/google authentication on the Jira API end is going to require having your usage of it (the jira REST api) be registered by a Jira admin as a 'consumer' for oauth purposes - how many of you would be able to get administrative clearance/setup in such a scenario?

To me, it seems like if the admin is yourself, you can just continue to enable basic auth, and if it is not yourself and another person is imposing the oauth/google sign in, the best solution may actually be the cookie 'workaround'.

Maybe I can more seamlessly integrate that somehow...

**Comment by zovt** [comment]
The cookie method might be the best option in that case then? Not sure. Is there some way to get a google OAuth token and pass it as the credentials to jira?

**Comment by ahungry** [comment]
The oauth process appears to require a consumer (application for the API / API user) be registered through the Jira administrator interface as the first step:

https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-oauth-authentication

Without this first step present, there would be no public and consumer keys with which to sign the oauth requests (if you've ever used Emacs twittering-mode, you may recall where you had to go and elect to allow twittering-mode to access your twitter over oauth - in that scenario, the twitter user is the administrator granting access however).

As it is, I've had the same cookie workaround key for a week straight with no issue (ignoring the somewhat insecure nature of having this cookie value stored in plain text in my ~/.emacs, it is almost more convenient than the basic auth as I don't have to sign into org-jira each time).

I'm not sure how this could be automated though, as I'm sure the google oauth/sso form must have some sort of anti-automation on it...

**Comment by zovt** [comment]
Makes sense. I'd be ok with the cookie if I could encrypt the credentials via gpg or otherwise 

On May 23, 2017 11:40:39 PM EDT, Matthew Carter <notifications@github.com> wrote:
>The oauth process appears to require a consumer (application for the
>API / API user) be registered through the Jira administrator interface
>as the first step:
>
>https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-oauth-authentication
>
>Without this first step present, there would be no public and consumer
>keys with which to sign the oauth requests (if you've ever used Emacs
>twittering-mode, you may recall where you had to go and elect to allow
>twittering-mode to access your twitter over oauth - in that scenario,
>the twitter user is the administrator granting access however).
>
>As it is, I've had the same cookie workaround key for a week straight
>with no issue (ignoring the somewhat insecure nature of having this
>cookie value stored in plain text in my ~/.emacs, it is almost more
>convenient than the basic auth as I don't have to sign into org-jira
>each time).
>
>I'm not sure how this could be automated though, as I'm sure the google
>oauth/sso form must have some sort of anti-automation on it...
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahungry/org-jira/issues/44#issuecomment-303609198

-- 
Sent from mobile

**Comment by ahungry** [comment]
Well, you could actually - all org-jira requires is the variable (jiralib-token) be populated - you could have a setter for it in a gpg encrypted elisp file and just call `require` on the file, and Emacs should prompt you for the gpg password to decrypt it.

While it would still be in your running Emacs memory (in jiralib-token) it would at least not be persisted in plain text on disk anywhere.

Also, FWIW I don't think the cookie copied from browser has credentials in it, the sensitive data contained in it is the session id (if someone else got that, they could hijack your browser session basically).

**Comment by winmillwill** [comment]
I'm trying to get this workaround going and I've whittled down the headers to just the cookie and the curl command works, but there seems to be some nuance to setting `jiralib-token` that is escaping me, because I keep getting this for `jiralib-get-boards`:

```
REQUEST [error] Error (error) while connecting to https://REDACTED.atlassian.net/rest/agile/1.0/board?maxResults=50&startAt=0.
```

I'm no elisp guru, so it's hard for me to unpack what exactly I'm trying to accomplish with the backtick, the `format`, and the `. ,`. When I use the form given above, I just get this message:
```
savehist-printable: Not enough arguments for format string
```

**Comment by paralin** [comment]
@winmillwill also seeing the same issue

**Comment by ahungry** [comment]
I'll fix readme tonight, I don't remember why I had the format line in there - all it is is the string value of your browser cookie needs to go in jiralib-token, so this will suffice:

```lisp
(setq jiralib-token (cons "Cookie" "cloud.session.token=eyJ...<giant cookie token>"))
```

**Comment by Fedreg** [comment]
@ahungry This is working great.  Thank you!

**Comment by voteleobrown** [comment]
Was a more permanent solution to this ever engineered?

**Comment by ahungry** [comment]
Short answer - "no".

The big sticking point (for me at least) is that this type of setup done "correctly" and without a workaround usually uses the Oauth flow - however, unlike the Oauth flow on something like reddit's Oauth, where the user of the account gets to approve/deny which applications can integrate with their Oauth, Jira usually locks that down so that only the Jira Administrators can approve/deny apps (which means even if I built it out, you're going to have to get sign off from your JIra admins to use Oauth with "org-jira").

If anyone wants to implement, you can probably lift the oauth flow I added for md4rd-mode (mode for reddit) here https://github.com/ahungry/md4rd and tie it into the login/auth stuff in jiralib.

I find the workaround very simple and a once-of type thing as it never seems to expire on the Jira side.

**Comment by winmillwill** [comment]
Hitting a weird issue here: the first request will succeed, but then the cookiejar that request.el causes 500 errors. Deduced this by setting the cookiejar var to `"/dev/null"` and observing that the 500's went away.

**Comment by winmillwill** [comment]
FWIW, it looks like using a personal api token from [here](https://id.atlassian.com/manage/api-tokens) and your email from [here](https://id.atlassian.com/manage-profile/email) and doing basic auth is supported. Works for me and I'm auth'ing with google.

**Comment by voteleobrown** [comment]
I discovered the personal API token solution today as well, and just came back here to mention it.

**Comment by jgoerzen** [comment]
As far as I can tell, there is no version of the personal API tokens for the on-prem Jira (self-hosted rather than in the cloud).  But perhaps I'm missing something.  Wish that would be easier over here!

**Comment by jgoerzen** [comment]
With on-prem jira, there's no cloud.session.token either.  There's JSESSIONID and atlassian.xsrf.token.

**Comment by dorneanu** [comment]
Hi! I'm also struggling to get org-jira working with Jira and some SSO.

If I set the cookie header in my config file like this:

```
(defconst jiralib-token
   '("Cookie" . "cloud.session.token=<YOUR COOKIE VALUE>"))
```

it works. However I don't want to store the token in my config and the token will change almost every day. It should be possible to set the token via some environment variables (using `getenv`).

Since I'm quite new to Emacs and not really comfortable with Lisp, do you have an example how one could read the tokens value, let's say from the env variable `JIRA_TOKEN`?

Thank you very much.

**Comment by mrwacky42** [comment]
I too could not get `org-jira` to work with a Jira site that uses Google Oauth for login.
I followed the directions, and created a token, that worked just fine with `curl` on the command line directly (for `GET` requests).

But I couldn't get `org-jira` to fetch issues until I configured debugging:
```elisp
  (setq request-log-level '-1
        request-message-level 'warn)
```
And saw that the issue was XSRF validation failing.

I was very confused, until I found a line in my `~/.curlrc` that set my User Agent to a specific very old Firefox for some reason.
I commented that out, and `org-jira` works now.

**Comment by r4ravi2008** [comment]
> Hi! I'm also struggling to get org-jira working with Jira and some SSO.
> 
> If I set the cookie header in my config file like this:
> 
> ```
> (defconst jiralib-token
>    '("Cookie" . "cloud.session.token=<YOUR COOKIE VALUE>"))
> ```
> 
> it works. However I don't want to store the token in my config and the token will change almost every day. It should be possible to set the token via some environment variables (using `getenv`).
> 
> Since I'm quite new to Emacs and not really comfortable with Lisp, do you have an example how one could read the tokens value, let's say from the env variable `JIRA_TOKEN`?
> 
> Thank you very much.

Is your org using a custom jira server or jira cloud? If its a custom jira cloud all you need to do is:
```(setq jiralib-token (cons "Cookie" "<cookie content from you browser>"))```

**Comment by ahungry** [comment]
Closing this - if someone wants to make a PR with further enhancements to the authentication mechanisms, I wouldn't be opposed (as long as it doesn't break anything of course).

**Comment by tillydray** [comment]
Sorry to resurrect this thread, but it seemed to me like the best place to post. If you don't want to store your cookie in your config, you could do something like this (my elisp is weak, be gentle 😉)

```org
(defconst jira-cloud-session-token
  (substring
   (shell-command-to-string "shell command to get cookie") 0 -1))
(defconst jiralib-token
  '("Cookie" . '(concat "cloud.session.token=" 'jira-cloud-session-token)))
```

See https://stackoverflow.com/a/5020475 for more info on `shell-command-to-string`.

I use [1Password](https://1password.com/) and they have a [CLI](https://developer.1password.com/docs/cli/) to fetch these kinds of things. The syntax is `op read 'op://VAULT/Item_Name/Section'`. So mine looks something like `"op read 'op://Work/Atlassian/cloud.session.token'"`.

But if you're using `gpg`, `pass`, or whatever else, all you need is a shell command to fetch the cookie.
