### ISSUE TITLE
Automatic org-agenda integration ?

### ISSUE THREAD

**Issue by pmilosev** [ahungry/org-jira#45]
Hi
From what Ive seen so far I couldn't find any option that tasks pulled with org-jira are automatically added to the agenda.
What I was planning to do is write some hooks / wrappers around org-mode and org-jira so that when org-agenda is triggered, jira tickets are automatically included in it.

Is something like this already available ?

**Comment by ahungry** [comment]
There is a deadline sync available in org-jira (I believe it should be enabled by default).

If you sync up issues and they have deadlines added, they should show in your org-agenda (assuming you have ~/.org-jira directory in your org-agenda dirs).

Is something like that what you mean?

Oh, sweet beard btw :smile_cat:

**Comment by pmilosev** [comment]
Yeah, I know that issues will show in agenda if the files are part of org-agenda-files, but I couldn't find any existing mechanism to dynamically add them after issues are retrieved from jira.
What I managed to do so far is to extend org-jira-get-files with two hooks, one ran after each project-buffer is processed, the other one after all project-buffers are done. To keep the existing functionality, I moved existing `(switch-to-buffer project-buffer)` to a default hook.
Now with this I'm able to define custom hooks from init.el which would automatically save each project-buffer and additionally trigger org-agenda after all issues are downloaded.

But I ran into a completely different issue (present before but not obvious until I attached org-agenda in the last hook): `Debugger entered--Lisp error: (error "Issue NCA099SECO-285 not found!")`.
The error is reported bu macro `ensure-on-issue-id` but I couldn't find what causes it.
It's 100% reproducible on initial download of issues. I have dozen of projects with several issues in each.
It fails on different / random issues.
I suspect two things for now:
1. Data downloaded gets corrupted at random.
2. Asynchronous operation causing `ensure-on-issue-id` to be called before the project buffer is completely ready.

Any hint ?

**Comment by pmilosev** [comment]
OK,I  traced the error to `org-jira-update-comments-for-current-issue`, and it only breaks the flow if `debug-on-error` is enabled.
As it doesn't strictly relate to this issue, I'll open another ticket for it.
I should be able to push the new feature soon, after some testing.

**Comment by pmilosev** [comment]
How it works:
> (use-package org-jira
>   :config
>   (setq jiralib-url "https://my.jira.url.here/jira")
>   (setq org-jira-working-dir (expand-file-name "~/org/work/jira"))
>   (org-jira-auto-add-to-agenda t))

Now if you `org-jira-get-issues` and then `org-agenda`, you should have your new files included in the agenda as well.
Initially I targeted to also achieve a convenient way not to switch to jira buffers after `org-jira-get-issues` with:
> (remove-hook 'org-jira-get-issues-functions 'switch-to-buffer)

But the switch happens before this final switch to the last project file, so I gave up from that :)
Anyway I'll probably write some custom function for easy killing of all jira buffers.

Cheers
