### ISSUE TITLE
Retrieve logged time with org-jira-get-issues

### ISSUE THREAD

**Issue by shakthimaan** [ahungry/org-jira#48]
When using M-x org-jira-get-issues, is it possible to also include the "Logged" time in the :PROPERTIES: drawer?

**Comment by ahungry** [comment]
Look into the issue list on github for the thread about work log sync, that's the feature you seek.  It will sync logged time in both directions, between Org and jira.  

Or are you simply asking to keep the sum of time in the property drawer as well?  Even though you can sum the Org clocks with the clock report ?
