### ISSUE TITLE
Using cygwin curl in w32 Emacs fails to process a request

### ISSUE THREAD

**Issue by jtecca** [ahungry/org-jira#49]
This may be slightly related to #17 as I'm running GNU Emacs 25.1.1 (x86_64-w64-mingw32) on Windows 7 and getting errors for all of the org-jira-get* functions except org-jira-get-projects.

Unlike #17, I get the following after setting request to debug:
````
(setq request-log-level 'debug)
(setq request-message-level 'debug)
````

Output:
````
REQUEST [debug] REQUEST
REQUEST [debug] Run: curl --silent --include --location --compressed --cookie c:/users/jeff.tecca/.emacs.d/request/curl-cookie-jar --cookie-jar c:/users/jeff.tecca/.emacs.d/request/curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective %{url_effective}) --data-binary @c:/Users/JEFF~1.TEC/AppData/Local/Temp/emacs-request131168zuv --request POST --header Authorization: Basic Wk5FNTA0NzE6d2lyeTAhd2F2ZXNiaWtpbmk= --header Content-Type: application/json http://company.jira.com/rest/api/2/search
REQUEST [debug] REQUEST--CURL-CALLBACK event = finished

REQUEST [debug] REQUEST--CURL-CALLBACK proc = #<process request curl>
REQUEST [debug] REQUEST--CURL-CALLBACK buffer = #<buffer  *request curl*>
REQUEST [debug] REQUEST--CURL-CALLBACK symbol-status = nil
REQUEST [debug] REQUEST--CALLBACK
REQUEST [debug] (buffer-string) =

(:num-redirects 0 :url-effective http://maxResults:100/)HTTP/1.1 400 Bad Request

Server: Apache-Coyote/1.1

X-AREQUESTID: 682x1514029x1

X-ASESSIONID: r5qfcc

X-ASEN: SEN-2603490

X-Seraph-LoginReason: OK

X-AUSERNAME: myusername

Cache-Control: no-cache, no-store, no-transform

X-Content-Type-Options: nosniff

Content-Encoding: gzip

Vary: User-Agent

Content-Type: application/json;charset=UTF-8

Transfer-Encoding: chunked

Date: Thu, 18 May 2017 18:22:50 GMT

Connection: close



{"errorMessages":["Unexpected character ('j' (code 106)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')\n at [Source: org.apache.catalina.connector.CoyoteInputStream@163976f8; line: 1, column: 2]"]}
REQUEST [debug] REQUEST-RESPONSE--CANCEL-TIMER
REQUEST [debug] -CLEAN-HEADER
REQUEST [debug] -CUT-HEADER
REQUEST [debug] error-thrown = nil
REQUEST [debug] -PARSE-DATA
REQUEST [debug] parser = json-read
REQUEST [error] Error from parser json-read: (wrong-type-argument number-or-marker-p nil)
REQUEST [debug] data = nil
REQUEST [debug] symbol-status = parse-error
REQUEST [debug] Executing error callback.
REQUEST [error] Error (parse-error) while connecting to http://company.jira.com/rest/api/2/search.
````

The username and the `jiralib-url` are correct (I changed it in my reply here in order to avoid over-sharing information).  I presume that the authorization is working if I am able to get the list of projects for projects-list.org, but I am not sure how to confirm that.

If I execute the request in curl directly, I get the following output:
````
~ $ curl --silent --include --location --compressed --cookie c:/users/jeff.tecca/.emacs.d/request/curl-cookie-jar --cookie-jar c:/user s/jeff.tecca/.emacs.d/request/curl-cookie-jar --write-out "\n(:num-redirects %{num_redirects} :url-effective %{url_effective})" --data -binary @c:/Users/JEFF~1.TEC/AppData/Local/Temp/emacs-request1377201mP --request POST --header Authorization: Basic tokenpart tokenpart2 --header Content-Type: application/json http://company.jira.com/rest/api/2/search

(:num-redirects 0 :url-effective http://Basic/)
(:num-redirects 0 :url-effective http://tokenparttokenpart2/)
(:num-redirects 0 :url-effective http://application/json)HTTP/1.1 415 Unsupported Media Type
Server: Apache-Coyote/1.1
X-AREQUESTID: 591x1511723x1
X-ASESSIONID: r5qfcc
X-ASEN: SEN-2603490
X-Seraph-LoginReason: OK
X-AUSERNAME: myusername
Cache-Control: no-cache, no-store, no-transform
X-Content-Type-Options: nosniff
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 1135
Date: Thu, 18 May 2017 16:51:49 GMT

<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.17 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 415 - Unsupported Media Type</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>Unsupported Media Type</u></p><p><b>description</b> <u>The server refused this request because the request entity is in a format not supported by the requested resource for the requested method.</u></p><hr class="line"><h3>Apache Tomcat/8.0.17</h3></body></html>
(:num-redirects 0 :url-effective http://company.jira.com/rest/api/2/search)
````
I obviously changed the 'tokenpart' 'tokenpart2' strings before posting here in order not to leak more info.

I'm not sure where else to debug from here... Any ideas?

**Comment by jtecca** [comment]
Also, if I go the URL specified at the end of the curl statement (http://company.jira.com/rest/api/2/search) in my browser after I sign in from the browser, I get the first 50 issues out of all issues logged in our jira, which I think is the content that org-jira is looking for to parse.

**Comment by jtecca** [comment]
Looks like this is a Windows-specific issue.  Running the same emacs version and org-jira version on a remote Linux box and everything is working as expected.

**Comment by ahungry** [comment]
Hi, did you get to diagnose it any further?  It seems like it may be something related to the JSON object encoding on Windows (I'm making a guess here, due to the unexpected character that was encountered in the JSON string).

**Comment by jtecca** [comment]
The only other thing I was able to try was using the specific commit for request.el from #17 that @mfehlhaber identified as the commit before a regression was introduced.  Unfortunately, that did not fix the issue for me.  Originally I was running of of whatever is the latest from melpa.  

I'll try to dig into the request body that I'm getting back from the API to see what the issue is.  If I can grab the request body from my Linux box as well as my Windows box, I'll see if there's actually a difference.

I'll update again when I've got something more to look at.

**Comment by jtecca** [comment]
I think I have an idea of what the issue is.  I have cygwin installed on my system for SSH, git, etc, and have emacs interface with the cygwin CLI tools for as much of the work as I can.  Somehow my win32 emacs is picking up cygwin's curl and is using that to make the call to jira via request.el.

In the defun for request, there's some code that determines which backend to use:
```` emacs-lisp
(apply (if sync
             (request--choose-backend 'request-sync)
           (request--choose-backend 'request))
         url settings)
````
On my Linux box, this was returning `request--curl-sync` but was returning `request--curl` on the w32 emacs.  I hacked the `request--choose-backend` function to only return the `request--curl-sync` symbol but that still resulted in the same error.

At this point, I'm wondering that it might be an issue between cygwin's curl and a curl compiled specifically for w32.

To briefly test this, compiled emacs from source directly under cygwin (the w32 build I am using is directly from the GNU mirror) and loaded my same config... And now everything works!  Of course, now that means that I would have to deal with how painfully slow cygwin emacs is, but that is not your issue.

If I have time tomorrow, I will try to have my w32 emacs load a curl that was been compiled specifically for w32 and see if that fixes things.

**Comment by jtecca** [comment]
Apparently, I've been flush with free time today.  I installed a w32-natively compiled curl and put it into my Windows' PATH variable before the cygwin/bin tools.

I had to still `pop` the cygwin/bin path from my emacs' exec-path, and verified that w32 emacs is now pointed to the new w32 curl via `find-executable`.  

I ran `org-jira-get-issue` with a known issue and -- it works!  The blame goes entirely on me for running a frankenmacs setup.

I'm not sure if there is a good way for me to still use the cygwin binaries for the tools that do work well but only use this specific w32 curl, but I will hack around more on my own.

**Comment by ahungry** [comment]
Awesome analysis, thanks for digging into this further!

**Comment by edgimar** [comment]
For those who may have found this issue but are still unable to get curl to work after updating it, it may be a problem of missing certificates, as described in issue #39.  A straightforward explanation of how to add the missing certificates can be found [here](https://superuser.com/a/442797).
