### ISSUE TITLE
org-get-issues doesn't complete. Wrong type argument: stringp,

### ISSUE THREAD

**Issue by jamesrichardsonjr** [ahungry/org-jira#53]
Perhaps its custom field or some such thing. I don't know how to really debug this, so I'ma asking for help here.

Thanks.

This is from the *Messages* buffer

REQUEST [debug] REQUEST
REQUEST [debug] Run: curl --silent --include --location --compressed --cookie /home/james/.emacs.d/request/curl-cookie-jar --cookie-jar /home/james/.emacs.d/request/curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --data-binary @- --request POST --header Authorization: Basic omit --header Content-Type: application/json https://tools.lowes.com/jira/rest/api/2/search
REQUEST [debug] REQUEST--CURL-CALLBACK event = finished

REQUEST [debug] REQUEST--CURL-CALLBACK proc = #<process request curl>
REQUEST [debug] REQUEST--CURL-CALLBACK buffer = #<buffer  *request curl*>
REQUEST [debug] REQUEST--CURL-CALLBACK symbol-status = nil
REQUEST [debug] REQUEST--CALLBACK
REQUEST [debug] (buffer-string) =
HTTP/1.1 200 OK
Date: Fri, 02 Jun 2017 01:42:17 GMT
Server: Apache-Coyote/1.1
X-AREQUESTID: 1302x2046358x1
X-ASESSIONID: ofje5
X-ASEN: SEN-3876129
X-Seraph-LoginReason: OUT
X-Seraph-LoginReason: OK
X-AUSERNAME: jrichar
Cache-Control: no-cache, no-store, no-transform
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: User-Agent
Content-Type: application/json;charset=UTF-8
Set-Cookie: crowd.token_key=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; HttpOnly
Set-Cookie: crowd.token_key=fxHMrV76SqLvm7TmibzDWg00; Path=/; HttpOnly
Set-Cookie: JSESSIONID=F315FD985E02009ED9E954FFC70B9F2C; Path=/jira; Secure; HttpOnly
Transfer-Encoding: chunked

{"expand":"names,schema","startAt":0,"maxResults":100,"total":1,"issues":[{"expand":"operations,versionedRepresentations,editmeta,changelog,renderedFields","id":"261292","self":"https://tools.lowes.com/jira/rest/api/2/issue/261292","key":"GEN-170","fields":{"customfield_15000":"com.atlassian.servicedesk.plugins.approvals.internal.customfield.ApprovalsCFValue@38874556","customfield_12010":"Not started","customfield_13102":null,"fixVersions":[{"self":"https://tools.lowes.com/jira/rest/api/2/version/17243","id":"17243","name":"AIX - June Release","archived":false,"released":false}],"customfield_13500":null,"resolution":null,"customfield_12410":null,"customfield_12413":null,"customfield_13502":null,"customfield_12412":null,"customfield_10104":null,"customfield_12008":null,"customfield_10105":null,"customfield_12007":null,"customfield_12403":null,"customfield_12009":null,"customfield_12405":null,"customfield_12801":null,"customfield_10900":null,"customfield_10902":null,"customfield_10903":null,"customfield_10906":null,"lastViewed":null,"customfield_14300":null,"customfield_14301":null,"customfield_12002":null,"customfield_12001":null,"customfield_10100":null,"customfield_12004":null,"customfield_10101":null,"customfield_12003":null,"customfield_10102":null,"customfield_12006":null,"labels":["Genesis_Infrastructure"],"customfield_12005":null,"customfield_11700":null,"customfield_13603":null,"customfield_13605":null,"customfield_13604":null,"aggregatetimeoriginalestimate":null,"timeestimate":null,"versions":[],"issuelinks":[],"assignee":{"self":"https://tools.lowes.com/jira/rest/api/2/user?username=jrichar","name":"jrichar","key":"jrichar","emailAddress":"james.richardson@lowes.com","avatarUrls":{"48x48":"https://tools.lowes.com/jira/secure/useravatar?ownerId=jrichar&avatarId=17802","24x24":"https://tools.lowes.com/jira/secure/useravatar?size=small&ownerId=jrichar&avatarId=17802","16x16":"https://tools.lowes.com/jira/secure/useravatar?size=xsmall&ownerId=jrichar&avatarId=17802","32x32":"https://tools.lowes.com/jira/secure/useravatar?size=medium&ownerId=jrichar&avatarId=17802"},"displayName":"James Richardson","active":true,"timeZone":"America/New_York"},"status":{"self":"https://tools.lowes.com/jira/rest/api/2/status/10600","description":"","iconUrl":"https://tools.lowes.com/jira/images/icons/statuses/generic.png","name":"New","id":"10600","statusCategory":{"self":"https://tools.lowes.com/jira/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"To Do"}},"components":[],"customfield_15100":null,"customfield_13200":null,"customfield_11300":null,"customfield_14803":null,"customfield_14801":null,"customfield_12901":null,"customfield_14802":null,"customfield_12900":null,"aggregatetimeestimate":null,"creator":

I removed everything from until the success line as it has many emails descriptions with potentially confidential information.... I know sucks for a bug report/help request.

REQUEST [debug] symbol-status = success
Tag :GEN_170: set in 1 headings
not: Wrong type argument: stringp, ((customfield_15000 . "com.atlassian.servicedesk.plugins.approvals.internal.customfield.ApprovalsCFValue@38874556") (customfield_12010 . "Not started") (customfield_13102) (fixVersions . [((self . "https://tools.lowes.com/jira/rest/api/2/version/17243") (id . "17243") (name . "AIX - June Release") (archived . :json-false) (released . :json-false))]) (customfield_13500) (resolution) (customfield_12410) (customfield_12413) (customfield_13502) (customfield_12412) ...)

**Comment by jamesrichardsonjr** [comment]
Yes, it is still not happy:
REQUEST [debug] symbol-status = success
Tag :GEN_62: set in 1 headings
not: Wrong type argument: stringp, ((customfield_15000 . "com.atlassian.servicedesk.plugins.approvals.internal.customfield.ApprovalsCFValue@490ee3bc") (customfield_15400) (customfield_12010 . "Not started") (customfield_13102) (fixVersions . []) (customfield_13500) (resolution) (customfield_12410) (customfield_12413) (customfield_13502) ...)


I have no idea even where to start looking for the cause. :(

**Comment by jamesrichardsonjr** [comment]
It seems to have problems only with task_subtasks...

**Comment by jamesrichardsonjr** [comment]
could this somehow be related to my emacs version (25.2.2) org version (9.1.2) or jira version (7.2.7). It seems to download the same issue over and add the same multiple times to the org file.

**Comment by mibcadet** [comment]
I got the exact same problem, moving backward through request.el changes isn't helping. I got no idea how to fix such problems, I am not best at lisp ;/

**Comment by jamesrichardsonjr** [comment]
With the recent upgrade of Jira to 7.13.1, this is now working for me.
