### ISSUE TITLE
Question: Could org-jira be the foundation for an external-systems interface layer?

### ISSUE THREAD

**Issue by khaije1** [ahungry/org-jira#60]
From time to time I find myself wishing that other systems in my life were as well integrated into org-mode as Jira is, (thanks to org-jira).

`<thought experiment>`
What if this is actually possible and we're looking at the beginnings of it here?
How would we describe the steps looking backward from that possible future?
`</thought experiment>`

**Comment by ahungry** [comment]
Nice prompt, I think it definitely could be.

**Comment by khaije1** [comment]
I'll close this to reduce clutter. If other similar questions come up in the future I'll give the wiki a go. Thanks!
