### ISSUE TITLE
Feature: Add new org-jira-progress-issue-next

### ISSUE THREAD

**Issue by ahungry** [ahungry/org-jira#63]
Feature: Add new org-jira-progress-issue-next

Many times, issues will progress along a common path (todo, in-progress, done etc.) or (todo, in-progress, code-review, qa, uat, done).

It would be nice to allow the user to specify a list of path progression and a function that will check the current progress of issue and immediately jump to the next progress state in list.

**Comment by yisraeldov** [comment]
When ever I try to use this or `org-jira-progress-issue` I get an error. 

```
Wrong type argument: listp, 116
```

Any Idea how to get this to work 

Also If I mark an issue CLOSED in orgmode and update to jira, it gets remarked as TODO. Is there any way to progress issues from within the org-mode buffer?

**Comment by ahungry** [comment]
Yes, usual usage of org-jira-progress-issue (which this leverages) is supposed to just bump it to the next level.  If you're getting that error, it may be possible you're attempting to move the issue from one status to another via org-mode that is not compatible with your actual Jira instance.

For instance, a simple setup has states:

TODO -> In Progress -> Done

But a more complicated Jira may use:

TODO -> In Progress -> QA -> UAT -> Done

And if you attempt to move it from TODO -> Done (skipping the server defined jira flow) you can hit an error such as this.
