### ISSUE TITLE
Get all issues from project

### ISSUE THREAD

**Issue by drym3r** [ahungry/org-jira#64]
Hi,
Is there any possibility to get all issues from a project if those are not assigned to me? I didn't find an option for this. 

Thanks for your time and work.

**Comment by ahungry** [comment]
This comes from this:

```lisp
(defcustom org-jira-default-jql
  "assignee = currentUser() and resolution = unresolved ORDER BY priority DESC, created ASC"
  "Default jql for querying your Jira tickets."
  :group 'org-jira
  :type 'string)
```

You could update it to not include the assignee.

**Comment by drym3r** [comment]
Thank you very much!

**Comment by ahungry** [comment]
np!
