### ISSUE TITLE
logout feature?

### ISSUE THREAD

**Issue by matyasselmeci** [ahungry/org-jira#67]
I mistyped my password and now I can't connect. Is there anything I can do short of quitting and restarting emacs?

**Comment by ahungry** [comment]
Sure, M-x set-variable jiralib-token nil, or eval the following:

`(setq jiralib-token nil)`

Should do the trick.

You could also just manually call `M-x jiralib-login` to be re-prompted and enter it in yourself.

Part of the problem with the login not catching this is that the login is just a base64 encoded string, it doesn't do a test endpoint to confirm the credentials that get encoded are valid.
