### ISSUE TITLE
Question/enhancement: sparse-trees

### ISSUE THREAD

**Issue by rranelli** [ahungry/org-jira#68]
Hi,

First, thanks for the great package :)

I heavily use sparse-trees in my org flow;

However, top level headings are always shown on sparse trees; Since `org-jira-get-issues` adds issue as top level headings, sparse-trees are not really that usefull.

Is there a way to use them with the current project files layout?

A solution to this would be to nest all issues inside a top-level heading. A natural choice would be to use the project name as the top level heading;

**Comment by ahungry** [comment]
So that's why sparse-trees never seemed that useful... :smile: 

Good idea, I'll see what I can do.

**Comment by ahungry** [comment]
New branch sparse-trees should be fully usable, can you try it out and let me know what you think?

If it seems to work without any big issues, I may bump to 3.0.0 and push into master.

**Comment by rranelli** [comment]
Wow, that was fast.

I will use it next week and let you know if something is amiss

thankyou!

**Comment by ahungry** [comment]
Hm, issue atm, if the task description has `*` in it, I'm replacing too much whitespace that it's causing the star to be a top level headline.

Will work on a fix to that.

**Comment by ahungry** [comment]
Fixed in 146a90b1060a0e6421ab1cad316793460c178c88

**Comment by ahungry** [comment]
Well, now that this is mainline master, closing!
