### ISSUE TITLE
Question: Manually update time remaining

### ISSUE THREAD

**Issue by nickstares** [ahungry/org-jira#70]
Hello,

How would I go about writing a function to set the time remaining to 0?

Thanks!

**Comment by ahungry** [comment]
You mean to tie in with the worklog sync functionality where org-clocks are translated to worklog timestamp entries and vice-versa?

This may be difficult at the moment, as I don't believe I'm pulling the total work/time estimate at the moment.

If you know that a task has a 3 hour budget, you could always just org-clock-in, org-clock-out and hand edit the org-clock to span a 3 hour time (hit `C-c C-c` on said clock entry to recompute the displayed sum before doing the worklog or issue sync for good measure).

**Comment by nstares0** [comment]
Yeah, I wanted to be able to update my time remaining without changing my logged time. 
If you ever end up pulling the total work/time estimates, it would be cool to implement this feature.

Thanks for your help!

**Comment by ahungry** [comment]
I've always used Jira to set a total time / time remaining, and then have worklog entries reduce the time.  Is a common workflow to set total time and then manually set/adjust time remaining?

Most likely it would just be 2 additional per-issue properties I need to sync back and forth.

**Comment by nstares0** [comment]
I have no idea what is common, but I've been asked at my job to always set the remaining time to 0 after I finish a ticket.
