### ISSUE TITLE
error in process sentinel: Wrong type argument: number-or-marker-p, nil

### ISSUE THREAD

**Issue by qianmarv** [ahungry/org-jira#73]
Hello,

While using `getIssuesFromJqlSearch`, always get the issue: error in process sentinel: Wrong type argument: number-or-marker-p, nil

After some tries, found that inside function jiralib-call in jiralib.el, below code 

      ('getIssuesFromJqlSearch  (append (cdr ( assoc 'issues (jiralib--rest-call-it
                                                              "/rest/api/2/search"
                                                              :type "POST"
                                                              :data (json-encode `((jql . ,(first params))
                                                                                   (maxResults . ,(second params)))))))

If I change the type from "POST" to "GET" then it works fine, what could be the reason?

My environment:
OS: Win10
Emacs: 25.1 with spacemacs 0.200.10.x

Regards,
Marvin

**Comment by ahungry** [comment]
Usually this crops up due to something assumed to be a string actually being a nil value without coercion - I'm not sure why this endpoint would now be using GET over POST though, as you usually cannot send JSON data via GET requests.

While the error goes away, can you confirm the response received is still valid/expected?

**Comment by qianmarv** [comment]
You're right we can't use Get to send JSON data, it just I think in this case it is not necessary to put data in JSON and post it. 
For my case, we have lots of project in jira, so I have to get the issues only under the project I currently worked, so I add one function call in jiralib-call, such as in below, and to answer your question, it returns correct data set.

('getIssuesByProject  (append (cdr ( assoc 'issues (jiralib--rest-call-it
                                                          "/rest/api/2/search"
                                                          :params `((jql . ,(format "assignee = currentUser() and resolution = unresolved and project = %s" (first params)))
                                                                    (maxResults . ,(second params))))))
                                                               nil))

**Comment by ahungry** [comment]
Nice, want to make a PR and i can add it to the codebase?

**Comment by qianmarv** [comment]
Okay, will do, Thanks.

**Comment by qianmarv** [comment]
But, still don't why Post didn't work.
