### ISSUE TITLE
Adjustments/Feedback for the Sparse Tree's feature

### ISSUE THREAD

**Issue by nickgarber** [ahungry/org-jira#74]
Hiya, 

I've found that the new top-level heading is going above the '#+SETUPFILE: path/to/file' directive I add to the top of my org-jira files.

 - Could the sparse trees feature be made optional, perhaps with a default value in customize and file-based property override?
 - Could the top-level heading be added just before the first entry as opposed to the top of the file?

references:
- This request relates to #68 for which you asked for testers but I was unable to help out at the time.
- https://orgmode.org/guide/Properties.html

**Comment by ahungry** [comment]
I can definitely fix overriding file properties, but is there a good reason to not want the extra nesting?  Granted it takes a little bit to get used to (it would involve a lot of iffy (get it? haha) code in a lot of areas to make it customizable, since some of it is done in odd areas and with manual star insertion).

**Comment by nickgarber** [comment]
Nope, I don't mind the nesting so am content to keep it.

I think I experienced inconsistent indentation in a couple buffers as this
change hit but haven't been able to develop a test case for it, and it may
be related to the existence of the '#+SETUPFILE:' directive. If that
amounts to anything I could open a separate issue.

Thanks!

**Comment by nickgarber** [comment]
As the person that submitted this issue, I dont feel it needs to stay open so I'll close it.

I use org-jira daily and no longer feel that this negatively impacts my use or enjoyment of it.

**Comment by ahungry** [comment]
Glad to hear, thanks :)
