### ISSUE TITLE
Might fail when user id needs captcha -> add suggestion: log in via browser

### ISSUE THREAD

**Issue by ArneBab** [ahungry/org-jira#75]
In initial setup I got the error message that accessing the server failed. The reason was that JIRA requested a CAPTCHA. Logging in from the browser and solving the CAPTCHA there solved the problem. I cannot reproduce it right now, because solving the CAPTCHA made the problem go away and I had restarted Emacs in the meantime (so I don’t have the old Messages buffer with the debug messages).

Thank you for org-jira! I’ll be testing it.

**Comment by seanlynch** [comment]
We have our server set up to use Duo, so I'm having this same problem. Working around it for now by copying the cookie, but this or using OAuth seems like it would be far more secure.

**Comment by ahungry** [comment]
If anyone wants to make a PR for this, go for it.

**Comment by ArneBab** [comment]
Can you give me a hint where to start in the code?
