### ISSUE TITLE
Convert jira link format to org link format

### ISSUE THREAD

**Issue by ibizaman** [ahungry/org-jira#76]
Hi, thanks for this tool it is really neat!

I was wondering if org-jira could, on issue refresh or update, transform jira link format to org link format.

So when refreshing an issue, we would transform:
```
[my description|http://mylink.com]
```
to
```
[[http://mylink.com][my description]]
```
And in the opposite way when updating an issue.

Did I miss this somewhere?

**Comment by ahungry** [comment]
It isn't in there currently - are you hoping to transform all link references?  Such as links in descriptions/comments etc.?  I think there could be a problem if someone had a code block (for instance) which included a link in the org format - we would then be auto-translating it into the jira format as we sent the data back.

Speaking of which, translating `{code}` blocks to org src blocks would also be nice, but I'm not sure how feasible that is (it would be a big task, I think someone may have suggested it previously).

**Comment by ibizaman** [comment]
You beat me to it. I'd like to convert the src blocks and the lists too. I want to believe this is possible. I'll probably try to tackle it at some point.
