### ISSUE TITLE
Multiple remote Jira instances

### ISSUE THREAD

**Issue by paralin** [ahungry/org-jira#77]
How can I configure multiple remote Jira instances?

At the moment I use Google so I already have to use this workaround:

```
(setq jiralib-url "https://myjira.atlassian.net/")
(defconst jiralib-token `("Cookie" . "ajs_anonymous_id=....."))
```

Without diving into the code too much yet, I haven't found a way to set up more than one remote instance.

**Comment by ahungry** [comment]
Sorry, at this time there isn't support for multiple remotes (you could make a function to switch between the jiralib-url / jiralib-token pairs, which I think would work well enough if you didn't have any project names that overlapped.

**Comment by paralin** [comment]
@ahungry Probably that function could also change the root directory for the org files too, right? If you're fetching to files, that is.

Where's the best place for me to put this? It'd be nice if I didn't have to make wrapped versions of every command.

Thanks for the help on this
