### ISSUE TITLE
Allow ability to change project-file name

### ISSUE THREAD

**Issue by travispavek** [ahungry/org-jira#79]
I have macros defined to search for things like current sprint and fixversion. However they always want to use the project key filename which muddles things up. It would be great to be able to set the filename so that I can separate these searches into different org files.

**Comment by ahungry** [comment]
Instead of a file with an autoname based on project key (like EX.org or AHU.org) you want to have a user customizable prefix?  or some type of override map, so you may define:

```lisp
(("EX" . "your-file-name") ("AHU" . "your-other-name")
```

?

**Comment by travispavek** [comment]
No, what I was thinking was the ability to have different files for custom queries.  So for example I maybe would would have a search on fix version and I may want to save them to a file based on the fix version, or a sprint etc. It would probably only be something useful when using a saved macro. 

But, enhancement issue #22 would probably make this much less useful.

**Comment by scaba** [comment]
> Instead of a file with an autoname based on project key (like EX.org or AHU.org) you want to have a user customizable prefix? or some type of override map, so you may define:
> 
> ```lisp
> (("EX" . "your-file-name") ("AHU" . "your-other-name")
> ```
> 
> ?

A user-defined prefix would be great. I prefix my work-related files with "w-" so it would be great to have all of the Jira files listed along with them

**Comment by Fuco1** [comment]
I want this as well and probably implement it as an alist.  It is a little bit more configuration but gives more flexibility than simply providing a prefix.

Would that work for you @scaba ? Let's move the discussion to the new thread instead.

(Note: this is *not* the feature OP is asking for.  I will create a new issue)

**Comment by ahungry** [comment]
Please look at feature/Custom-JQLs before working on anything big, there is a bit of rework going on in there to make user customizable JQL + issue into filename placement occurring.

The user will be able to dictate which JQL runs and goes into which file as such:

```
         (setq org-jira-custom-jqls                                                                                                                                       
           '(                                                                                                                                                             
             (:jql " project IN (EX, AHU) and createdDate < '2019-01-01' order by created DESC "                                                                          
                   :limit 10                                                                                                                                              
                   :filename "last-years-work")                                                                                                                           
             (:jql " project IN (EX, AHU) and createdDate >= '2019-01-01' order by created DESC "                                                                         
                   :limit 10                                                                                                                                              
                   :filename "this-years-work")                                                                                                                           
             (:jql "                                                                                                                                                      
         project IN (EX, AHU)                                                                                                                                             
         and status IN ('To Do', 'In Development')                                                                                                                        
         AND (labels = EMPTY or labels NOT IN ('FutureUpdate'))                                                                                                           
         order by priority, created DESC "                                                                                                                                
                   :limit 20                                                                                                                                              
                   :filename "ex-ahu-priority-items")                                                                                                                     
             ))   
```

I won't merge any PR that conflicts with this branch, as I don't have time to rework it or merge anything until this one is done.

**Comment by Fuco1** [comment]
Noted, but I already sent the PR :D  No problem though, I'm going to use my code in the meantime because it does what I need and if we decide I can do the rebase/merge on top of your work later. Cheers!

**Comment by ahungry** [comment]
Thanks!  I'll just merge it for now and delay the jql stuff slightly so all users can benefit for your nice update immediately.  Thanks again for the pr
