### ISSUE TITLE
Question: How to filter out finished issues?

### ISSUE THREAD

**Issue by yangchenyun** [ahungry/org-jira#80]
Once an issue is completed/done, a user would like them to be exempted from the org-jira-get-issues result, is there a way to excluding them?

**Comment by ahungry** [comment]
We just had a feature added for filtering incoming worklogs: jiralib-worklog-import--filters-alist - you can also customize some of the JQL 

```lisp
      (defcustom org-jira-default-jql
	"assignee = currentUser() and resolution = unresolved ORDER BY                                                                                                 
        priority DESC, created ASC"
	"Default jql for querying your Jira tickets."
	:group 'org-jira
        :type 'string)
```

I think you can probably customize the JQL as is to prevent the REST calls from receiving cretain issues.

**Comment by yangchenyun** [comment]
@ahungry This API is awesome, thanks!
