### ISSUE TITLE
Question: Can Jira Statuses be mapped to Org workflows?

### ISSUE THREAD

**Issue by tamoore** [ahungry/org-jira#81]
Sorry if this has been asked before, I had a look at the docs and the issues but couldn't find a related question/answer.

Essentially I have a sequence set up for org mode and I'd love to map that sequence to the statuses in jira.

For example, I might have the following sequence:

```
#+SEQ_TODO: TODO(t/!) NEXT(n/!) WAITING(w@/!) IN_PROGRESS(i/!) PROJECT(p/!) SOMEDAY(s/!) | DONE(d/!)
```
And so if a jira task is in in progress I would love to map that so that it is updated in org with the following:

```
** IN_PROGRESS Location Component :RI_26:
   :PROPERTIES:
   :status:   In Progress
   ...some propreties
   :END:
   - State "IN_PROGRESS" from "TODO"       [2018-03-19 Mon 06:59]
  :LOGBOOK:
   :END:
*** description: [[https://jira//browse/RI-26][RI-26]]
  ...some description

```

**Comment by ahungry** [comment]
@chuym just added something in 4e61c9d  that appears to be what you were hoping for.

**Comment by ProjectMoon** [comment]
Are there any examples what exactly should be in this new variable?

**Comment by chuym** [comment]
@ProjectMoon You want to set `org-jira-keywords-to-jira-status-alist` to something like this:

```
 (setq org-jira-keywords-to-jira-status-alist
       '(("In Progress" . "INPROGRESS")
         ("To Do" . "TODO")
         ("Code Review" . "PR")))
```
The key is a JIRA status, and the value is an org-mode keyword.

**Comment by ProjectMoon** [comment]
Thanks a lot. I put in my configuration like this:

```
  (setq org-jira-keywords-to-jira-status-alist
	'(("Open" . "TODO")
	  ("Reopened" . "TODO")
	  ("In Progress" . "PROG")
	  ("QA" . "DONE")))
```
When pulling down issues, it's throwing an error like this: `mapc: Wrong type argument: listp, "TODO"` Any ideas on what this?

**Comment by chuym** [comment]
@ProjectMoon this should solve it: https://github.com/ahungry/org-jira/pull/106

**Comment by Fuco1** [comment]
@ahungry Shouldn't this be called `org-jira-jira-status-to-org-keyword-alist` or something similar?

When I read the name of this option I couldn't understand it because it looked like it was mapping a jira keyword to jira status, which is weird :D

**Comment by chuym** [comment]
@Fuco1 I agree that name is not descriptive enough, changed it here: https://github.com/ahungry/org-jira/pull/112

**Comment by eliraz-refael** [comment]
There's no mention of this on the docs, could you add it to the docs?

**Comment by ahungry** [comment]
Theres a few other customs not on the first README, if you try M-x customize-group org-jira, you should see this as an available option.

It might be a nice idea to rework a bit of the documentation at some point (maybe an org file like read the org format).
