### ISSUE TITLE
Do something with jira ticket Labels?

### ISSUE THREAD

**Issue by benley** [ahungry/org-jira#83]
It looks like org-jira doesn't currently do anything with Labels from jira.  It would be great if those could become tags on the TODO items org-jira creates, or perhaps a list in properties.

**Comment by dupuchba** [comment]
how can I help to add this one ?

**Comment by ahungry** [comment]
You can feel free to implement it if you like - now that we are using an "sdk" to wrap around the Jira objects, we would want to do the following:

1. Map out the 'labels' type (list of strings etc.?)
2. Write the appropriate slots in the class objects to hold labels 
3. Write the extraction code to pull them out of the 'data' responses (the jira json) - optionally writing the appropriate API calls if we currently do not get labels in any of our data
4. Update the headline render code to take labels out of the objects via their slot accessors and put them in as org tags
5 (maybe nice) - figure how how to do the entire thing, but in reverse (so user can add org tags to a headline, and on issue update have them applied as labels on the jira side)

If it seems daunting, feel free to put in PR halfway through, asking for advice/suggestion on how its going so far.

**Comment by dupuchba** [comment]
Thanks a lot, I started to look at the code and the Jira API, it should be faisable.
I don't understand some choices though, e.g. the use of `jiralib-complete-callback` as a global var but it's request specific IMO.
In the same "spirit" Jira is now in it's 3rd API version, as a maintener of a Clojure project, I guess you did not have time to upgrade the v2 -> v3, I might help.

One other question is more structural, I see the 2 main uses of `org-jira` : 
- a "REPL" one : I want to quickly check in a temp buffer what are my current issues for example (or what my new teamate is working on)
- a mid/long term one : like a projectile project folder, I want to version all my issues, see what are the new one and refresh the sprint/project..

I am really interested in you opinion.

Concerning the label, I think I'll find some time this week-end to look at it, I am a newbie in elisp but I love lisp languages and I get the basics of elisp

**Comment by ahungry** [comment]
Yes, see line 289 comment about that:

           ;; @todo :auth: Probably pass this all the way down, but I think                                                                                              
           ;; it may be OK at the moment to just set the variable each time.                                                                                             
           (setq :complete-callback
                 ;; Don't run with async if we don't have a login token yet.                                                                                             
                 (if :token callback nil))


It needs a refactor to take the received callback in jiralib-call and shove it along the entire function call chain, or the global.  The global was the quick fix, and has avoided most edge cases so far.

**Comment by ahungry** [comment]
I haven't ever used it as a REPL based workflow (other than when developing new features and testing etc.).  It is not really readable output most the time, and as the mode name implies, org-jira (basically, represent jira issues in org buffers, and vice versa).

With some decent pretty printers (I think I added one 'dump' one actually in the SDK refactor) it is ok in that workflow as well.

The new org-jira-get-issues-from-custom-jql call would definitely assist with displaying arbitrary query results to see current issues etc.

**Comment by TxGVNN** [comment]
Hi, I discover this package in recent, it's useful. Thanks for your work.
Today I see I need to render labels. I begin to research with less experience about lisp :P.

I found the `labels` field has the struct like as `component` field, So if we finish #103, it easy to clone to `labels` field.

The `components` field had existed, but I can not hack to render.
Does this function render to an org file?

[(defun org-jira--render-issue (Issue)](https://github.com/ahungry/org-jira/blob/master/org-jira.el#L1059)

I removed 2 lines in order to try to understand, but the org file after render still include ID and CUSTOM_ID.  I don't know what wrong.

```patch
- (org-jira-entry-put (point) "ID" issue-id)
- (org-jira-entry-put (point) "CUSTOM_ID" issue-id)
```

**Comment by TxGVNN** [comment]
Perhaps, I found something.
I deleted the org file, it renders the content that I wish. The components fields will render if it is not empty. (Seems my project did not use components, so I don't know it works =(( ).

I created the labels struct, but it doesn't still work. @ahungry  Could you have a look?

In `org-jira-sdk.el`
```patch
(defclass org-jira-sdk-issue (org-jira-sdk-record)
   ((assignee :type (or null string) :initarg :assignee)
+   (labels :type string :initarg :labels)
    (components :type string :initarg :components)
```

```patch
(cl-defmethod org-jira-sdk-from-data ((rec org-jira-sdk-issue))
  (cl-flet ((path (keys) (org-jira-sdk-path (oref rec data) keys)))
    (org-jira-sdk-issue
      :assignee (path '(fields assignee name))
+     :labels (mapconcat (lambda (c) (org-jira-sdk-path c '(name))) (path '(fields labels)) ", ")
      :components (mapconcat (lambda (c) (org-jira-sdk-path c '(name))) (path '(fields components)) ", ")
```

In `org-jira.el`
```patch
+ (defun org-jira-get-issue-labels (issue)
+  "Return the labels the ISSUE belongs to."
+  (mapconcat
+   (lambda (comp)
+     (org-jira-find-value comp 'name))
+   (org-jira-find-value issue 'fields 'labels) ", "))
```

```patch
(defun org-jira--render-issue (Issue)
  "Render single ISSUE."
  (org-jira-log "Rendering issue from issue list")
  (org-jira-log (org-jira-sdk-dump Issue))
-  (with-slots (filename proj-key issue-id summary status components priority headline id) Issue
+  (with-slots (filename proj-key issue-id summary status labels components priority headline id) Issue
...
            (mapc (lambda (entry)
                    (let ((val (slot-value Issue entry)))
                      (when (or (and val (not (string= val "")))
                                (eq entry 'assignee)) ;; Always show assignee
                        (org-jira-entry-put (point) (symbol-name entry) val))))
-                  '(assignee filename reporter type priority resolution status components  created updated))

+                  '(assignee labels filename reporter type priority resolution status components  created updated))
```

**Comment by ahungry** [comment]
This is looking good, thanks for making a PR.  I will test it and let you know what I find.

The issue you reference regarding components was more for having a way to interactively select which ones to put in the issue, rather than a missing sync function IIRC.

**Comment by ahungry** [comment]
Gonna close this issue, as labels should show up in the property drawer now that this has been merged.  Thanks @TxGVNN

**Comment by TxGVNN** [comment]
Thanks for the quick test and merge. That is really good when I see you still actively maintain because Emacs is perfect and org-jira is great package help me work better. 

Thank you again and wish you health to continue the wonderful work!

**Comment by chrislockard** [comment]
Thank you both for your great work! This package may solve my biggest workflow gap, and I'm very appreciative that you've worked on it.

I may be missing something, but it does not appear possible to change labels in the org buffer and have them reflect in JIRA. 

For instance, if I edit an existing issue's :labels: property in my org-jira buffer and run 'org-jira-update-issue', I see a status message about the issue updating in JIRA (at https://jira.example.com/projects/PROJECT/summary), but the labels aren't acutally updated. When the org-jira buffer refreshes, the original labels are present.  

Am I doing something wrong, such as editing labels incorrectly or is what I'm trying to do not currently possible?

**Comment by TxGVNN** [comment]
Hi @chrislockard,
I'm not sure the labels will be updated or not. Because at the time when there I just need to pull the labels. 
Currently, I've switched a new job without using JIRA=)). So I have not used this package again.

Perhaps you should look by yourself and feel free to contribute
