### ISSUE TITLE
Changing issue assignee doesn't seem to work

### ISSUE THREAD

**Issue by FrancisMurillo** [ahungry/org-jira#86]
Hello,

When I try to use `org-jira-assign-issue`, it does not seem to change the designated assignee. 

(Don't know how else to describe this.)

**Comment by lvsv** [comment]
Try to fix `request.el` https://github.com/tkf/emacs-request/issues/77 and use this patch https://github.com/lvsv/org-jira/commit/357920926c6386dd4275caafc789331d3ac33287

**Comment by klochowicz** [comment]
This issue still persists - I'm getting 
`[error] request--callback: peculiar error: 400`. 

emacs 26.1, self-hosted Jira instance, the patch mentioned earlier has been merged into org-jira since then...
