### ISSUE TITLE
Support for the Issue/Worklog Accounts property

### ISSUE THREAD

**Issue by nickgarber** [ahungry/org-jira#87]
I can appreciate that not everyone will use this plugin. Just wanted to register the request. :)

refs:
 - http://developer.tempo.io/doc/accounts/api/rest/latest/
 - https://community.atlassian.com/t5/Answers-Developer-Questions/using-tempo-API-to-add-worklog-in-JIRA-on-behalf-of-someone-else/qaq-p/496055
 - https://community.atlassian.com/t5/Answers-Developer-Questions/How-to-set-Tempo-Account-with-API/qaq-p/511803

(edit: 20190805, consolidating references in the desc)

**Comment by ahungry** [comment]
I'm going to close this issue as it's more a feature request and seems tied to a third party plugin that I don't plan on using.  If you (or anyone browsing this) would like to support integration in org-jira.el, I'm not opposed, I just can't contribute, and it doesn't seem like there is a lot of interest in this.

Thanks though!

**Comment by nickgarber** [comment]
Hiya @ahungry, I'd be willing to look into adding this support. Should I treat it as a plugin to org-jira, and if so how would you like it's integration to happen? Alternatively I could just add the code as normal and base it's activation on some combo of a customization variable and an available endpoint.

Just wanted to get your thoughts on this before getting cracking.

Cheers!

**Comment by ahungry** [comment]
I'll reopen if you'll work on this, adding directly to the package is fine, that's what defcustoms are for :smile:

**Comment by nickgarber** [comment]
Sure, I'll take point, though slowly. 😅
This'll be entirely new territory for me.

**Comment by nickgarber** [comment]
Just noting where to look for myself .... http://developer.tempo.io/doc/accounts/api/rest/latest/

**Comment by nickgarber** [comment]
Looking into this and I wonder if custom fields, (such as 'Account'), could be handled generically using the property -to- field mapping provided via `org-jira-property-override` ... ?

For example, the Tempo plugin add's an issue-level custom fields for `Account` when it's installed. Custom fields are get/set using the same Jira API as other issue fields, but take the form `customfield_<int>`, where `<int>` is a reference number that can vary by instance. Stated plainly, the reference number used by one Jira instance won't match the one used by another Jira instance, even for the same custom fields, created by the same plugin, for the same purpose, at the same time. 

Basically, the idea is that if a property from `org-jira-property-overrides` exists in the current issue, the properties value will be paired for update with the corresponding Jira field name.


So to sync the 'Account' field at the issue level we have to already have the number, (and ideally the display name), for each custom field we want to interact with. To be clear, this is an inelegant, one-time, manual effort, but opens upa covering more surface area

I see potential to use the existing variable `org-jira-property-override`, to cover this use-case. I'm just a few percent into the work on this but it feels promising.

Before I go to much further I wanted to run a couple prospective changes by you, @ahungry :
- Would you be OK with adding a new hashtable cache for field and permissions discovery?
- Would you be OK with adding a requirement on https://github.com/Wilfred/ht.el in jiralib.el ?
- Would you be OK with supplementing or mutating `org-jira-property-override`'s data structure to support different values for different servers? 

In the next few days I'll kick things off with a WIP PR and work this task "in public" in order to welcome all appropriate feedback and chastening.

**Comment by ahungry** [comment]
Sure, I think all 3 sound fine.  @nevetS was asking about some custom fields stuff here: https://github.com/ahungry/org-jira/issues/22 - maybe you guys can coordinate on it in some way?

**Comment by nickgarber** [comment]
Sound good! 

To make practical progress I'll tackle this in phases, (possibly spread across multiple issues/PRs):
1. support sync'ing explicitly defined custom fields
2. opportunistically use mappings in `org-jira-property-override` if a matching field/property is found
3. use Jira's `createmeta` API to discover, list, and cache custom field info for sync
4. use Jira's `mypermissions` API to discover, list, and cache field permissions, to prevent disallowed update requests

For this specific issue I'm setting my sights on tasks 1 and 2.
