### ISSUE TITLE
org-jira-get-issues fails

### ISSUE THREAD

**Issue by piyushkapadia** [ahungry/org-jira#88]
Brand new install GNU Emacs 25.3.1 (x86_64-w64-mingw32) with no other extra packages except org mode and org-jira latest from stable melpa.

jiralib-url is setup correctly and authentication works fine.

Fails to get with below error with org-jira-get-issues call 

Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
<omit>
  org-jira-get-issue-list(#[(&rest data) "\302\303\301\304\305\"\"A\306\"\307	!)\207" [data issues append assoc cl-getf :data nil org-jira-get-issues] 6 "Callback for async, DATA is the response from the request call.\n\n(fn &rest DATA &allow-other-keys)"])
  call-interactively(org-jira-get-issues record nil)
  command-execute(org-jira-get-issues record)
  execute-extended-command(nil "org-jira-get-issues" nil)
  funcall-interactively(execute-extended-command nil "org-jira-get-issues" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by ahungry** [comment]
This sounds like it's occurring on Windows, someone with that OS will need to assist, as from the error dump I don't see anything obvious.

Did you ever get it working?  Or gave up on org-jira?

**Comment by ahungry** [comment]
Btw, when pasting error logs, please make sure to remove the Authorization: Basic <token> info, it isn't needed (I deleted most your log in comment as there were a few references of it).
