### ISSUE TITLE
Use of smart quotes prevents issues from updating.

### ISSUE THREAD

**Issue by mbatema-apixio** [ahungry/org-jira#91]
I'd witnessed updates to an item's description field being swallowed, and turned on `requests` logging:
```
REQUEST [debug] (buffer-string) =
HTTP/2 400 
server: Atlassian Proxy/0.1.244
cache-control: no-cache, no-store, no-transform
content-type: application/json;charset=UTF-8
strict-transport-security: max-age=315360000; includeSubDomains; preload

SNIP

x-seraph-loginreason: OK

{"errorMessages":["Illegal unquoted character ((CTRL-CHAR, code 28)): has to be escaped using backslash to be included in string value\n at [Source: org.apache.catalina.connector.CoyoteInputStream@78dbfa09; line: 1, column: 1805]"]}
```

It turns out that in my `summary` field, the contents had "smart quotes" (seen in the payload when org-jira does a fetch to obtain the newly updated contents): `\342\200\234decision\342\200\235`.

I haven't dug to see if this is an issue with the implementation of InputStream Jira is using, an issue with the library org-jira is using for JSON encoding, or with org-jira itself. However, whether transitively inherited or not, it is a limitation for org-jira.

**Comment by lvsv** [comment]
I created a task  with `summary` field  “decision",  executed  `org-jira-get-issues` and everything was okey, no issues.
I think it is the same problem in `request.el` library, as i wrote in https://github.com/ahungry/org-jira/issues/98, without this fix https://github.com/tkf/emacs-request/issues/77  you can't update fileds with non-ascii symbols. 
Can you try the fix of  request.el and test again?
