### ISSUE TITLE
Sprint Info

### ISSUE THREAD

**Issue by gburch** [ahungry/org-jira#92]
With the addition of the "Get Issue from Board" feature it would be nice to include some information on the sprint an issue is in. The easiest would be to include it in the PROPERTIES drawer. I believe _rest/agile/latest/issue/_ includes the same info you are getting from the API endpoint but includes additional information about sprints and closedSprints. The more involved way would be to build off the board work and have the ability to choose a sprint and get the issues from that sprint.

**Comment by ahungry** [comment]
Feel free to add the PR, this would be a nice update.
