### ISSUE TITLE
"Not an issue region"

### ISSUE THREAD

**Issue by Myz** [ahungry/org-jira#94]
I had a look into the source code and found out that a regexp is being used in order to find the current headline. Therefore it looks for `**` which might not be there when displaying the task list indented where the second `*` is being omitted.

It expects this kind of structure:
```
* Main headline
** Sub headline
```
But in my buffer it looks like this:
```
* Main headline
  * Sub headline
```
Note the indentation on the second line.
https://orgmode.org/manual/Clean-view.html

Even disabling https://github.com/sabof/org-bullets does not help.

**Comment by ahungry** [comment]
The headline parser (regex) would have to be updated to accommodate the Clean-view mode (neat option in org for sure).

Does the clean view just affect the display, or does it cause the files themselves to be saved with leading spaces instead of stars?  (does the raw file still have stars?)

The entire org-jira is only set up / tested / functional with the non-clean (standard) view at the moment, so I would add the option to disable this in your PROJ.org buffers you plan to use org-jira in for now.

**Comment by Myz** [comment]
As I found out, the raw buffer still contains the double stars (`**`), the first ones foreground color is just the same as the background color.

Sure I did a test with not having anything from my config like that:

```
~$ cd $(mktemp -d)
/tmp/tmp.lgoFlg708e$ cat > .emacs <<EOF
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)

(setq jiralib-url "https://**********/jira")
EOF
/tmp/tmp.lgoFlg708e$ env HOME=$(pwd) emacs
```
Then I installed the packages `org` & `org-jira`, restarted emacs just to be sure.
Then I ran `M-x org-jira-get-issues` which then prompts me for the username and the password. Once entered it pulls down all my issues and opens up the buffer in the window.

Now I log some time on some issue with the org clock in `C-c C-x C-i` and out commands `C-c C-x C-o`,

All good until here.

Then when I try to push these changes with `M-x org-jira-update-worklogs-from-org-clocks RET` back again it fails because it is not finding the headline aka `Not on an issue region!`.

The buffer is in MAJOR Org and MINOR jira mode.

**Comment by ahungry** [comment]
Does `org-jira-update-issue` command work?  It should also update the clocks (it calls the command you're calling directly, however after potentially navigating to acceptable spot).

Also the position of LOGBOOK is important - your structure should look like this:

```
* PROJ-Tickets
** TODO Some task :PROJ-123:
  :PROPERTIES:
  <snip>
  :END:
  :LOGBOOK:
  CLOCK: <whatever>
  :END:
  *** description: PROJ-123
    Some description
```

**Comment by Myz** [comment]
After pulling the issues with `M-x org-jira-get-issues RET` it looks like this to me:
```
* DEV-Tickets
** TODO bla bla bla :DEV_6430:
   :PROPERTIES:
   :assignee: my
   :reporter: someoneelse
   :type:     Story
   :priority: Default
   :status:   Open
   :END:
```
The description is completely missing even thou there is one in the jira itself for the specific ticket.
The previous output from my `*Messages*` buffer might be related to that: `org-jira-find-value: Wrong type argument: listp, (description . ".....`.

I also tried to update only that single ticket with `M-x org-jira-update-issue RET` while having the cursor ON the headline and this was the outcome:
```
org-jira-update-issue: Not on an issue
```

**Comment by iqrow** [comment]
I'm also experiencing this, let me know if there's anything I can help with, or information to provide to to debug this. Thanks!

**Comment by ahungry** [comment]
Are you also using Clean View? @iqrow

**Comment by ahungry** [comment]
Wow!  I would have not found that out (never looked at that package before).  I'm going to close this then - unrelated, how do you like that package?

Thanks for the find.

**Comment by Ragenvald** [comment]
So how to fix this issue?

**Comment by Myz** [comment]
@Ragenvald I think the best way to solve this at the moment is to disable the emoji layer in your spacemacs configuration.

**Comment by KMontag42** [comment]
Yes @Myz @Ragenvald the fix that I was able to find was to disable the `emoji-cheat-sheet-plus` layer in my spacemacs configuration. Everything went back to normal afterwards.
