### ISSUE TITLE
Add comment in Org buffer?

### ISSUE THREAD

**Issue by nwautomator** [ahungry/org-jira#95]
Is it possible to add a new comment to an issue within the project's buffer? When I grep through the code I see a function called "jiralib-add-comment", but I wasn't sure if this function was used to build the comments in the Org buffer when pulling issues from Jira. Thanks in advance!

**Comment by iocanel** [comment]
It works for me by adding:

    * Comment:
       <my comment here>

and the calling `org-jira-update-comment`.

**Comment by ahungry** [comment]
Yup, that's the best way to do it.  I think we could add a helper / minibuffer prompt that just has someone type a comment in and does an insert into the proper issue slot, but that would be a new feature.

**Comment by ahungry** [comment]
Added in 3.1.0, try out `C-c c c`

**Comment by nwautomator** [comment]
@ahungry yep, confirmed that the new command works! Thanks!
