### ISSUE TITLE
 Symbol’s function definition is void: org-clock-drawer-name

### ISSUE THREAD

**Issue by skybert** [ahungry/org-jira#97]
Hi,

thanks for a great mode!

```
M-x org-jira-update-issue
```

Gives me:
```
org-jira-update-worklogs-from-org-clocks: Symbol’s function definition is void: org-clock-drawer-name
```

Versions:
```
org-jira-20180521.707
Org-mode version 8.2.10 (release_8.2.10 @ /usr/share/emacs/25.1/lisp/org/)
GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian
```

**Comment by skybert** [comment]
Upgrading to a later org version resolved the issue. Apparently, the Org version bundled with Emacs 25.1 isn't compatible.

This version Org contains the above mentioned function:
```
Org mode version 9.1.13 (9.1.13-elpa @ /home/torstein/.emacs.d/elpa/org-9.1.13/)
```

**Comment by ahungry** [comment]
I should make it check for the function presence - it already defaults to LOGBOOK if the user hasn't customized this setting in newer orgs.  That would make org-jira work with bundled Emacs I believe.

**Comment by skybert** [comment]
Sounds good @ahungry
