### ISSUE TITLE
Problems with non-ascii symbols in comments or assignee

### ISSUE THREAD

**Issue by lvsv** [ahungry/org-jira#98]
May be it will help someone.

Save problem.
I can't create comments, or modify any of them if it has non-ascii symbols.
When request.el uses curl to send request to jira, it saves all data in /tmp/USER/emacs-request* files before send it. Without this fix https://github.com/tkf/emacs-request/issues/77  request.el will convert utf8 in some binary garbage. The request will fail due to data validation. 

Representation problem.
If you have a comment in worklog, or when you choose Assignee in org-jira-assign-issue, data is not converted from \xxx\xxx format into utf8 string. 
I changed org-jira-get-assignable-users (added org-jira-decode to displayName and key)  and now i have correct names in org-jira-assign-issue.
I changed org-jira-insert-clock function (added org-jira-decode to clock-entry) to fix worklog's comments.

**Comment by ahungry** [comment]
Nice find, thanks @lvsv

**Comment by lvsv** [comment]
Duplicate #130
