### ISSUE TITLE
org-jira-find-value: Wrong type argument: listp, []

### ISSUE THREAD

**Issue by iqrow** [ahungry/org-jira#99]
First of all thank you for this package! I only installed today, so I apologise for
any ignorance, but I've encountered some issues and I was wondering if anyone knew why.
Perhaps I haven't set everything up correctly.

Context: Spacemacs on Mac

After running `org-jira-get-issues-headonly` and getting a shortlist of issues:

The first time I press `RET` to follow the link to the issue buffer from this list I
see the following output in the *Messages* buffer:

```
REQUEST [debug] symbol-status = success
Use M-x make-directory RET RET to create the directory and its parents
Tag :PROJ_1179: set in 1 headings
org-jira-find-value: Wrong type argument: listp, []
```

It seems to create the PROJ.org file and it automatically navigates to it

The second time I `RET` a link, it seems to add the issue to the PROJ.org buffer
but does not automatically navigate to it, is this expected behaviour?

```
REQUEST [debug] symbol-status = success
Tag :PROJ_1142: set in 1 headings
org-jira-find-value: Wrong type argument: listp, []
```

Anything I can do to debug this? Thanks.

**Comment by ahungry** [comment]
I've never really used the headonly feature (it was a carry over from when I inherited the package).  I'll have to take a look, as the org-return doesn't seem to even go anywhere on my machine (I just use org-jira-get-issues and fold them up in org)
